### PR TITLE
Make iOS integration tests fail the build

### PR DESCRIPTION
**Pull request by premun**
I fixed the issues in iOS and it is stable now. We should get notified about possible next failures (someone breaking the SDK..)

### CODE REVIEW

**Comment by premun** [comment]
@MattGal iOS is fine, I think Android as well. Do you agree we can flip this?

**Comment by MattGal** [comment]
> @MattGal iOS is fine, I think Android as well. Do you agree we can flip this?

I don't think so, unless we got new test apps.  The test apps I was using tended to randomly fail their instrumentation.  @steveisok , is that issue resolved yet?  (In which case we could swap out the APKs and then fail on failure)

**Comment by premun** [comment]
> I don't think so, unless we got new test apps. The test apps I was using tended to randomly fail their instrumentation. @steveisok Steve Pfister FTE , is that issue resolved yet? (In which case we could swap out the APKs and then fail on failure)

Hm.. then I will just do the iOS one

**Comment by premun** [comment]
@MattGal I removed the flip for Android and only iOS will fail the build. iOS hasn't failed in the last month or more so it is safe to assume it is stable

**Comment by MattGal** [comment]
> @MattGal I removed the flip for Android and only iOS will fail the build. iOS hasn't failed in the last month or more so it is safe to assume it is stable

Sounds good.  We have an FR issue to give the emulators more RAM that might solve this soon.

**Comment by premun** [comment]
@MattGal can you approve please?

**Review by MattGal — APPROVED** [review]

**Pull request merged**
