### PR TITLE
Arcade CI failing due to component governance errors

### PR DESCRIPTION
**Pull request by epananth**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

Issue -> https://github.com/dotnet/arcade/issues/13326

### CODE REVIEW

**Comment by garath** [comment]
It looks like these came up after changes in #13210. @ViktorHofer FYI, in case you want to review this.

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
Marking as request changes so that I can first take a look. Thanks for letting me know.

**Comment by premun** [comment]
cc @MilenaHristova

**Comment by ViktorHofer** [comment]
I submitted https://github.com/dotnet/arcade/pull/13341 which is the better fix as it avoids these dependencies all-together. There's a remaining set of packages that are problematic, which I will work on in the next days:
- Microsoft.Extensions* brings in https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation
- Azure.Core brings in `System.Net.Http/4.3.4` which transitively brings in X509Certificates/4.3.0.

We can enable [Arcade's FlagNetStandard1xDependencies switch](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/TargetFrameworkFilters.BeforeCommonTargets.targets#L21) when those dependencies are updated and consumed. That will then guard against any future netstandard1.x dependencies being consumed.

**Comment by epananth** [comment]
Thanks @ViktorHofer, going to close this PR.

**Pull request closed without merging**
