### PR TITLE
Add "No CDN" flags to .NET Install Script usage from eng/common

### PR DESCRIPTION
**Pull request by MattGal**
### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation (if these changes don't work, all CI builds will fail)

### CODE REVIEW

**Review by Chrisboh — APPROVED** [review]

**Comment by MattGal** [comment]
Relevant logging bits from the [PR build](https://dev.azure.com/dnceng/public/_build/results?buildId=1053272&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef&t=3ccc3669-e0b9-50c6-efe1-cc0487c0e6c1):

Windows:

```

dotnet-install: Downloading primary link https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\workspace\_work\1\s\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
```

Source build: (linux)

```
dotnet-install: Downloading primary link https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/__w/1/s/.dotnet`. Note: This change will be visible only when sourcing script.
```

**Comment by akoeplinger** [comment]
@MattGal this will make the install experience much worse for everyone not in US-West where the `dotnetcli` storage container lives since the download speeds are awful if you pull from the blob storage directly.

Compare:

```bash
$ wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-linux-x64.tar.gz

156,10M  2,01MB/s    in 2m 29s

$ wget https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.2.21155.3/dotnet-sdk-6.0.100-preview.2.21155.3-linux-x64.tar.gz

156,10M  9,29MB/s    in 17s
```

What's the reason for this change?

**Comment by MattGal** [comment]
@akoeplinger people use these scripts in Helix work items (asking them to stop did not help) and it accounts for many tens of thousands in CDN fees, estimating more than the entire cost of the rest of the world combined.  I'm chatting with @Chrisboh about reverting it now though.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/7147, will merge after discussing with @Chrisboh

**Comment by akoeplinger** [comment]
Don't we pay for bandwith fees on the blob storage container too? And as far as I know blob storage has a fixed quota of traffic per container so the more hits we get the slower it'll get.

If the Helix usage is such a huge driver then we should focus on that and not just ask nicely :)

**Comment by MattGal** [comment]
> Don't we pay for bandwith fees on the blob storage container too? And as far as I know blob storage has a fixed quota of traffic per container so the more hits we get the slower it'll get.

CDN costs more than double storage per GB.

> 
> If the Helix usage is such a huge driver then we should focus on that and not just ask nicely :)

With the number of folks in Europe who've pinged me this morning, yes we'll probably do that.

**Pull request merged**
