### PR TITLE
Allow for repo specific Publish properties

### PR DESCRIPTION
**Pull request by livarcocc**
Allow for repo specific Publish properties such as add additional files to be published

### CODE REVIEW

**Comment by mmitche** [comment]
@tmat Probably needs to take a look here.

**Comment by livarcocc** [comment]
@tmat is OOF. Can I say sorry later?

**Comment by mmitche** [comment]
yweah

**Comment by tmat** [comment]
If you need a quick workaround setting the property in Versions.props file should work.

Do we think repos will need to configure publishing? If so I'd call that imported file `Publishing.props` as we already have `Signing.props`.

**Comment by mmitche** [comment]
@livarcocc Can you point me to the code where you're specifying the additional files?

**Comment by livarcocc** [comment]
@mmitche https://github.com/livarcocc/core-sdk/blob/official_builds/eng/Publish.props

**Pull request merged**
