### PR TITLE
Update dependencies from .net eng - validation channel

### PR DESCRIPTION
**Pull request by riarenas**
* [X] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

@missymessa @adiaaida this updates from the validation channel to get the updated versions for v3 publishing.

### CODE REVIEW

**Review by missymessa — APPROVED** [review]
LGTM shipit

**Comment by riarenas** [comment]
Woops this is downgrading roslyn. Update incoming

**Comment by riarenas** [comment]
ok, it looks good now. Setting auto-merge

**Pull request merged**
