### PR TITLE
Add tizen riscv64 rootfs and cross build support

### PR DESCRIPTION
**Pull request by gbalykov**
Change similar to https://github.com/dotnet/arcade/pull/11832.

Part of https://github.com/dotnet/runtime/issues/84834
cc @t-mustafin @clamp03 @ashaurtaev

### CODE REVIEW

**Comment by gbalykov** [comment]
cc @am11

**Review by am11 — APPROVED** [review]
LGTM, thanks!
cc @janvorli, @akoeplinger

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by HJLeee — APPROVED** [review]
LGTM, Thank you.

**Review by clamp03 — APPROVED** [review]
Thank you

**Comment by gbalykov** [comment]
@am11 @janvorli can this be merged?

**Comment by janvorli** [comment]
@gbalykov can you please rebase the change on the latest main?

**Comment by gbalykov** [comment]
@janvorli done

**Comment by am11** [comment]
@ViktorHofer, can we lift the "must rebase" restriction from shell scripts which are not used in this repo at all? (which begs the old question; do these scripts really belong here? 😅)

**Review by ashaurtaev — APPROVED** [review]

**Review by JongHeonChoi — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> @ViktorHofer, can we lift the "must rebase" restriction from shell scripts which are not used in this repo at all? (which begs the old question; do these scripts really belong here? 😅)

Unsure what you mean by that. @janvorli would you be able to provide an answer to am11's question?

**Comment by am11** [comment]
@ViktorHofer, I was referring to these merging policies:
image

Files under `eng/common/cross` are not used by the CI. Can we exclude this path from CI trigger?

**Pull request merged**
