### PR TITLE
Quick script fixes

### LINKED ISSUE #3395: Telemetry mismatch in tools.sh
In tools.sh, line 80:

```bash
    Write-PipelineTelemetryError -category 'InitializeTools' "Error: Cannot find \"$key\" in $global_json_file"
```

Everywhere else this category is `'InitializeToolset'`. We need to fix it to that.

### PR DESCRIPTION
**Pull request by jonfortescue**
Tested and the script for logging changes is not gonna break things lol.

cc/ @mjanecke this fixes #3395 (the obnoxious telemetry mismatch).

### CODE REVIEW

**Comment by riarenas** [comment]
Is there an issue that this is fixing?

**Comment by jonfortescue** [comment]
@riarenas attached the issue it's fixing.

**Pull request merged**
