### PR TITLE
Allow opting-out of PackageReferences for individual projects

### PR DESCRIPTION
**Pull request by wtgodbe**
Allows us to opt repo projects out of these global PackageReferences.

@weshaggard PTAL

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @ericstj 

@wtgodbe can you please add this condition to the other PackageReferences that are in the targets/props (not the ones pulled into the tools.proj).

**Comment by weshaggard** [comment]
>Why is this needed?

For the corefx model we don't want individual projects to have PackageReferences in them as we only restore once for the repo. For our normal flow these don't have much impact but there are some scenarios where they cause us some issues. One example is we generate a project we try to restore and it imports our common Directory.Build.props/targets and as such it tries to restore these packages as well but the restore sources for that restore don't have the correct feeds to find these packages and we also don't want or need these packages for those projects so it seems like a waste to add another feed and restore packages we don't use. 

We could create an property to disable just these PackageReferences but I tend to think we should have a more general property that allows repo's like corefx to opt-out of all individual project package references as we don't want or need them there and they only cause potential issues. Another issue we just (https://github.com/dotnet/corefx/pull/33173) had to workaround is VS restoring our projects where we don't want any restore to happen on them, they never used to restore because they had no PackageReferences but now they have these references in scope.

**Comment by tmat** [comment]
Thanks for details. Wouldn't adding
```
<ItemGroup>
  <PackageReference Remove="*"/>
</ItemGroup>
```

to `Directory.Build.targets` work for CoreFX?

CoreFX is rather special. Maybe there will be one more repo that needs this, but I don't think this belongs to Arcade SDK.

**Comment by wtgodbe** [comment]
@tmat we need this for the Standard repo as well. I don't believe we'd want to clear out all PackageReferences in `Directory.Build.targets`, as that'd risk clearing out PackageReferences from our targets, or even clearing them out from some other external source that we haven't anticipated. Rather than a general solution, I'd rather scope it to the PackageRefs from Arcade - I suppose the options then would be to take this change, or to clear out the Arcade PackageRefs specifically:

```
<ItemGroup>
  <PackageReference Remove="Microsoft.SourceLink.GitHub"/>
  ...
</ItemGroup>
```

**Comment by tmat** [comment]
@wtgodbe I don't understand. Either you want per-project packages or you don't. From what @weshaggard explained it looks like the repo is not restoring projects at all, instead all packages are restored upfront from Tools.proj. I don't see why you'd want some packages and not others. That doesn't make much sense to me.

**Comment by wtgodbe** [comment]
Actually, we should be able to get around this issue with https://github.com/dotnet/buildtools/pull/2198 for now. We can revisit this in the future if necessary.

**Comment by weshaggard** [comment]
>@wtgodbe I don't understand. Either you want per-project packages or you don't. From what @weshaggard explained it looks like the repo is not restoring projects at all, instead all packages are restored upfront from Tools.proj. I don't see why you'd want some packages and not others. That doesn't make much sense to me.

There is a mix of projects. Our library projects we don't want PackageReferences nor do we want to restore them. However there are some projects we do want to restore as part of our repo restore and they need package references. For now we have decided to fix the current problem a different way but I do think we should consider at least adding an flag for these SourceLink packages similar to what we have for UsingToolXliff.

**Pull request closed without merging**
