### PR TITLE
Fix encoding of common loc lss file

### PR DESCRIPTION
**Pull request by carlossanlop**
@cristianosuzuki77 @ViktorHofer @ericstj 

This file was last flowed into dotnet/runtime by the dependency bot as a binary file. https://github.com/dotnet/runtime/pull/90014

The file should be treated as plain text / xml.

The GitHub diff still thinks this extension is a binary file, but if you click on View File, it now looks like a plain text xml file, instead of showing monospaced characters to indicate it's binary. See before: https://github.com/dotnet/runtime/blob/a29a13b27ce9ee16b7dac4edede4994c433200ce/eng/common/loc/P22DotNetHtmlLocalization.lss

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Should we mark .lss files as plain text in this repo's .gitattributes file?

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
> Should we mark .lss files as plain text in this repo's .gitattributes file?

Levi _just_ mentioned the same to me. I'll fix that too.

**Comment by carlossanlop** [comment]
@ViktorHofer  Does that mean we need to make the same .gitattributes modification to all repos that inherit from arcade, or is that file also going to be flowed with dependency flow PRs?

**Comment by ViktorHofer** [comment]
> @ViktorHofer Does that mean we need to make the same .gitattributes modification to all repos that inherit from arcade, or is that file also going to be flowed with dependency flow PRs?

Ideally in all repos as the file doesn't flow into consuming repos. It's on a per repository basis. I think just having it in arcade and runtime for now should be sufficient. The origin (where it is originally checked in) is the most important place.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
