### PR TITLE
Delete the Microsoft.DotNet.Build.Tasks.IO task

### PR DESCRIPTION
**Pull request by natemcmaster**
The remaining tasks in this project were made obsolete by moving their functionality into MSBuild itself. (see https://github.com/Microsoft/msbuild/pull/3398)

Follow-up to https://github.com/dotnet/arcade/pull/244

### CODE REVIEW

**Comment by natemcmaster** [comment]
@chcosta this fails on CI because there are no more test projects.

> There was an error processing the xunit test results - this means there was a test failure (or build failure) upstream. Look above in the log. [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/artifacts/Debug/TestResults/*.xml'. Configuration error?.

Should we create a dummy test project or change the CI config?

**Comment by chcosta** [comment]
Comment out the relevant CI config.  Sad that we don't have any tests.

**Comment by natemcmaster** [comment]
Ok, I removed the test reporting in Jenkins config. It will probably still fail, though, right? CI doesn't use updated .groovy files from PRs IIUC.

**Comment by chcosta** [comment]
Right, it will probably still fail

**Comment by natemcmaster** [comment]
@chcosta yup, 4 reds. Are you otherwise okay with this change?

**Pull request merged**
