### PR TITLE
Add option to quiet down the chatter on merge PRs

### PR DESCRIPTION
**Pull request by nguerrera**
When -QuietComments is passed:

1. Don't tag authors of commits moving between branches in merge description
2. Don't comment on every PR update

I did some basic testing on nguerrera/test-bot

### CODE REVIEW

**Comment by nguerrera** [comment]
We're getting spammed since moving to this bot. cc @dsplaisted

**Comment by nguerrera** [comment]
Follow up, how do I wire QuietComments into the trigger, is it already set up that I can just add another switch to the json somehow or does something on the back end also need to change?

**Comment by mmitche** [comment]
> Follow up, how do I wire QuietComments into the trigger, is it already set up that I can just add another switch to the json somehow or does something on the back end also need to change?

@nguerrera I added a variable to the build def which can be used to pass the switch.  To enable, add:

```
"QuietComments": "-QuietComments"
```

to the trigger parameters where needed, e.g.
https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L1246

**Comment by nguerrera** [comment]
Should this be something like "ExtraSwitches": "-QuietComments"

**Comment by mmitche** [comment]
> Should this be something like "ExtraSwitches": "-QuietComments"

Changed to "ExtraSwitches"

**Pull request merged**
