### PR TITLE
Add .NET package icon to all packages by default.

### PR DESCRIPTION
**Pull request by tmat**
The icon can be changed by setting PackageIconFullPath property to the full path of the desired icon.
To include icon in projects with hand-written .nuspec add `$CommonFileElements$` under `<files>` element, e.g.

```xml
<files>
  $CommonFileElements$
  <file src="netcoreapp2.0\MyLib.dll" target="tools\netcoreapp2.0" />
</files>
```

### CODE REVIEW

**Comment by tmat** [comment]
@wtgodbe Might need to follow up on this, where the icon has been added explicitly, e.g.: https://github.com/aspnet/EntityFrameworkCore/pull/18105

**Comment by dougbu** [comment]
Great this has been merged. Will it flow into Arcade's 'master' branch at some point (or must that be done separately)?

**Comment by tmat** [comment]
@mmitche Said it should flow.

**Comment by mmitche** [comment]
Here: https://github.com/dotnet/arcade/pull/4088

**Comment by dougbu** [comment]
@mmitche that'll bring in @joeloff's sign check fixes but
1. Not this change
2. Includes a "Revert changes to sign check version" commit which makes @joeloff's changes irrelevant (if I'm reading things correctly)

**Comment by mmitche** [comment]
Ahh it couldn't be updated because of conflcits.  I'll open a manual merge.

**Comment by ericstj** [comment]
Doesn't NuGet reccomend a 64x64 png?

**Pull request merged**
