### PR TITLE
Variables template

### PR DESCRIPTION
**Pull request by chcosta**
Azure DevOps has enabled variables to be loaded in the current [context](https://github.com/Microsoft/azure-pipelines-yaml/pull/46).

@mmitche, can you take a look and let me know your thoughts about refactoring our yaml to use this functionality?

Basically, this change adds a "variables" template which defines an `isInternal` variable

### CODE REVIEW

**Comment by jonfortescue** [comment]
@chcosta what is the status on this -- should we merge it?

**Comment by chcosta** [comment]
I'm not certain if there is sufficient value for this yet.  Let's hold off and allow more time to consider.

**Comment by jonfortescue** [comment]
@chcosta circling back -- any idea on if we should merge or close?

**Comment by jonfortescue** [comment]
@chcosta ping

**Comment by chcosta** [comment]
A fun exercise, but I don't think anyone is clamoring for this and it's probably not worth the risk at this point.

**Pull request closed without merging**
