### PR TITLE
Add LinqPad driver for the swagger generator

### PR DESCRIPTION
**Pull request by alexperovich**
This change adds a LinqPad driver for the swagger generator I have had in my back pocket for a while.

I also fixed the generation for "file" type responses to something that works.

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Are people really clamoring for this? To my knowledge, you are the only user of LinqPad I've ever encountered, and I'm worried about adding a bunch of code that needs to be maintained without some real user need.

**Comment by alexperovich** [comment]
I use it a bunch, and I want to check it in somewhere. I thought to just put it next to the generator stuff.

**Comment by ChadNedzlek** [comment]
I'm not sure that justifies the maintenance cost of this few thousand lines of code in a very important core repository.  Every line of code has an ongoing cost, so the benefits need to be there...

**Comment by tmat** [comment]
@alexperovich Why don't you create a private repo?

**Pull request closed without merging**
