### PR TITLE
Add option to build iOS apps on helix

### PR DESCRIPTION
**Pull request by steveisok**
This change adds awareness to the helix sdk to build apps on the helix instance themselves.  When `ShouldBuildApps` == `true` in the `CreateXHarnessAppleWorkItems` task, it will inform the `xharness-helix-job-apple` script of the mode.  The script will expect `build-apple-app.sh` to be part of the payload and execute the commands within.  It is assumed the script will build the app.  

After the build completes, the app and provisioning file will be in the same place as they are in other configurations and run.

### CODE REVIEW

**Comment by premun** [comment]
@steveisok was there a problem with just using the `CustomCommands`? Seems like we might have all we need already and you could plug in your new functionality this way without having to extend the SDK.

You could even keep the build script in its own file as is and do:
```xml
<CustomCommands>
  source build-apple.app.sh
  xharness apple test -t $target -o "$output_directory" ...
</CustomCommands>
```

Or is there something you were missing?

**Comment by steveisok** [comment]
Signing would still happen before the app is built and error out.

**Comment by premun** [comment]
@steveisok there is now a bash function available that you can use `sign [path to app]`.
The full order of things then should be:
```sh
source build-apple-app.sh # produces The.Test.app dir
cp embedded.mobileprovision ./The.Test.app
sign The.Test.app
xharness apple test -t $target -o $output_directory -a The.Test.app
```

**Comment by steveisok** [comment]
Isn't there still an if statement that tries to sign even before the custom commands are executed?  

Can we move that around somehow?  What would you suggest?

**Comment by premun** [comment]
There is one but I think it's harmless because our app won't exist yet:
```sh
    if [ -d "$app" ]; then
        sign "$app"
    else
        echo 'Device target detected but app not found, skipping signing..'
    fi
```

But we can also totally move it if you think there's a scenario this could hurt us.

My understanding is that you point the SDK to a zipped folder with all the build scripts and dependencies which will create the `.app` folder.

Once we have that, we can totally just do what I suggest above:
- Copy profile
- Sign
- Run via xharness

I think everything can happen inside of the `<CustomCommands>` which get injected into the line that says `source commands.sh`

**Comment by steveisok** [comment]
Ah, that is harmless indeed.  I'll switch to what you suggest.

**Comment by steveisok** [comment]
@premun I was able to incorporate your feedback and no longer need this change.

One thing to note, there is the option to aot for the simulator, which would mean we need to build on helix too.  In that case, we do not skip launching the simulator with an app that does not yet exist.  I don't think we'll need it at this time, but one thing to consider.

**Pull request closed without merging**
