### PR TITLE
SymTargets: Add dependent target

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by safern** [comment]
I can build a package with this change and publish to a myget feed and test it on the failing PR if needed.

**Comment by tmat** [comment]
Actually, if you have a the repo checked out locally, you can just make the change in the restored arcade package on your machine and try the build.

**Comment by JoeRobich** [comment]
We are still seeing errors during Roslyn builds in this mornings Arcade update (as we did with previous attempted updates this week). https://github.com/dotnet/roslyn/pull/39965 - [AzDO Build](https://dev.azure.com/dnceng/public/_build/results?buildId=435948)
```
  The system cannot find the path specified.
C:\Users\vsagent\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19571.10\tools\SymStore.targets(54,5): error MSB3073: The command ""C:\Users\vsagent\.nuget\packages\microsoft.diasymreader.pdb2pdb\1.1.0-beta1-62506-02\tools\Pdb2Pdb.exe" "F:\workspace\_work\1\s\artifacts\bin\Microsoft.CodeAnalysis\Release\netstandard2.0\Microsoft.CodeAnalysis.dll" /out "F:\workspace\_work\1\s\artifacts\SymStore\Release\Microsoft.CodeAnalysis\netstandard2.0\Microsoft.CodeAnalysis.pdb" /srcsvrvar SRC_INDEX=public" exited with code 3. [F:\workspace\_work\1\s\src\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj]
```

**Comment by tmat** [comment]
We'll get there, eventually: https://github.com/dotnet/arcade/pull/4424 :-/
Tested Roslyn ci with this change.

**Pull request merged**
