### PR TITLE
Hit version of SignTool in Arcade SDK

### PR DESCRIPTION
**Pull request by JohnTortugo**
Fix failure to test sign python binaries.

### CODE REVIEW

**Comment by chcosta** [comment]
Did you validate this with an internal build?

**Comment by JohnTortugo** [comment]
I'm not sure how to do this for this particular case. I'm updating the SDK itself, how can I get a .nupkg with that fix from a feed? The best I could do for now was to test the SignTool itself.

**Comment by chcosta** [comment]
push your change to the internal branch, build, update your change with the versions published via your internal build, push that to the internal branch, build again.  You're going to have to go through similar hoops after you merge or the sdk won't be using your change and will stay broken, right?

**Comment by chcosta** [comment]
@riarenas is working on automating this process, but for now you have to do a bit more work to validate you're actually fixing something.

**Comment by JohnTortugo** [comment]
Thank you @chcosta

**Comment by chcosta** [comment]
There's other reports of the exclusive lock preventing builds from completing today.  I don't know of a way to figure out who's actively holding the lease at the moment though :(

FYI @vatsan-madhavan @dotnet/dnceng @mmitche

**Comment by dagood** [comment]
When in doubt, look for a ProdCon publish. There's one running as of writing: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2197012&_a=summary&view=logs. It's normal for it to take hours.

https://github.com/dotnet/arcade/issues/1175 tracks infra changes to stop this from happening.

**Comment by chcosta** [comment]
Hmm... In the azure portal, if I look at the storage blob, it claims that the Lease State is "Broken".  The documentation claims

https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob

> "Break", to end the lease but ensure that another client cannot acquire a new lease until the current lease period has expired. 

Is someone intentionally "breaking" rather than "releasing"?  Is it possible to force release the lease?  I'd hate if that was an infinite timeout...

**Comment by chcosta** [comment]
I suppose that means we just have to monitor that build though.  Thanks for the link @dagood

**Comment by jcagme** [comment]
When working on this (probably more than a year ago) I intentionally broke the lease after stopping a test I was running. The status has been broken since and it won't change unless we delete the file and is regenerated by Sleet. If you break the lease intentionally it will be leased again by next package publish.

**Comment by chcosta** [comment]
Oh wow.  Thanks for the info.  That's really unfortunate.

**Comment by jcagme** [comment]
> When in doubt, look for a ProdCon publish. There's one running as of writing: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2197012&_a=summary&view=logs. It's normal for it to take hours.
> 
> #1175 tracks infra changes to stop this from happening.

What's the cadence of ProdCon builds? Does it take more than 3 hours to publish on every build?

**Comment by chcosta** [comment]
The current build is running for more than 3 hours

**Comment by jcagme** [comment]
Yeah, I'm trying to understand id this the average on every ProdCon build. Also, if ProdCon builds once a day, a week, etc.

**Comment by jcagme** [comment]
@JohnTortugo build's done BTW

**Comment by JohnTortugo** [comment]
Yeah, I just restarted mine.

**Comment by chcosta** [comment]
@JohnTortugo , thanks for letting me use your issue to get a better understanding of all the ways this is a terrible experience.  @jcagme @dagood , thanks for the insight.

**Comment by JohnTortugo** [comment]
> @JohnTortugo , thanks for letting me use your issue to get a better understanding of all the ways this is a terrible experience. @jcagme @dagood , thanks for the insight.

I also learned a few things today :-)

**Comment by JohnTortugo** [comment]
I'm finishing validation with this build: https://dnceng.visualstudio.com/internal/_build/results?buildId=42577&view=logs If everything goes well I'll merge this PR. \o/

**Pull request merged**
