### PR TITLE
Fix SymStore targets to fail build on error

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/arcade/issues/4370

### CODE REVIEW

**Comment by tmat** [comment]
@mmitche FYI

**Comment by mmitche** [comment]
Thanks, I had a similar fix in progress.  Fixes: https://github.com/dotnet/arcade/issues/4370

**Comment by ViktorHofer** [comment]
This broke the runtime repo: 

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19568.10\tools\SymStore.targets(22,41): error MSB4057: The target "CoreCompile" does not exist in the project. [D:\a\1\s\src\libraries\build.proj]
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19568.10\tools\SymStore.targets(22,41): error MSB4057: (NETCORE_ENGINEERING_TELEMETRY=Build) The target "CoreCompile" does not exist in the project.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=432049

We could work around this and add the CoreCompile target of course but I would like to understand/discuss the break first.

**Comment by tmat** [comment]
I'll take a look.

**Comment by tmat** [comment]
I think we can fix it by replacing `CoreCompile`, which is only available in managed projects, with `Build`.

**Comment by tmat** [comment]
https://github.com/dotnet/arcade/pull/4401

**Pull request merged**
