### PR TITLE
Revert "Refactor base and telemetry templates for repository reuse"

### PR DESCRIPTION
**Pull request by chcosta**
Reverts dotnet/arcade#385

official builds appear to be broken.  Reverting this change to determine what has changed before merging this.

FYI @jonfortescue @mmitche

### CODE REVIEW

**Comment by natemcmaster** [comment]
I think you'll have to manually push this to internal VSTS. https://github.com/dotnet/arcade/pull/385 broke the code-mirror config, so the code-mirror config can't mirror the change which fixes the code-mirror ;).

**Comment by chcosta** [comment]
Hmmm...  I'll follow up on that but it looks like the Revert successfully mirrored into devdiv.

https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Arcade-Trusted?_a=history

Thanks for the tip

**Comment by natemcmaster** [comment]
I was looking at https://dotnet.visualstudio.com/internal/_git/dotnet-arcade/commits

**Comment by chcosta** [comment]
Arcade doesn't build from there, but I certainly don't want it broken. I'll follow up

**Comment by natemcmaster** [comment]
Arcade may not build there, but I think it’s still used for the code-mirror config which copies aspnet repos into dotnet.visualstudio.com

**Pull request merged**
