### PR TITLE
[release/5.0] Update the SDK to 5.0 RC2

### PR DESCRIPTION
**Pull request by ViktorHofer**
We want to update the SDK from 5.0 RC1 to RC2.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Merging as approved by Tactics.

**Comment by riarenas** [comment]
Publishing for the official build of this change failed but it's not yet clear to me why.

https://dnceng.visualstudio.com/internal/_build/results?buildId=846794&view=results

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : Object reference not set to an instance of an object.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 93
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 95
```

FYI @epananth

**Comment by mmitche** [comment]
It's because the channel ".NET 5 Eng and .NET 5 Eng - Validation" doesn't exist in master yet. Arcade needs an update from itself to get the recently checked in code for that.

Unfortunately, it looks like runtime is broken again with the latest arcade validation: https://dev.azure.com/dnceng/internal/_build/results?buildId=846653&view=results fyi @ViktorHofer 

We can update arcade to a new arcade -validation though, if we want, which will solve the issue.

**Comment by ViktorHofer** [comment]
> Unfortunately, it looks like runtime is broken again with the latest arcade validation: https://dev.azure.com/dnceng/internal/_build/results?buildId=846653&view=results fyi @ViktorHofer

That runtime master, how is that relevant to NET 5? Looking at the failures right now.

**Comment by riarenas** [comment]
Makes sense to me to update arcade from validation for this. If Arcade breaks itself we will still guard other repos from seeing the break.

We probably also need better error reporting for this situation. I can see this as a not uncommon occurrence for repos as they change their default channels to newly created channels that might still not be ready in the arcade version used by the branch in charge of publishing.

**Comment by ViktorHofer** [comment]
> Looking at the failures right now.

@mmitche the failure is understood and expected. I need to react to https://github.com/dotnet/arcade/commit/cc7b7d1ee1d070cb3ccc2ffd6f4061850ddd232a in dotnet/runtime: https://github.com/dotnet/runtime/pull/43218.

**Comment by riarenas** [comment]
Retried the build after merging #6379 and now it succeeded.

**Pull request merged**
