### PR TITLE
Update dumpasync command executed on dumps

### PR DESCRIPTION
**Pull request by stephentoub**
To include more "call stack"-like information.
cc: @danmosemsft

### CODE REVIEW

**Comment by stephentoub** [comment]
> Is this dumping working? I was afraid it had rotted.

It's not, actually, at least not from what I've seen.  But I realized I had never updated the command in use after updating dumpasync to change its command-line args, so I figured I should make it right for if/when dumpling is fixed :)

**Comment by danmosemsft** [comment]
It looks like this is a corefx specific file, despite being in this repo. It seems to me this is all of generic interest and should be extracted (as part of making it actually work perhaps)
@ViktorHofer do you agree.

**Comment by safern** [comment]
> It looks like this is a corefx specific file, despite being in this repo. It seems to me this is all of generic interest and should be extracted (as part of making it actually work perhaps)
@ViktorHofer do you agree.

I think there is no intention on share this file because this are very specific to corefx. Other repos use dotnet test and simpler commands.

**Comment by danmosemsft** [comment]
Hmm, the script seems pretty generic to me, or not far off. Passed the location of the tools, tries to find a dump file, run the debugger and dump the results to console, upload the dump, ..  that's something CoreCLR would want (if they dont have it already)

**Pull request merged**
