### PR TITLE
Add dotnet/format to flow creation script

### PR DESCRIPTION
**Pull request by dkurepa**
We can revert this PR when https://github.com/dotnet/sdk/pull/38857 gets merged in

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Format now got merged into sdk.

**Comment by dkurepa** [comment]
Thanks for letting me know. I'll revert this. Did the change get merged before or after the p3 branching?

**Comment by ViktorHofer** [comment]
After.the branch-off.

**Comment by dkurepa** [comment]
Cool, thanks!

**Pull request merged**
