### PR TITLE
[release/5.0] Add support for additional DotNetRuntime (#7158)

### PR DESCRIPTION
**Pull request by riarenas**
## Description

https://github.com/dotnet/arcade/issues/7378

Cherry-pick of https://github.com/dotnet/arcade/commit/b61eaae19626f8e52614b5162ca518f1c6c56751 to mitigate SSL issues when trying to download the install scripts. 

## Customer Impact

Without this change, ASPNetCore's servicing builds are having a high rate of failure during the script downloads

## Regression

No

## Risk

How risky is this change?

Low

## Workarounds

no

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Review by MattGal — APPROVED** [review]
May be worth an experiment of adding the runtimes (without merging them) to the unit tests proj like Hao did to make sure there aren't surprises.

**Comment by riarenas** [comment]
>May be worth an experiment of adding the runtimes (without merging them) to the unit tests proj like Hao did to make sure there aren't surprises. 

Yep I'm getting a test build ready.

**Comment by riarenas** [comment]
Test build: https://dev.azure.com/dnceng/public/_build/results?buildId=1135039&view=results

I see in the binlogs that the added runtimes were added as correlation payloads.

**Comment by MattGal** [comment]
> Test build: https://dev.azure.com/dnceng/public/_build/results?buildId=1135039&view=results
> 
> I see in the binlogs that the added runtimes were added as correlation payloads.
> 
> image

Awesome, I appreciate the diligence.

**Pull request merged**
