### PR TITLE
[release/5.0] move the skip EOL target framework check to the post-build-templates

### PR DESCRIPTION
**Pull request by ghost**
As https://dev.azure.com/dnceng/internal/_build/results?buildId=1786939&view=results shows, keeping the property to skip the eol target frameworks in the azure-pipelines.yml file will end up breaking consumer repositories when they get the latest arcade changes. This change moves the property to the common templates. 

https://github.com/dotnet/arcade/issues/9440

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by riarenas** [comment]
I'm running https://dev.azure.com/dnceng/internal/_build/results?buildId=1787054&view=results to test this.

**Review by AlitzelMendez — APPROVED** [review]

**Comment by riarenas** [comment]
Also for what it's worth, it looks like the error is not a 100% repro. one of the test legs restored fine here: https://dev.azure.com/dnceng/public/_build/results?buildId=1789039&view=results

**Comment by riarenas** [comment]
Finally got a green build through a lot of retrying. @mmitche can you take a look when you get a chance since this is going into a release branch?

**Review by mmitche — APPROVED** [review]

**Pull request merged**
