### PR TITLE
Reorder tools and solution restoration

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/arcade/issues/4102

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera @dougbu

**Comment by nguerrera** [comment]
I'd prefer if it didn't rely on the ordering details and instead did not import SDKs from outside the repo cone, but if this works, I can live with it.

**Comment by nguerrera** [comment]
I think it would be better to remove SDK import from tools.proj if possible. The ordering/caching is an implementation detail IMHO.

**Comment by tmat** [comment]
I'll follow up and see if we can remove the import. We don't need to merge this PR unless a workaround is needed immediately.

**Comment by dougbu** [comment]
On immediate need: Soon would be good but perhaps not "immediate".

Problem is quite annoying but affects our team more than other devs because we are still doing 3.0.x and 3.1.0-previewY things as well as new work in 'master'. Problem doesn't impact our CI builds and is much less likely to trip up external contributors (I hope) e.g. we tend to ask external contributors to move changes _to_ 'master'.

/fyi @anurse @ajcvickers @mkArtakMSFT @Pilchie @wtgodbe @JunTaoLuo

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/arcade/pull/4111.

**Pull request closed without merging**
