### PR TITLE
Update SymUploader to 2.0.0-preview.1.21466.7

### PR DESCRIPTION
**Pull request by hoyosjs**
This is required to index some outstanding files in our packages.

### CODE REVIEW

**Comment by epananth** [comment]
can you please do a arcade promotion test with this version? ( probably promote it to general testing to make sure it works?)

**Review by mikem8361 — APPROVED** [review]

**Comment by hoyosjs** [comment]
I was about to post it but had some bumps with my branches. Here it is https://dev.azure.com/dnceng/internal/_build/results?buildId=1366714

**Review by epananth — APPROVED** [review]
LGTM

**Comment by epananth** [comment]
actually I checked the maestro promotion pipeline, and I saw this 

image

**Comment by epananth** [comment]
Go to general testing feed and get the latest feeds task and arcade sdk version and update it in your local arcade branch and promote any other build. That build should use the latest symUploader version. That will give the right result, this previous build still uses older symUploader version.

**Comment by hoyosjs** [comment]
Full one with a new arcade SDK + this https://dev.azure.com/dnceng/internal/_build/results?buildId=1367343&view=logs&s=380ab8c6-4139-55ff-15c4-fb48260f4dca&j=ba23343f-f710-5af9-782d-5bd26b102304

**Comment by hoyosjs** [comment]
image

and also checked on the new files. All looks good.

**Pull request merged**
