### PR TITLE
[release/6.0] Enable CG detection in the job templates (#8376)

### PR DESCRIPTION
**Pull request by mmitche**
Remove the explicit injection in the arcade pipeline

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
So far no major issues rolling this out in main.

**Review by riarenas — DISMISSED** [review]

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1576475&view=results

**Comment by agocke** [comment]
@mmitche any idea what's going wrong here? I have no idea how to debug this.

**Comment by agocke** [comment]
Nvm apparently Michal figured it out

**Comment by mmitche** [comment]
@riarenas Can I get final approval here?

**Comment by mmitche** [comment]
or @MattGal I ported the continueOnError to 6.0

**Review by riarenas — APPROVED** [review]
Oh, weird that it got reset.

**Pull request merged**
