### PR TITLE
Update Roslyn toolset version

### PR DESCRIPTION
**Pull request by agocke**
This should include all changes from before today.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @agocke.  This include [DoesNotReturn{If}] support, correct?  Does it also include [NotNullIfNotNull] support?  Just want to understand the intended scope.

**Comment by agocke** [comment]
I believe yes to DoesNotReturn, no to NotNullIfNotNull, cc @jcouv

**Comment by agocke** [comment]
NotNullIfNotNull should be in today, and I'll have a separate update for that.

**Comment by agocke** [comment]
Also, special casing for IEquatable<T> should go in today.

**Pull request merged**
