### PR TITLE
aka.ms link creation should also retry on TaskCanceledException

### PR DESCRIPTION
**Pull request by adiaaida**
When the HttpClient hits its Timeout, it throws a TaskCanceledException. We assumed that it threw an HttpRequestException. This change adds TaskCanceledException to the list of exceptions we catch and retry on during aka.ms link creation.

This also changes the name of CreateOrUpateLinkBatchAsync to CreateOrUpdateLinkBatchAsync.

Fixes https://github.com/dotnet/arcade/issues/6444.

### CODE REVIEW

**Review by riarenas — APPROVED** [review]
I get the feeling we've been bitten by the multiple exceptions that HttpClient throws more than once.

LGTM

**Review by mmitche — APPROVED** [review]

**Comment by markwilkie** [comment]
I like resiliency!

**Comment by adiaaida** [comment]
Just a note, this has been improved in .Net 5: https://github.com/dotnet/runtime/pull/2281

When we upgrade arcade-services to .NET 5/6, we can update these catches to check if the TaskCanceledException has an inner exception of TimeoutException.

See original issue and discussion here: https://github.com/dotnet/runtime/issues/21965

I will create an issue in arcade with this info to remind us that we can/should make these updates when we upgrade.

**Review by missymessa — APPROVED** [review]
LGTM shipit

**Review by sunandabalu — APPROVED** [review]
:shipit:

**Comment by ChadNedzlek** [comment]
If we ever actually support cancellation we'll have to be careful. Since actual cancellation would look similar, and we wouldn't want to retry if we are supposed to be cancelling. :-)

**Comment by riarenas** [comment]
Yeah. That was the motivation behind the httpclient change that's coming in .net 5. I think we'll have to wait until then to be able to support both things.

**Comment by MattGal** [comment]
> If we ever actually support cancellation we'll have to be careful. Since actual cancellation would look similar, and we wouldn't want to retry if we are supposed to be cancelling. :-)

There's an existing pattern all over in buildtools and arcade that can be followed, you just make sure the token doesn't match the one passed in to the cancel-able API before doing a timeout retry.

**Comment by ChadNedzlek** [comment]
Ugh... I don't like the change... you _still_ need a giant pile of special code for every HTTP request... they just make it different complicated code as of 5.0... so it's breaking, but not better. Yay. :-|

**Comment by ChadNedzlek** [comment]
I guess the thing you had to do currently (check the token to see if it's the "cancelly" token) will still work...

**Pull request merged**
