### PR TITLE
Do not validate queues unless Test target is called

### PR DESCRIPTION
**Pull request by krwq**
This allows us running different test projects on different queues in IoT repo (i.e. hardware dependent tests on ARM32 and hardware independent on AMD64 which are faster)

### CODE REVIEW

**Comment by safern** [comment]
cc: @alexperovich @jonfortescue

**Comment by alexperovich** [comment]
> This allows us running different test projects on different queues in IoT repo (i.e. hardware dependent tests on ARM32 and hardware independent on AMD64 which are faster)

How exactly does this change allow you to do this? This check needs to be where it is because none of the other targets are tested with empty target queues. It also makes no sense to run anything if there are no target queues.

**Comment by krwq** [comment]
@alexperovich, example scenario:

We have two subsets of tests:

U - unit tests - they should run on faster setup, i.e. ADM64
H - hardware tests - they need to run on ARM32

Inside of our project we create property: RunHardwareTests which runs H when set to `true` or U when set to anything else.
Other thing in our project is target `RunAllTests` which runs our project twice (calling msbuild task): 1. RunHardwareTests=true; RunHardwareTests=false.

You'd expect above to work but it turns out that even though the `Test` target is not called the build fails because `RunAllTests` fails the check I fixed in here because `ValidateTargetQueues` is run regardless if `Test` is being run or not. The fix here moves this target to run only when tests are being run.

**Comment by alexperovich** [comment]
Why do you need to build the project twice with different properties. And one of these invocations isn't expected to do anything?

Just have the project figure out what queue to send to based on if it is a hardware test or not.

**Comment by krwq** [comment]
@alexperovich currently there is no way to assign some projects to some queues. You have to assign all projects to all queues which won't work here correctly

**Comment by alexperovich** [comment]
What do you mean? Assign some projects to some queues? The HelixTargetQueue items are per project.

**Comment by krwq** [comment]
I.e. here https://github.com/dotnet/iot/blob/master/eng/sendToHelix.proj#L42 doesn't seem `HelixTargetQueue` is in any way related to `XUnitProject` - could you show an example on how would you achieve what you described?

**Comment by alexperovich** [comment]
So, you have a set of XUnit projects, and some of them need to run on ARM64 and some on ARM32 right? I would put both target queues in the sendToHelix.proj, then condition the XUnitProject includes on "Should this project run on this queue" e.g.

```
<HelixTargetQueue Include="Windows.10.Arm32.Iot"/>
<HelixTargetQueue Include="Windows.10.Arm64.Iot"/>

... later ...

<XUnitProject Condition=" '$(HelixTargetQueue)' == 'Windows.10.Arm32.Iot'" Include="HardwareTests.csproj"/>
<XUnitProject Condition=" '$(HelixTargetQueue)' == 'Windows.10.Arm64.Iot'" Include="NonHardwareTests.csproj"/>
```

You could also condition both items on a $(RunHardwareTests) property if that works better for you.

**Comment by krwq** [comment]
Thanks @alexperovich! I still think this validation regardless of the target is incorrect so I'll leave the PR open

**Comment by alexperovich** [comment]
The issue is that a Helix SDK project is malformed if it has no target queues set, it will not do anything useful. This validation is important to catch this error before trying to build/restore anything. That operation can take time. Validating the queues as an InitialTarget makes the error happen as soon as it can possibly happen.

**Comment by JohnTortugo** [comment]
Ping. Is this something that we want to merge?

**Comment by alexperovich** [comment]
I still agree with my past self. A helix project is not well formed if it doesn't have target queues set. None of the targets have been tested with this case and it will error with strange messages if this validation isn't here.

**Comment by safern** [comment]
We can close and keep discussion open. If we agree that this is needed we can re-open.

**Pull request closed without merging**
