### PR TITLE
Fix URL shown in Helix.SDK logs when in staging

### PR DESCRIPTION
**Pull request by premun**

### CODE REVIEW

**Review by lukas-lansky — APPROVED** [review]

**Review by lpatalas — APPROVED** [review]

**Comment by akoeplinger** [comment]
@premun I think this broke showing the production URL, e.g. from https://dnceng.visualstudio.com/public/_build/results?buildId=884957&view=logs&j=b6f63eff-75cc-59ca-fdbf-d2121601a613&t=3f89b0b1-a79b-5dad-cfb9-522fb012a84f
```
 Sending Job to Ubuntu.1804.Amd64.Android.Open...
  Sent Helix Job; see work items at /api/jobs/eae17619-7fc8-429c-8c7e-b778efb87c18/workitems?api-version=2019-06-17
  Waiting for completion of job eae17619-7fc8-429c-8c7e-b778efb87c18 on Ubuntu.1804.Amd64.Android.Open
```

It no longer logs the helix.dot.net hostname.

**Comment by alexperovich** [comment]
Yes, this broke that. the HelixBaseUri property isn't guaranteed to be set, because it gets defaulted by the task.

**Comment by premun** [comment]
Ah, will fix.

**Comment by premun** [comment]
Fixed here: https://github.com/dotnet/arcade/pull/6562

**Pull request merged**
