### PR TITLE
Fix publishing aka.ms secrets 

### PR DESCRIPTION
**Pull request by riarenas**
This change fixes https://github.com/dotnet/dnceng/issues/1109 and does a couple of things:

* Fixes the secret metadata so that secret-manager understands that this is an Entra application and not a GitHub Oauth app. 
* The change involves changing up the naming of the existing secrets, to comply with the secret-manager naming convention for Entra ID Applications.

Both the dnceng/internal and devdiv variable groups have been updated to also contain the new secrets. Once we have flowed this change back to arcade, we can look into deleting the old secrets from the key vault.

### CODE REVIEW

**Comment by riarenas** [comment]
I will run some validation publishing builds for this change before merging.

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2303029&view=results is a publishing build using my branch's YAML.

**Review by mmitche — APPROVED** [review]
Have you verified that the secrets exist in the AzDO variable group?

**Comment by riarenas** [comment]
> Have you verified that the secrets exist in the AzDO variable group?

I added them to the `publish-build-assets` variable groups in [dnceng](https://dnceng.visualstudio.com/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=20&path=Publish-Build-Assets) and [devdiv](https://devdiv.visualstudio.com/DevDiv/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=149&path=Publish-Build-Assets). That was the only place I saw where we use the old names.

**Comment by riarenas** [comment]
@mmitche I can wait until after GA to merge this. No rush.

**Comment by mmitche** [comment]
Yeah let's wait till GA for this. FYI there may be a couple other places (dotnet-release?) that reference the existing secret names.

**Comment by riarenas** [comment]
> Yeah let's wait till GA for this. FYI there may be a couple other places (dotnet-release?) that reference the existing secret names.

Ooh, good call. I only checked GitHub. Let me run an internal search

**Comment by riarenas** [comment]
Ugh. There are quite a few repos that have this in templates not controlled by Arcade. Apart from the release repo, most of them look like they shouldn't be doing that in the first place and copied the template from Arcade. 

Huge sigh, but I think I don't really care too much if they get broken once the current secrets are removed from the variable group.

**Comment by mmitche** [comment]
My bet is that most of these are not active. I would update dotnet-release and let the other secrets expire. Document and scream test.

**Review by AlitzelMendez — CHANGES_REQUESTED** [review]
Blocking on @riarenas' request so he doesn't merge things early

**Comment by epananth** [comment]
@riarenas can we merge this PR? :)

**Comment by riarenas** [comment]
I think it's good to merge, but I would accompany with a PR to the release repo, as mentioned in the discussion here.

**Comment by epananth** [comment]
okay will do :) thanks @riarenas

**Comment by epananth** [comment]
dotnet-release pr -> https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37660

**Review by epananth — APPROVED** [review]

**Review by AlitzelMendez — APPROVED** [review]

**Pull request merged**
