### PR TITLE
Move to preview9 SDK

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by Pilchie** [comment]
@rrelyea - do you know what this is?  Appears to be another breaking change in NuGet.

**Comment by ericstj** [comment]
See my commit details around what caused this. 

>Suppress dependencies when building SDKs / BuildTasks

> NuGet added validation to enforce parallel assets between
lib/ref/dependencies to catch a place where folks don't declare
dependencies that match their assets, or vice-versa.

> This validation was flagging all Arcade projects, which were creating
empty dependency groups and no lib nor ref assets.
Empty dependency groups are intentional for build tasks and SDKs since
they shouldn't contribute to the project's dependencies.  No Lib/Ref
is also intentional since these packages only provide build assets.

> It's technically more correct to omit the empty dependency groups,
so this is what I've done.  NuGet could special case the check here
to avoid flagging packages which only define empty dependency
groups.

This was caused by https://github.com/NuGet/NuGet.Client/pull/2936, /cc @JarahSi @nkolev92

**Comment by nkolev92** [comment]
@zivkan was looking into this issue. 

It's a validation rule added that gets elevated to an error. 

Is the package being built marked with some special package type? 
Anything that distinguishes it from regular library packages so that NuGet would know when to skip this specific validation?

**Comment by zivkan** [comment]
@nkolev92 I only looked at one of the projects, but that one does [specify it's own package type](https://github.com/dotnet/arcade/blob/0f5cfb20a355c27bc84cedd049c946b44a7fc1da/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L15). We can use that to skip this validation.

**Comment by ericstj** [comment]
This got back the pack error, was hitting a test issue.  It looked potentially transient so I retried.  Might warrant a closer look by @mmitche .

**Comment by ericstj** [comment]
> We can use that to skip this validation

Not foolproof, in fact SDK packages should have no dependencies.  These packages have lib nor ref: Why are you even applying this rule?  Additionally, the dependencies are empty, why apply the rule?  Those two are better conditions than package type.

**Comment by zivkan** [comment]
>  SDK packages should have no dependencies

We can add that validation, if you like.

> Why are you even applying this rule?

The rule is designed to improve the quality of dependency packages. It was an oversight to apply this rule to other package types. [The spec for the rule](https://github.com/NuGet/Engineering/blob/master/Client.Specs/PackageValidation/DependenciesInNuspecMatchLibRefFolder.md) lists some motivations about why the rule works as is (when our intern did the work, I thought we created the specs in a public repo, but now I notice it's private. we should move them). Both signals you listed, no lib/ref files or no dependencies, have the possibility of issues in dependency package types, so I don't think it's appropriate to skip the validation based solely on those conditions.

**Comment by ericstj** [comment]
Probably best to move this discussion to an issue in NuGet repo.  FWIW the basic scenario that hits this is any project that sets "IncludeBuildOutputInPackage =false" since that package is likely to customize its content but cannot customize the dependencies (since the PackTask doesn't really provide great hooks for specifying dependencies).  I think there are likely missing features in PackTask around turning off package dependencies and providing them directly as items similar to files.

**Comment by nkolev92** [comment]
> I think there are likely missing features in PackTask around turning off package dependencies and providing them directly as items similar to files.

Yeah I have an issue for that, but it's not been prioritized yet. https://github.com/NuGet/Home/issues/8133

**Comment by mmitche** [comment]
Now that we've branched arcade, I'm merging this.

**Pull request merged**
