### PR TITLE
Updating WPF status for Yaml Stages Publishing

### PR DESCRIPTION
**Pull request by vatsan-madhavan**

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
@riarenas, @markwilkie this is a doc-only update. would one of you please override checks and merge this?

**Comment by markwilkie** [comment]
done

**Comment by markwilkie** [comment]
@vatsan-madhavan - once the pool gets sorted for the build, are you unblocked for publishing?

**Comment by vatsan-madhavan** [comment]
> once the pool gets sorted for the build, are you unblocked for publishing?

looks that way, unless i encounter some other problem... :)

**Comment by vatsan-madhavan** [comment]
I have a working prototype now https://dev.azure.com/dnceng/internal/_build/results?buildId=296230. It doesn't seem to publish any packages though to the [windowsdesktop](
https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json) feed though. Is this because this is on the validation channel? I'm looking for Microsoft.DotNet.Wpf.GitHub.4.8.0-preview9.19405.11.nupkg on the feed... 

/cc @riarenas, @JohnTortugo

**Comment by JohnTortugo** [comment]
@vatsan-madhavan no publishing is happening because that branch that you're using doesn't have a default channel associated in Maestro. There are some [instructions how to point your test branch to the validation channel here](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md#validating-the-changes).

**Comment by vatsan-madhavan** [comment]
darc get-default-channels shows this. is this not enough?  

https://dev.azure.com/dnceng/internal/_git/dotnet-wpf @ refs/heads/dev/vatsan/yamlstages -> .NET Tools - Validation

**Comment by JohnTortugo** [comment]
Looking at the build log I see that it didn't find that mapping. Usually, this happens because of one of these: 1) the channel mapping was configured after the build ran; 2) the channel mapping wasn't configured ever (which is not your case); 3) the same branch name exist in ADO and GitHub repos, in which case the mapping is looked up based on GitHub repository URL.

I think you might have hit case 3 above so I just added another configuration for your branch + channel 9 but using GitHub repository URL.

**Pull request merged**
