### PR TITLE
Update SDK to latest Tasks.Feed

### PR DESCRIPTION
**Pull request by JohnTortugo**
Just to be sure we're using the latest changes.

### CODE REVIEW

**Comment by riarenas** [comment]
19454.15 is busted, so this needs an update to a newer version

**Comment by JohnTortugo** [comment]
The Tasks.Feed too?

**Comment by riarenas** [comment]
Nope, but I'd rather not update to a version that comes from a broken SDK

**Comment by JohnTortugo** [comment]
Updated to latest version. Published the packages here: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=17082

**Pull request merged**
