### PR TITLE
Import WebTools SignCheck tool into Arcade

### PR DESCRIPTION
**Pull request by JohnTortugo**
This PR is for copying over the sources of the [SignCheck ](https://devdiv.visualstudio.com/DevDiv/_git/WebTools-InternalTools?path=%2FSignCheck&version=GBmaster)tool from WebTools repository into Arcade.

**Roadmap for this PR:**

- [x] **No functional changes intended in this PR.**
- [x] Copy sources (+commit history) from Webtools repository
- [x] Adjust license headers
- [x] Make Arcade build SignCheck solution -- SignCheck target platform is x86
- [x] Make it packable
- [x] Rename to Arcade format
- [x] Fix versioning - Remove Nerdbank.GitVersioning
- [x] Add license files to the package

### CODE REVIEW

**Comment by JohnTortugo** [comment]
Before merging this I'm checking with @joeloff about the correct use of the `ResxWorkaround.props` file.

**Comment by joeloff** [comment]
The resxworkaround.props deals with some flaky behavior in the VS IDE. When you edit resources, the IDE doesn't always pick them up and the only other work-around is to sometimes close and reopen the solution. It only happens in SDK based .csproj files AFAIK

**Comment by anurse** [comment]
Looks like this package is on the arcade feed but `Microsoft.DotNet.SignCheckLibrary` (which it depends on) is not. Is this ready to try out? I'm hoping to add support for the SignCheck tool in a legacy repo we ship and getting it from a public feed is much easier than from devdiv.visualstudio.com ;).

**Comment by JohnTortugo** [comment]
AFAIU this is ready to use. We basically ported it from its [original repo](https://devdiv.visualstudio.com/DevDiv/_git/WebTools-InternalTools?path=%2FSignCheck&version=GBmaster) without any functionality change. @markwilkie / @joeloff

**Comment by joeloff** [comment]
@anurse Does the SignCheck package list it as a dependency. Since it's a tools package, it should just contain all the required files. It should be packaging up a copy of the Microsoft.DotNet.SignCheckLibrary. I wonder if that package dependency is artificial because the old internal project was an SDK project with a project reference and it might be interpreting that reference to add a package dependency as well.

**Comment by anurse** [comment]
I'm definitely getting a NuGet restore issue:

```
Attempting to gather dependency information for package 'Microsoft.DotNet.SignCheck.1.0.0-beta.18531.6' with respect to project './artifacts/tools', targeting 'Any,Version=v0.0'
Gathering dependency information took 870.21 ms
Attempting to resolve dependencies for package 'Microsoft.DotNet.SignCheck.1.0.0-beta.18531.6' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Microsoft.DotNet.SignCheckLibrary'. Source(s) used: 'nuget.org', 'Azure SignalR Dev'.
```

So I think it is listed as a dependency, despite being a tool package.

**Pull request merged**
