### PR TITLE
Allow suppression of all targets

### PR DESCRIPTION
**Pull request by mmitche**
Allow for use of ExcludeFromBuild to exclude a project from building, similar to ExcludeFromSourceBuild.

### CODE REVIEW

**Comment by mmitche** [comment]
This is motivated by aspnet. The build overall is extremely expensive in many ways and much of the time in the product build is spent building the tests. We build the tests in other legs of the build, and so don't need to build them twice.

**Comment by dougbu** [comment]
Guess we'd add a `$(ExcludeFromBuild)` setting near https://github.com/dotnet/aspnetcore/blob/master/Directory.Build.targets#L6-L7 with a condition something like
``` msbuild
<ExcludeFromBuild
  Condition="'$(ExcludeFromBuild)' == '' and '$(CI)' != '' and '$(isTestingJob)' != 'true' and
    ('$(IsBenchmarkProject)' == 'true' or '$(IsUnitTestProject )' == 'true' or
     '$(IsTestAssetProject)' == 'true' or '$(IsSampleProject)' == 'true')">true</ExcludeFromBuild>
```

Other than perhaps needing to add `$(isTestingJob)` into the environment (it's a pipeline parameter) or to provide a simple way to skip building tests, this looks good to me.

Am I understanding the intent correctly?

**Comment by mmitche** [comment]
> Guess we'd add a `$(ExcludeFromBuild)` setting near https://github.com/dotnet/aspnetcore/blob/master/Directory.Build.targets#L6-L7 with a condition something like
> 
> ```
> <ExcludeFromBuild
>   Condition="'$(ExcludeFromBuild)' == '' and '$(CI)' != '' and '$(isTestingJob)' != 'true' and
>     ('$(IsBenchmarkProject)' == 'true' or '$(IsUnitTestProject )' == 'true' or
>      '$(IsTestAssetProject)' == 'true' or '$(IsSampleProject)' == 'true')">true</ExcludeFromBuild>
> ```
> 
> Other than perhaps needing to add `$(isTestingJob)` into the environment (it's a pipeline parameter) or to provide a simple way to skip building tests, this looks good to me.
> 
> Am I understanding the intent correctly?

Yep exactly.

**Pull request merged**
