### PR TITLE
Fixes for darc-init tool 

### PR DESCRIPTION
**Pull request by MattGal**
Moving the arcade build to a Server SKU (different powershell behaviors) exposed a problem, which I was very fortunate to have a living legend sitting nearby to help out with.

https://github.com/dotnet/core-eng/issues/8163

### CODE REVIEW

**Comment by chcosta** [comment]
Just to be safe, we should schedule a private internal build.  I'll schedule one and paste the link here.

**Comment by chcosta** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=545050&view=results

**Comment by chcosta** [comment]
Updated build - https://dev.azure.com/dnceng/internal/_build/results?buildId=545056&view=results

**Comment by riarenas** [comment]
Interesting. Should we also queue a build from a repo using the client sku builds with these changes to the scripts to make sure nothing regresses there? Or overkill?

**Comment by MattGal** [comment]
> Interesting. Should we also queue a build from a repo using the client sku builds with these changes to the scripts to make sure nothing regresses there? Or overkill?

Probably overkill.  This has been happily silently failing on Client SKU builds for some time.

**Comment by MattGal** [comment]
Nice, this worked in https://dev.azure.com/dnceng/internal/_build/results?buildId=545056&view=logs&j=1217766f-bb40-52a2-b66d-f8ecc3a6dc68&t=3fc062db-97f0-5cb1-4219-c99d19e79124!  Merging and closing.

**Pull request merged**
