### PR TITLE
Update SourceIndexPackageVersion

### PR DESCRIPTION
**Pull request by wtgodbe**
Dupe of https://github.com/dotnet/aspnetcore/pull/51715. Related: https://github.com/dotnet/source-indexer/pull/120

### CODE REVIEW

**Comment by wtgodbe** [comment]
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

In the SourceIndex job. @garath @riarenas any ideas?

**Comment by riarenas** [comment]
No ideas, as I'm not familiar with the source index code at all. 

Can you remind me what is driving the need for a new binlog version, and therefore this chain of changes?

**Comment by wtgodbe** [comment]
MSBuild.StructuredLogViewer updates sometimes break source-index:

> Unhandled exception. System.NotSupportedException: Unsupported log file format. Latest supported version is 16, the log file has version 17.

We've been seeing this in every Source-Index job in aspnetcore for the past few days, which motivated https://github.com/dotnet/source-indexer/pull/120. For now we've disabled source-index in aspnetcore

**Comment by riarenas** [comment]
Do you know what caused the aspnetcore build to try to use newer binlog versions?

**Comment by wtgodbe** [comment]
> Do you know what caused the aspnetcore build to try to use newer binlog versions?

I think msbuild got updated to generate the new binlog versions, so the build machines we run on must have gotten updated to use that new version. We haven't changed anything with regards to binlog generation

**Comment by wtgodbe** [comment]
@dotnet/dnceng who else might know about source-index? We've had to disable it in aspnetcore because of this error

**Comment by markwilkie** [comment]
Ownership of this was transferred to @SteveMCarroll a bit ago.  I'm not sure who he has to work on it right now, but off course, we're happy to assist whoever that is where we can.

cc/ @garath @shawnro

**Comment by ViktorHofer** [comment]
> I think msbuild got updated to generate the new binlog versions, so the build machines we run on must have gotten updated to use that new version. We haven't changed anything with regards to binlog generation

Correct. We need to keep the StructuredLogViewer nuget package reference up-to-date so that it can handle newer binlog versions. MSBuild from time to time revs the binlog version when they add new stuff to the format.

**Comment by ViktorHofer** [comment]
This is likely required before updating Arcade to a .NET 9 SDK. @wtgodbe what's the status on this? Is there anything left?

**Comment by mmitche** [comment]
Loading 15.1 MSBuild...odd...okay

**Comment by ViktorHofer** [comment]
Should we also update the .NET SDK to 8? https://github.com/dotnet/arcade/blob/1f6c5acef9bdf9d4bf1eded044eeec0d7d19560d/eng/common/templates/job/source-index-stage1.yml#L42-L48

**Comment by ViktorHofer** [comment]
Yeah, 17.5 of msbuild packages should require that version of msbuild. So we probably need to update the SDK.

**Comment by ViktorHofer** [comment]
I added a rollforward switch to the two global tools for now but we ideally should just make them target .NET 8 instead.

**Comment by ViktorHofer** [comment]
@mmitche now I'm unsure if the `1es-windows-2022-open` images already have VS 17.8 installed. Could we use a different pool, i.e. the VS preview pool?

**Comment by mmitche** [comment]
Our stock 2022 pool has 17.8. Let me switch to that.

**Comment by ViktorHofer** [comment]
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Hmm I'm out of ideas unless trying to repro this locally. cc @rainersigwald in case you understand why the msbuild assembly can't be found / loaded.

**Comment by mmitche** [comment]
> > Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> 
> Hmm I'm out of ideas unless trying to repro this locally. cc @rainersigwald in case you understand why the msbuild assembly isn't found / loaded.

And why 15.1.0.0?...that such an old number

**Comment by rainersigwald** [comment]
> > Hmm I'm out of ideas unless trying to repro this locally. cc @rainersigwald in case you understand why the msbuild assembly isn't found / loaded.
> 
> And why 15.1.0.0?...that such an old number

that's our current version, frozen in amber at the point we went open-source :-/

**Comment by mmitche** [comment]
> > > Hmm I'm out of ideas unless trying to repro this locally. cc @rainersigwald in case you understand why the msbuild assembly isn't found / loaded.
> > 
> > 
> > And why 15.1.0.0?...that such an old number
> 
> that's our current version, frozen in amber at the point we went open-source :-/

image

**Comment by rainersigwald** [comment]
I don't know what's going on here, though. I'll plan to take a look tomorrow morning.

**Comment by akoeplinger** [comment]
I root caused the failure and will have a PR shortly for dotnet/source-indexer

**Comment by akoeplinger** [comment]
https://github.com/dotnet/source-indexer/pull/123

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@akoeplinger thank you so much!

**Pull request merged**
