### PR TITLE
Remove attachments because we overflowed Azure DevOps

### PR DESCRIPTION
**Pull request by ChadNedzlek**
Related to https://github.com/dotnet/arcade/issues/7319

### CODE REVIEW

**Review by alexperovich — APPROVED** [review]

**Review by MattGal — APPROVED** [review]

**Comment by missymessa** [comment]
Since this is something that has the potential to break folks, could we make sure to communicate this change to Arcade users?

**Comment by ChadNedzlek** [comment]
I'll rely to the mail to partners Matt sent.

**Comment by MattGal** [comment]
@ChadNedzlek do you think we should port this to the release branches?  I'm not sure how much it matters since the volume is drastically lower there, but the port is cheap.

**Comment by ChadNedzlek** [comment]
I'd be fine with not.  Their volume is pretty low, and the problem seems to have been mitigated for now.

**Pull request merged**
