### PR TITLE
Pass continueOnError down into telemetry templates

### PR DESCRIPTION
**Pull request by AdamYoblick**

### CODE REVIEW

**Comment by AdamYoblick** [comment]
Whoh, no build checks for these PR's?

**Comment by chcosta** [comment]
Why do we want to ignore telemetry failures?

**Comment by AdamYoblick** [comment]
We don't want to ignore them by default, but the caller should be able to decide if they want to continue if telemetry fails.

We had a sporadic telemetry failure fail our build, and something like telemetry, which is absolutely not critical, should not fail our build. :)

**Comment by AdamYoblick** [comment]
And because all the other common templates support this behavior? I think giving the customer the choice is always better than forcing a failure

**Comment by chcosta** [comment]
We need to invest in ensuring sporadic telemetry failures don't happen

**Comment by chcosta** [comment]
How often is this causing failures? i'm only aware of one instance in the past 6 months

**Comment by AdamYoblick** [comment]
I mean, does it matter? I'd like our build to be as stable as possible.

I'm saying that, as a customer, we'd like the option for failed telemetry to not fail our build, similar to every other call made in eng\common\templates\job\job.yml. The default behavior is not changed, it's an opt-in.

**Comment by chcosta** [comment]
@markwilkie thoughts?

**Comment by AdamYoblick** [comment]
(not to mention the work is already done in the PR) 😄

**Comment by AdamYoblick** [comment]
Hi @markwilkie 

Nobody is saying telemetry doesn't matter. What I'm saying is telemetry doesn't matter enough to me to fail my build. It's not a critical step. Customers should have the option for their build to continue if non-essential steps fail. 

Many of those non-essential steps are in the job.yml, and **every single other existing step already allows customers to continue on error** (Microbuild signing, Microbuild cleanup, publishing build artifacts to VSTS, publishing test results to VSTS, gathering asset manifests, publishing to BAR).

This PR doesn't change default behavior in any way. It just gives customers more options and makes telemetry error handling consistent with the rest of the tasks in the job.yml.

**Comment by AdamYoblick** [comment]
And FYI another telemetry failure just failed a PR build we had:

https://dev.azure.com/dnceng/public/_build/results?buildId=77964

This is the kind of things I want to avoid :)

**Comment by AdamYoblick** [comment]
And another telemetry failure that failed our build:

https://dev.azure.com/dnceng/internal/_build/results?buildId=79531&_a=summary

**Comment by markwilkie** [comment]
Approved for merge.

Yup - due to the telemetry being flaky, you're correct @AdamYoblick that this functionality should be added.  Thanks a bunch for doing the PR and being patient in getting this PR through.

A couple of other notes:  1) remember that Arcade won't flow until after we ship P2 (very soon now) and 2) we'll want to circle back around to make sure that folks are sending telemetry as a high priority.  However, looks like we need to get to the bottom of the flakiness first.  I'll file an issue on that.

**Comment by AdamYoblick** [comment]
No problem, thanks Mark. Appreciate it. :)

**Comment by jonfortescue** [comment]
I believe @chcosta has introduced a fix for this when we switch to AzDO tasks to do telemetry -- is that correct, Chris? If so I think we can close this.

**Comment by chcosta** [comment]
Yup, this should be fixed now.  Let me know if it's not @AdamYoblick.  Thanks @jonfortescue

**Pull request closed without merging**
