### PR TITLE
Add more testing for resx generation and fix for syntax error in generated C#

### PR DESCRIPTION
**Pull request by natemcmaster**
Follow up to #2657 

Fixes for missing closing parenthesis when using the named arguments formatter.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I believe this or the previous change broke the build in corefx: https://github.com/dotnet/corefx/pull/37340#issuecomment-489317884

cc @ercistj

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
@natemcmaster this broke CoreFX, can you please have a look ASAP.

**Comment by natemcmaster** [comment]
It was the previous change, not this one. I will comment on https://github.com/dotnet/corefx/pull/37340 with a recommendation for a fix.

**Pull request merged**
