### PR TITLE
Include PlatformName in the SymStore output directory

### PR DESCRIPTION
**Pull request by tmat**
Enables publishing converted PDBs for projects that target multiple platforms (x86/x64).

### CODE REVIEW

**Comment by tmat** [comment]
> We'll need to port this to the 3.x branch if we want to MSBuild to use it

You'd need to port all the other changes made to this file. 

> they only consume Arcade from the servicing branch

Why is that?

**Comment by JohnTortugo** [comment]
> > We'll need to port this to the 3.x branch if we want to MSBuild to use it
> 
> You'd need to port all the other changes made to this file.
> 

@tmat it's been a lot of changes in the version of that file in master. Do you think just porting the change you did would be sufficient? I mean, just appending the Platform. I.e.,: https://github.com/dotnet/arcade/blob/SymStorePatch3x/src/Microsoft.DotNet.Arcade.Sdk/tools/SymStore.targets#L28

> > they only consume Arcade from the servicing branch
> 
> Why is that?

TBH I don't have a clue. @rainersigwald do you know why MSBuild master branch isn't taking updates from Arcade Latest? That is, MSBuild is still ingesting Arcade from the servicing 3.x branch in it's master branch.

**Comment by tmat** [comment]
> Do you think just porting the change you did would be sufficient?

Maybe, maybe not. I don't see why we would want to create another version of this logic.

**Comment by rainersigwald** [comment]
MSBuild is still shipping to 3.x channels and VS. My understanding of the support lifecycle of Arcade was that we should be on 3.x Arcade for those purposes. Has that changed? Does the Arcade team support building 3.x products using 5.x Arcade? How does the Arcade lifecycle for the in-early-development 5.x stuff work with respect to M2/QB stabilization requirements for VS releases?

**Comment by markwilkie** [comment]
@rainersigwald - could you remind me the plan/intent for when msbuild should switch to arcade 5.0?  I do remember us talking about this, but don't recall the outcome.

**Comment by rainersigwald** [comment]
@markwilkie My understanding was that we'd switch when we started development on MSBuild X.Y (16.8? 16.9? 17.0?) that would be shipped as part of .NET SDK 5.0.100. Which would be probably late summer/early fall.

**Comment by markwilkie** [comment]
Yea.....makes sense.

**Pull request merged**
