### PR TITLE
Update zlib package on illumos

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Updates the zlib package we're ingesting on illumos. Contributes to https://github.com/dotnet/runtime/issues/69652.

I'm also about to send a separate PR to the _runtime_ repo which updates the source files we have checked in. Between the two PRs, I believe the work item will be complete.

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by am11** [comment]
This version is unfortunately not available on pkgsrc.joyent.com or the skylime mirror: https://pkgsrc.smartos.skylime.net/packages/SmartOS/2020Q1/x86_64/All/zlib-1.2.12.tgz (v1.2.11 exist)

@jperkin, I noticed that zlib 1.2.12 was updated in the manifest https://github.com/TritonDataCenter/pkgsrc/blob/trunk/devel/zlib/Makefile, do you know when the package will be available to consumption?

**Comment by jperkin** [comment]
2020Q1 is not an LTS release and was EOL over 2 years ago.  1.2.12 is available in the trunk repository.

**Comment by am11** [comment]
Thank you! I missed the quarter reference.

@GrabYourPitchforks, updating the pinned `2020Q1` reference to floating `trunk` will break other packages. I will modify the script separately such that it pulls the manifest, and find the latest version of each package that we need.

**Comment by GrabYourPitchforks** [comment]
@am11 No worries. Thank you for looking at this. :)

I'll just hold tight and wait for your changes to come through first. If it would instead be easier for you to handle everything (including this) as a single separate PR, let me know and I can close this one.

**Comment by am11** [comment]
I have opened https://github.com/dotnet/arcade/pull/10215 so we use `trunk` repository.

**Comment by GrabYourPitchforks** [comment]
Closing in favor of https://github.com/dotnet/arcade/pull/10215.

**Pull request closed without merging**
