### PR TITLE
Set flag also for cross-targeting builds

### PR DESCRIPTION
**Pull request by DoCode**
(#2677)

### CODE REVIEW

**Comment by DoCode** [comment]
@ViktorHofer PTAL

**Comment by ViktorHofer** [comment]
I assume you tested that this fixes the official build failures? Thanks a lot!

**Comment by tmat** [comment]
This should address the issue https://github.com/dotnet/arcade/pull/2683. Please revert this change once the other PR is merged.

**Comment by DoCode** [comment]
@tmat ok, yes. That's the correct solution.

**Pull request merged**
