### PR TITLE
Revert "Normalize RepoRoot to include trailing slash (#7498)"

### PR DESCRIPTION
**Pull request by riarenas**
This reverts commit a4191734058802ac065b0f3270b76d2f0f3a60cd.

fixes https://github.com/dotnet/arcade/issues/7506

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Review by epananth — APPROVED** [review]

**Comment by ViktorHofer** [comment]
I have the fix ready, if you give me another few minutes I can submit the PR.

**Review by mmitche — APPROVED** [review]

**Comment by riarenas** [comment]
@ViktorHofer sounds good. we can hold on on the revert:

@msftbot do not merge unless @ViktorHofer approves.

**Comment by riarenas** [comment]
I'm not sure the auto merge bot understands it shouldn't merge this anymore, so closing for now.

**Comment by ViktorHofer** [comment]
PR is up: https://github.com/dotnet/arcade/pull/7508

**Pull request closed without merging**
