### PR TITLE
Publishing: Support for multiple build manifests

### PR DESCRIPTION
**Pull request by JohnTortugo**
With this change the publishing release pipeline will be able to work with eventual multiple build manifests.

### CODE REVIEW

**Comment by jcagme** [comment]
So, a single build leg will produce different manifests?

**Comment by jcagme** [comment]
> This is the case today, in cases where you need to do more than one push (packages and blobs)

Hmmm packages and blobs end up in the same manifest IIRC (unless something changed in the past three weeks). When we actually push to BAR we merge packages and blobs so we don't push duplicated items

**Comment by mmitche** [comment]
@jcagme From what i could tell, if you have two separate push operations (flat container and non flat container) the first manifest will be overwritten

**Comment by JohnTortugo** [comment]
The way I thought the publishing release pipeline, it would operate based on build-manifest files. The goal of this PR is just to support the default release pipeline to process more than one build-manifest file - be it from different legs or not (e.g., [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=77758)). AFAIU the merge of different manifests happen on the [BAR publishing task](https://github.com/dotnet/arcade-services/blob/b7c74cef8c82fa1e9d9a815ea131d636deadefe3/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs#L66) just to communicate to the Maestro API - it doesn't create a consolidated manifest after the merge. 

May be the release pipeline should [eventually?] fetch the assets from Maestro/BAR instead of the build xml?

**Comment by JohnTortugo** [comment]
Closing this one in favor of: https://github.com/dotnet/arcade/pull/1884

**Pull request closed without merging**
