### PR TITLE
Remove legacy source-build switches

### PR DESCRIPTION
**Pull request by mmitche**
### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

### CODE REVIEW

**Comment by mmitche** [comment]
https://github.com/dotnet/source-build/issues/4182

**Review by ViktorHofer — APPROVED** [review]
Reviewed line by line. LGTM

**Comment by MichaelSimons** [comment]
The scope of https://github.com/dotnet/source-build/issues/4182 is not clear.  What is tracking the removal of `ExcludeFromSourceBuild`?  I don't see any other issue in https://github.com/dotnet/source-build/issues/2975 that would include this besides https://github.com/dotnet/source-build/issues/4182.  I am asking if https://github.com/dotnet/source-build/issues/4182 should remain open until this is done?

**Comment by mmitche** [comment]
I still see a couple remaining usages so holding off on merging this.

**Review by ViktorHofer — APPROVED** [review]
I reviewed all the remaining places in the VMR and everything's now updated. We are still waiting on some codeflow changes to happen but that shouldn't block us from merging this PR in.

**Pull request merged**
