### PR TITLE
Bump symbol uploader version

### PR DESCRIPTION
**Pull request by JohnTortugo**
Update version of symbol uploader.

### CODE REVIEW

**Comment by mikem8361** [comment]
You don't need to update arcade again. The version I just built is exactly the same as before.

**Comment by JohnTortugo** [comment]
> You don't need to update arcade again. The version I just built is exactly the same as before.

You mean the content?

**Comment by mikem8361** [comment]
Yes. There are not any code changes.  The binaries are different because they were rebuilt. I just did the build to update the package version.

**Comment by JohnTortugo** [comment]
> Yes. There are not any code changes. The binaries are different because they were rebuilt. I just did the build to update the package version.

Oks. Thanks for letting me know.

**Pull request closed without merging**
