### PR TITLE
Remove option to clone inner source during source-build

### PR DESCRIPTION
**Pull request by MichaelSimons**
Related to https://github.com/dotnet/source-build/issues/4117

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
Unfortunately this is a breaking change as the PrepareInnerSourceBuildRepoRoot target is referenced in a few repos: https://github.com/search?q=repo%3Adotnet%2Fdotnet%20PrepareInnerSourceBuildRepoRoot&type=code

I would rename this back to the old target name. `CopyInnerSourceBuildRepoRoot` and `CloneInnerSourceBuildRepoRoot` aren't used anywhere outside and can be safely removed.

**Comment by MichaelSimons** [comment]
> Unfortunately this is a breaking change as the PrepareInnerSourceBuildRepoRoot target is referenced in a few repos: https://github.com/search?q=repo%3Adotnet%2Fdotnet%20PrepareInnerSourceBuildRepoRoot&type=code
> 
> I would rename this back to the old target name. `CopyInnerSourceBuildRepoRoot` and `CloneInnerSourceBuildRepoRoot` aren't used anywhere outside and can be safely removed.

Thanks for the catch.  That was a silly oversite on my part.  I pushed an update.

**Comment by mmitche** [comment]
SBE isn't dependent on inner-clone behavior, is it?

**Comment by NikolaMilosavljevic** [comment]
> SBE isn't dependent on inner-clone behavior, is it?

We are using inner-clone for SBE, in VMR build, to avoid file mutations.

**Comment by NikolaMilosavljevic** [comment]
> > SBE isn't dependent on inner-clone behavior, is it?
> 
> We are using inner-clone (clone or copy) for SBE, in VMR build, to avoid file mutations.

**Comment by mmitche** [comment]
Cool, I see how SBE is using a copy right now.

**Review by mmitche — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
