### PR TITLE
move default location of rootfs to artifacts/rootfs instead of eng/common/cross

### PR DESCRIPTION
**Pull request by wfurt**
This is follow up on https://github.com/dotnet/corefx/pull/37678.
originally, build-rootfs lived in cross at arch repo and by default rootfs was created where script lives. After moving to Arcade, it makes more sense to follow Arcade standards and create everything under artifacts.
That makes cleaner separation between code and produced binaries. 

One can still crate rootfs elsewhere via passed argument or environmental variable.

### CODE REVIEW

**Comment by tmat** [comment]
What does `rootfs` mean?

**Comment by safern** [comment]
I think it is root file system. It is used in Unix to change the root file system path via an environment variable for commands executed when the given env variable is set.

**Comment by wfurt** [comment]
we created directory named rootf. In essence that contains clone of root filesystem with tools needed to build given architecture. In current incarnation it has the usual bin, etc, lib, and usr directories.

**Comment by tmat** [comment]
I see. In that case I think it would be better to move this directory under `.tools\rootfs`.

**Comment by janvorli** [comment]
I would also prefer a location that's not in artifacts. The rootfs is not a result of a build and it is nice to be able to delete the whole artifacts folder to get rid of the built stuff and still preserve the rootfs.

**Comment by tmat** [comment]
That's exactly why `.tools` is different from `artifacts` :)

**Comment by wfurt** [comment]
updated. I like .tools since it is already in .gitignore. 
I primarily though eng/common is not right and I wanted to update that before making final changes in corefx.

**Pull request merged**
