### PR TITLE
Open xml files with utf-8 encoding

### PR DESCRIPTION
**Pull request by adiaaida**

### CODE REVIEW

**Comment by mmitche** [comment]
The files are always encoded with utf8?

**Comment by adiaaida** [comment]
As far as I have been able to tell, yes.

**Comment by adiaaida** [comment]
I think that should go into a different issue. I'd like to be able to fix the thing that is actually broken. Since the file event thing is new functionality, I think it should be its own issue that we address separately.

**Comment by adiaaida** [comment]
I opened #4359 to track the file event.

**Pull request merged**
