### PR TITLE
Revert changes breaking build on FreeBSD

### PR DESCRIPTION
**Pull request by josteink**
This PR reverts changes introduced in https://github.com/dotnet/runtime/pull/58314 which breaks the .NET build on FreeBSD, and does so in a way to try to avoid regressions being reintroduced later on when new packages are updated.

CC: @jkotas @Thefrank

### CODE REVIEW

**Review by jasonpugsley — APPROVED** [review]
LGTM. Thanks for this.

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by Thefrank** [comment]
Thanks for getting this in!

**Comment by josteink** [comment]
I’ll create another PR for runtime directly too, just so we won’t have to wait for another package update to restore FreeBSD buildability 🙂

**Pull request merged**
