### PR TITLE
Specify LastExit scope

### PR DESCRIPTION
**Pull request by garath**
Specify global scope in prepping LastExit to avoid shadowing.

I confirmed the scope-change behavior work as expected locally, and verified that this change did not cause any SDL failures in SDK, runtime or aspnetcore repositories.

### CODE REVIEW

**Comment by dagood** [comment]
There are a few more instances of this pattern:

https://github.com/dotnet/arcade/blob/be9124cd49ec34ae7c75a32d74f1c2afb8282813/eng/common/sdl/init-sdl.ps1#L13

https://github.com/dotnet/arcade/blob/be9124cd49ec34ae7c75a32d74f1c2afb8282813/eng/common/sdl/execute-all-sdl-tools.ps1#L35

https://github.com/dotnet/arcade/blob/main/Documentation/Policy/PowershellBestPractices.md#L104

**Review by jonfortescue — APPROVED** [review]
I'd look at the stuff Davis mentioned but otherwise this seems good.

**Comment by garath** [comment]
> There are a few more instances of this pattern

Good catch, thank you.

**Review by dagood — APPROVED** [review]
LGTM. I think it'd be good to update this too, for the future: https://github.com/dotnet/arcade/blob/main/Documentation/Policy/PowershellBestPractices.md

**Pull request merged**
