### PR TITLE
Update dotnet SDK to 3.0.100 stable

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by mmitche** [comment]
We will also want to port this to release/3.x too.

**Comment by ViktorHofer** [comment]
Yeah I'll do that after the CI tells me that the change is safe and is merged.

**Comment by ViktorHofer** [comment]
Don't have much context here, tests are expected to fail but don't. Can somebody please take a look?

cc @alexperovich @chcosta

**Comment by chcosta** [comment]
This looks like https://github.com/dotnet/core-eng/issues/7923#issuecomment-534191370

**Comment by ViktorHofer** [comment]
I'm hitting multiple issues here. Had to rebuild. Branch protection is definitely not my friend here. Seems like Windows machines aren't responding on Helix. The build itself already succeeded and testing also succeeded on 3 of 4 steps. Maybe somebody want to merge this...

**Comment by ViktorHofer** [comment]
I'm not authorized to merge this PR (even though all checks are green and the PR is approved). Can somebody please merge this one?

**Pull request merged**
