### PR TITLE
Update GenerateTrainingInputFiles task:

### PR DESCRIPTION
**Pull request by chsienki**
- Allow a users OptProf.json to specify a filtered list of test cases, where only certain assemblies within in a product generate entries for a given test.
- Update tests to cover new options

### CODE REVIEW

**Comment by tmat** [comment]
Wasn't it possible to specify these in the `assemblies` element?

**Comment by chsienki** [comment]
@tmat it is, but I wanted to go this route for two reasons: 
1) we have 32 dll's involved in IBC collection. It's going to be hard to read what ever way we do it, but this made it slightly easier to understand

2) The assembly option requires us to know what the output path of the dll will be at run time. That means hard coding a lot of info into the roslyn repo that could potentially change external to the repo. Putting a filter under the product means we just have to list the location in the VSIX. We can check that with BuildBoss to ensure that the profiling data never gets out of sync with the VSIX layout.

It's mainly the getting out of sync that lead me to explore doing it this way; given how much time we've wasted to incorrect OptProf, i'd love to know we're making it harder to accidentally break things 6 months down the line.

**Comment by tmat** [comment]
Makes sense. Wondering though if we could include that information in the project file that generates that VSIX. That would remove the need to keep it in sync.

E.g. [here](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj#L26-L30).

```
<ProjectReference Include="..\..\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj">
      <Name>CodeAnalysis</Name>      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup;SatelliteDllsProjectOutputGroup</IncludeOutputGroupsInVSIX>
      <ForceIncludeInVSIX>true</ForceIncludeInVSIX>
      <IbcTrainingScenarios>foo;bar;baz</IbcTrainingScenarios>
    </ProjectReference>
```

Then we would hook up a build task that collects these properties and generates the corresponding json files like we do from OptProj.json.

Perhaps we could do that later, once we get everything working end-to-end.

**Comment by chsienki** [comment]
Hmm, that's a very interesting idea. I agree we probably want to get this working end to end first, then could clean it up as needed.

**Comment by chsienki** [comment]
Ping @tmat can I merge this, or would you rather we go down the alternate route first?

**Comment by tmat** [comment]
Please merge

**Pull request merged**
