### PR TITLE
Enable 'fast' publishing

### PR DESCRIPTION
**Pull request by mmitche**
For repos that do not do any build validation, or who's post-build stages do not depend on non-build stages, the Publish To BAR job can be used to call publishing. Due to the 1ES pool spin-up time, this cuts off another job and hence another 15-20 minutes of official build time.

To opt in, a repo needs to do the following:
- If using jobs.yml, set parameter publishAssetsImmediately to true
- If not using jobs.yml and instead using publish-build-assets.yml, set parameter publishAssetsImmediately to true.
- In post-build.yml, set publishAssetsImmediately to true
- If there are any additional publishing parameters to post-build.yml (artifactsPublishingAdditionalParameters or signingValidationAdditionalParameters), instead send them to jobs.yml or publish-build-assets.yml

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
Working publishing for wpf https://dev.azure.com/dnceng/internal/_build/results?buildId=1643546&view=results

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1654139&view=results

**Comment by mmitche** [comment]
Test, but without wpf doing fast publishing: https://dev.azure.com/dnceng/internal/_build/results?buildId=1654158&view=results

**Comment by mmitche** [comment]
This cuts 10-15 mins off builds.

**Review by riarenas — DISMISSED** [review]
LGTM! good idea to do this. Maybe just add the prerequisites and mechanics to the publishing doc under documentation/corepackages?

**Review by epananth — DISMISSED** [review]

**Comment by mmitche** [comment]
@akoeplinger Used else instead
@riarenas @epananth I've updated the docs with some new info on publishing, including info on the new mode, removing some info on V2, etc. Once this gets checked in and I can enable it in a couple repos, I'll add links to those commits in the onboarding section.

**Review by riarenas — APPROVED** [review]

**Pull request merged**
