### PR TITLE
Fix aka.ms link library's UsingTask task names

### PR DESCRIPTION
**Pull request by dagood**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

---

* See https://github.com/dotnet/arcade/issues/8573

### CODE REVIEW

**Review by adiaaida — APPROVED** [review]
LGTM, thanks for fixing this

**Review by riarenas — APPROVED** [review]
Looks reasonable to me, but I'm not sure about this task. Added @adiaaida in case she knows whether this might break anything (but it seems broken already so I don't think so)

**Comment by adiaaida** [comment]
As far as I am aware, none of our services are using this task, so I think we're ok.

**Comment by dagood** [comment]
FWIW, the task doesn't show up in any of the repos that grep.app has indexed (other than this project itself 🙂): https://grep.app/search?q=CreateAkaMSLink. Same results in dnceng internal repo search. I did this search earlier on to see if I could find an example of this package in use.

**Pull request merged**
