### PR TITLE
Add a method for submitting a job with a joblist

### PR DESCRIPTION
**Pull request by DrewScoggins**
This adds a method for passing a URI to a joblist. This allows you to copy another job easily.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
> The entire JobSender is a helper for constructing a job list and submitting the job
Is it? I was using it because it offers an easy to use wrapper around sending a job to Helix that does not require me to go and track down a bunch of storage URIs and sas keys. This just adds a way to allow the use of a pre-made job list.

If I want to use the New api I now have to track down all of this additional information and can no longer take advantage of the niceties of the fluent API.

**Comment by DrewScoggins** [comment]
> The entire JobSender is a helper for constructing a job list and submitting the job
Is it? I was using it because it offers an easy to use wrapper around sending a job to Helix that does not require me to go and track down a bunch of storage URIs and sas keys. This just adds a way to allow the use of a pre-made job list.

If I want to use the New api I now have to track down all of this additional information and can no longer take advantage of the niceties of the fluent API.

**Comment by alexperovich** [comment]
If you already have a job list the storage keys are useless. The only thing they are used for is uploading the payloads that go in the job list. If you have the job list already then its just a simple api call.

**Comment by DrewScoggins** [comment]
OK, but I don't see why we can't use the fluent API to handle all of the other setup that we need here and just use a previously created job list. I don't really see how using a pre-created  job list and building one using the rest of the API are really that different.

**Comment by alexperovich** [comment]
What do you mean by "all of the other setup"? If you have a pre-packaged job list there isn't any.

**Comment by DrewScoggins** [comment]
All of this

```
apiint.Job.Define()
  //                            .WithSource("pr/test/diskspd")
  //                            .WithType("test/diskspd")
  //                            .WithBuild("12345.10")
  //                            .WithTargetQueue("pr-windows.10.amd64.clientrs3.devex.open-FixArtifactStomping" /* Helix Queue ID Goes Here */)
```

**Comment by alexperovich** [comment]
That would be this:
```csharp
await api.Job.NewAsync(new JobCreationRequest(source, type, build, properties, jobListUri, targetQueue);
```

**Comment by jonfortescue** [comment]
closing for now

**Pull request closed without merging**
