### PR TITLE
Fix TargetChannelConfig.Equals

### PR DESCRIPTION
**Pull request by hoyosjs**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

Fixes https://github.com/dotnet/arcade/issues/6998

### CODE REVIEW

**Comment by hoyosjs** [comment]
Is there a good way to create a test against a channel that doesn't exist/exists but is not configured to publish? I didn't see a test that successfully mocks the inputs to the `PublishArtifactsInManifest*` enough to run Execute.

**Comment by adiaaida** [comment]
Not sure on that last question. Added @epananth, since she has more knowledge about the publishing code/tests.

**Review by adiaaida — APPROVED** [review]

**Comment by epananth** [comment]
I had a error msg before -> https://github.com/dotnet/arcade/blob/03999a52a4333bc2399906cda9138a474bbf77f6/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs#L76, but looks like there are other places I need to consider adding this..

**Comment by epananth** [comment]
All the test related to PublishArtifactsInManifest are here https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed.Tests/PublishArtifactsInManifestTests.cs

**Comment by hoyosjs** [comment]
@epananth the problem is there was an unhandled exception inside . the line you pointed out just validates the input channels are numbers separated by `-`; this happened further down in evaluation, where the constants didn't contain the channel yet.

**Comment by epananth** [comment]
Yep I see that. I was thinking of adding that msg in those parts too. I will create an issue to fix this

**Comment by epananth** [comment]
Issue - https://github.com/dotnet/arcade/issues/7010

**Comment by hoyosjs** [comment]
I tried adding a test, but the MaestroClient object inside `PublishArtifactsInManifestV3.ExecuteAsync` is not mocked. The logic this would need to test is right by it.

**Comment by hoyosjs** [comment]
Tried to add 

```c#
        public void V3PublishingTaskWithChannelNotEnabledForPublish()
        {
            var manifestFullPath = TestInputs.GetFullPath(Path.Combine("Manifests", "SampleV3.xml"));
            var buildEngine = new MockBuildEngine();
            var invalidChannelId = "9999999";
            var task = new PublishArtifactsInManifest()
            {
                BuildEngine = buildEngine,
                TargetChannels = invalidChannelId,
                AzureDevOpsFeedsKey = "test",
                AzureStorageTargetFeedKey = "test",
                InstallersFeedKey = "test",
                ChecksumsFeedKey = "test",
                NugetPath = $"{Path.GetRandomFileName()}.exe",
                BlobAssetsBasePath = "test",
                PackageAssetsBasePath = "test",
                BARBuildId = 4242,
                MaestroApiEndpoint = "https://testEndpoint/",
                BuildAssetRegistryToken = "test"
            };

            // Dependency Injection setup
            var collection = new ServiceCollection()
                .AddSingleton<IFileSystem, FileSystem>()
                .AddSingleton<IBuildModelFactory, BuildModelFactory>();
            task.ConfigureServices(collection);
            using var provider = collection.BuildServiceProvider();

            task.InvokeExecute(provider);

            var which = task.WhichPublishingTask(manifestFullPath);
            which.Should().BeOfType<PublishArtifactsInManifestV3>();

            which.Execute();

            task.Log.HasLoggedErrors.Should().BeTrue();
            buildEngine.BuildErrorEvents.Should().Contain(e =>
                e.Message.Equals($"Channel with ID '{invalidChannelId}' is not configured to be published to."));
        }
```

But this is blocked on PublishArtifactsInManifestV3.ExecuteAsync being able to mock the IMaestroApi. Can we merge as is @epananth ?

**Comment by epananth** [comment]
I will take care of this test here (https://github.com/dotnet/arcade/issues/6931). please go ahead and merge.

**Pull request merged**
