### PR TITLE
Support adding a version tag to the build manifest

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/5299

Some notes:

- I don't think we need a complex versioning system so I decided to go with just a number.
- I added the option for the user of the task to inform the version tag so that:
  - We can let users specify a version in their `Publishing.props` and keep using an specific version.
  - We can use that while working on a newer version of the infra.

I'll spin up some test builds but I've already ran some tests locally.

### CODE REVIEW

**Comment by epananth** [comment]
Are we planning to write unit tests for this in future?

**Comment by epananth** [comment]
Ah sorry, I reread your issue on after I posted my comment. Disregard this.

**Comment by JohnTortugo** [comment]
Tested in this build: https://dnceng.visualstudio.com/internal/_build/results?buildId=610581&view=results Look for the `PublishingVersion` in the build manifest.

> Are we planning to write unit tests for this in future?

IMO there isn't much new code here to test. But I sure can add a simple unit test to check that the correct value is added to the manifest. I just want to get some feedback first if people think that this versioning mechanism will be sufficient.

**Comment by JohnTortugo** [comment]
> Tested in this build: https://dnceng.visualstudio.com/internal/_build/results?buildId=610581&view=results Look for the `PublishingVersion` in the build manifest.
> 
> > Are we planning to write unit tests for this in future?
> 
> IMO there isn't much new code here to test. But I sure can add a simple unit test to check that the correct value is added to the manifest. I just want to get some feedback first to see if people think that this versioning mechanism will be sufficient.

**Pull request merged**
