### PR TITLE
Remove duplicate package Icon

### PR DESCRIPTION
**Pull request by ericstj**
We were double-including the package icon after we started including
@(None) items in the package.

Remove the redundant item and use the same property as CSProj pack
target for specifying the Icon.

This was regressed here https://github.com/dotnet/arcade/commit/50da2e606edc3ec69750480c356f433e710304ef#r40426132

### CODE REVIEW

**Comment by akoeplinger** [comment]
@ericstj it looks like this breaks the arcade bump in https://github.com/dotnet/llvm-project/pull/58. It's possible that the way we set up the packaging projects there isn't entirely correct though, so I'd appreciate any pointers.

**Comment by ericstj** [comment]
@akoeplinger this repo has the same bug that coreclr did.  Check out this change: https://github.com/dotnet/runtime/commit/7ec5302874ecbc2bc3cf580d006b4d1b3fbc6e7c#diff-e98ea49ea8fa5661939a1d9ffb312bba

**Comment by akoeplinger** [comment]
Thanks, that did indeed fix the issue.

**Comment by akoeplinger** [comment]
yeah we just copied pieces from dotnet/runtime in order to create a nuget package, happy to get rid of them if possible.

**Comment by ViktorHofer** [comment]
Cam someone please open an issue to track the pkgproj removal in repos outside of dotnet/runtime? Thanks

**Comment by akoeplinger** [comment]
@ViktorHofer here on arcade? or in runtime?

**Comment by ViktorHofer** [comment]
In arcade probably as the package lives here.

**Pull request merged**
