### PR TITLE
[release/6.0] Port 1ES pool changes to 6.0

### PR DESCRIPTION
**Pull request by mmitche**
This is a port of the linked PRs from main that streamline and remove retail pool usage from the common templates. There are some 'unnecessary' changes in here (like publishing) which are always taken from main, but it's easier to take the changes wholesale.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1584456 - arcade build
Will test on some other repos first.

**Review by riarenas — APPROVED** [review]

**Comment by mmitche** [comment]
aspnetcore https://dev.azure.com/dnceng/internal/_build/results?buildId=1584752&view=results

**Comment by mmitche** [comment]
@riarenas Can I get a re-approval after the merge?

**Review by riarenas — APPROVED** [review]

**Pull request merged**
