### PR TITLE
[main] Update OctoKit to 12.0.0

### PR DESCRIPTION
**Pull request by lbussell**
Part of https://github.com/dotnet/docker-tools/issues/1322

See https://github.com/octokit/octokit.net/issues/2927

### CODE REVIEW

**Comment by lbussell** [comment]
Migrating package... https://dev.azure.com/dnceng/internal/_build/results?buildId=2470208&view=results

**Review by dougbu — APPROVED** [review]
Approving but please confirm Octokit is exercised enough in the validation build to ensure we won't hit regressions / breaking changes in production.

**Review by mthalman — APPROVED** [review]

**Comment by lbussell** [comment]
> Approving but please confirm Octokit is exercised enough in the validation build to ensure we won't hit regressions / breaking changes in production.

@dougbu, this update to OctoKit should only change comment IDs from ints to longs. M.DN.VersionTools.Automation.GitHubApi doesn't expose that ID so this is not a breaking change.

**Pull request merged**
