### PR TITLE
Upgrade System.Text.Encodings.Web to 4.7.2 per CG

### LINKED ISSUE #7160: Fix ComponentGovernance alerts in arcade
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We have two CG alerts right now. They can be found here: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade?_a=alerts&typeId=6283540&alerts-view-option=active.

The two that we are seeing are related to the version of System.Text.Encodings.Web and the recommendation is this:

```
Upgrade to version System.Text.Encodings.Web - 4.5.1,4.7.2,5.0.1
```

### PR DESCRIPTION
**Pull request by jonfortescue**
Fixes #7160.

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Review by ChadNedzlek — APPROVED** [review]
Sure, why not. :-)

**Comment by adiaaida** [comment]
Well... That's a build result I certainly didn't expect.

**Comment by jonfortescue** [comment]
well huh...okay well guess I'll debug this lol

**Comment by jonfortescue** [comment]
@ChadNedzlek @adiaaida Latest push fixes build errors but changes things more broadly so ptal.

**Review by adiaaida — APPROVED** [review]
LGTM, so long as testing is all good

**Review by ChadNedzlek — APPROVED** [review]

**Pull request merged**
