### PR TITLE
Add references to newtonsoft.json for transitive version pinning

### PR DESCRIPTION
**Pull request by riarenas**
part of https://github.com/dotnet/arcade/issues/10101

Adds references to newtonsoft.json everywhere we need to control transitive pinning.

Running https://dev.azure.com/dnceng/internal/_build/results?buildId=1898566&view=results to see what CG thinks of these changes and whether they are enough.

A lot of the older versions we get through msbuild, which seems like too big of a dependency to just update everywhere, which makes me think the direct references are the best way to go to get this sorted. 

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by riarenas** [comment]
missed some. New test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1898609&view=results

**Comment by riarenas** [comment]
latest test build is finding some references to `9.0.1` that I can't quite track

**Comment by riarenas** [comment]
I think the last few references are coming from the test sdk. There's a newer version uploaded to solve their own newtonsoft dependency issues: https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/17.4.0-preview-20220707-01#dependencies-body-tab

Upgrading from [our current version](https://github.com/dotnet/arcade/blob/95c90ff3e1fdf0df923819efab997962ed64bc5d/eng/Versions.props#L43) means we'll have to update some other dependencies, (or make sure to add newtonsoft references to every test project in the repo) so that might be better left as a separate PR.


```
\src\Microsoft.DotNet.VersionTools.Tasks.Tests\Microsoft.DotNet.VersionTools.Tasks.Tests.csproj : error NU
1605: Detected package downgrade: NuGet.Frameworks from 5.11.0 to 5.6.0-preview.2.6489. Reference the package directly
from the project to select a different version.  [\Arcade.sln]
\src\Microsoft.DotNet.VersionTools.Tasks.Tests\Microsoft.DotNet.VersionTools.Tasks.Tests.csproj : error NU
1605:  Microsoft.DotNet.VersionTools.Tasks.Tests -> Microsoft.NET.Test.Sdk 17.4.0-preview-20220707-01 -> Microsoft.Test
Platform.TestHost 17.4.0-preview-20220707-01 -> Microsoft.TestPlatform.ObjectModel 17.4.0-preview-20220707-01 -> NuGet.
Frameworks (>= 5.11.0)  [\Arcade.sln]
\src\Microsoft.DotNet.VersionTools.Tasks.Tests\Microsoft.DotNet.VersionTools.Tasks.Tests.csproj : error NU
1605:  Microsoft.DotNet.VersionTools.Tasks.Tests -> NuGet.Frameworks (>= 5.6.0-preview.2.6489) [\Arcade.sl
n]
\src\Microsoft.DotNet.SourceBuild\tests\Microsoft.DotNet.SourceBuild.Tasks.Tests.csproj : error NU1605: De
tected package downgrade: NuGet.Frameworks from 5.11.0 to 5.6.0-preview.2.6489. Reference the package directly from the
 project to select a different version.  [\Arcade.sln]
\src\Microsoft.DotNet.SourceBuild\tests\Microsoft.DotNet.SourceBuild.Tasks.Tests.csproj : error NU1605:  M
icrosoft.DotNet.SourceBuild.Tasks.Tests -> Microsoft.NET.Test.Sdk 17.4.0-preview-20220707-01 -> Microsoft.TestPlatform.
TestHost 17.4.0-preview-20220707-01 -> Microsoft.TestPlatform.ObjectModel 17.4.0-preview-20220707-01 -> NuGet.Framework
s (>= 5.11.0)  [\Arcade.sln]
\src\Microsoft.DotNet.SourceBuild\tests\Microsoft.DotNet.SourceBuild.Tasks.Tests.csproj : error NU1605:  M
icrosoft.DotNet.SourceBuild.Tasks.Tests -> NuGet.Frameworks (>= 5.6.0-preview.2.6489) [\Arcade.sln]
\src\Microsoft.DotNet.PackageTesting.Tests\Microsoft.DotNet.PackageTesting.Tests.csproj : error NU1605: De
tected package downgrade: NuGet.Frameworks from 5.11.0 to 5.6.0-preview.2.6489. Reference the package directly from the
 project to select a different version.  [\Arcade.sln]
\src\Microsoft.DotNet.PackageTesting.Tests\Microsoft.DotNet.PackageTesting.Tests.csproj : error NU1605:  M
icrosoft.DotNet.PackageTesting.Tests -> Microsoft.NET.Test.Sdk 17.4.0-preview-20220707-01 -> Microsoft.TestPlatform.Tes
tHost 17.4.0-preview-20220707-01 -> Microsoft.TestPlatform.ObjectModel 17.4.0-preview-20220707-01 -> NuGet.Frameworks (
>= 5.11.0)  [\Arcade.sln]
\src\Microsoft.DotNet.PackageTesting.Tests\Microsoft.DotNet.PackageTesting.Tests.csproj : error NU1605:  M
icrosoft.DotNet.PackageTesting.Tests -> NuGet.Frameworks (>= 5.6.0-preview.2.6489) [\Arcade.sln]
    0 Warning(s)
    3 Error(s)
```

**Review by MattGal — APPROVED** [review]
LGTM, I assume you've built locally and checked out the package cache too?

**Comment by AlitzelMendez** [comment]
I talked with Ricardo and I am going to merge this pr to handle the other alerts in other pr

**Pull request merged**
