### PR TITLE
[release/3.x] Move to latest SDK

### PR DESCRIPTION
**Pull request by dougbu**
### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by rbhanda — APPROVED** [review]

**Comment by dougbu** [comment]
@mmitche Should I bump the SDK version here and in #9994❔ Or do you want to create new PRs next week ❔

**Comment by mmitche** [comment]
> @mmitche Should I bump the SDK version here and in #9994❔ Or do you want to create new PRs next week ❔

Bump it in the already opened PRs. I'll do this next week when it releases.

**Comment by dougbu** [comment]
Won't pass 'til release but ready

**Comment by dougbu** [comment]
Needs approval and merging (I don't have rights in this branch) but `All checks have passed`

**Review by mmitche — APPROVED** [review]

**Pull request merged**
