### PR TITLE
Retry failed requests when pulling provisioning profiles

### PR DESCRIPTION
**Pull request by premun**
This is trying to address the following error:
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
```

reported in #8703

### CODE REVIEW

**Comment by premun** [comment]
@MattGal can you help me review this one?

We are having issues with SSL connection when pulling files from `netcorenativeassets`. It happens rarely and probably started recently but we run this code many times a day and only fails sometimes (we pull 1 file per the whole build, then we pull files in every work item from bash but that seems to be working fine).

The storage account shows occasional failures:
image


I am not sure that this is the right solution though..

**Review by garath — CHANGES_REQUESTED** [review]
This check should not be disabled. It will make SDL unhappy.

**Comment by premun** [comment]
> This check should not be disabled. It will make SDL unhappy. 

Do you think retries would help? It will it be three times this?

**Comment by garath** [comment]
> Do you think retries would help? Or will it be three times this?

I haven't looked at the occurrence frequency yet, but you mention it's intermittent. Given that, plus that this is "supposed to work reliably" makes me think retries are a good idea.

**Comment by garath** [comment]
Thinking aloud... We've enabled CRL checks everywhere as part of SDL improvements. Where possible we should start keeping tabs on how often it fails. I would be surprised if it was a _serious_ impact, but... I'd like to prove that if reasonable. I'll spend a bit of time poking at app insights queries to get a starting point.

**Comment by MattGal** [comment]
> Thinking aloud... We've enabled CRL checks everywhere as part of SDL improvements. Where possible we should start keeping tabs on how often it fails. I would be surprised if it was a _serious_ impact, but... I'd like to prove that if reasonable. I'll spend a bit of time poking at app insights queries to get a starting point.

Thinking back at you aloud, what if we did something like this:

- Ensure existing retries have verbose and friendly logging that makes it explicitly clear a retry happened, while also turning up (say doubling) number of retries
- After a reasonable amount of time we will either see one of two things:
  - This always happens regardless of number of retries / length of delay
  - Retries work
- In the former case, we just accept it; it's network flakiness.   Potentially dropping the retries back down
- In the latter case, we can turn up the retries since we want the CRL checks on.

**Comment by garath** [comment]
> Thinking back at you aloud, what if we did something like this:

Reasonable and wise.

**Comment by premun** [comment]
Thanks both.

To make things clear - right now there are **no retries**. The thing I am worried about is that retries won't help - that if the agent is missing some intermediate certs or something similar, it will just try three times.

The problem occurred twice in about 30(?) runtime builds in the last week and was reported to us. 

I will try to pull the frequency out of Kusto, add retries and monitor this then.

**Comment by premun** [comment]
@garath the new socket handler won't work unfortunately because we need to target .NET 472 (since these are MSBuild tasks).

I looked up errors in Kusto connected to this MSBuild task and there are more problems - transient ones such as "Connection reset by peer" so I added retries.

```sql
TimelineIssues
| where Type == "error" and Message contains "CreateXHarnessAppleWorkItems"
| join kind=inner TimelineBuilds on BuildId
| where StartTime > now() - 14d
```

**Review by garath — APPROVED** [review]

**Pull request merged**
