### PR TITLE
Reboot+retry for Simulator hangs only (not devices, Mac Catalyst)

### PR DESCRIPTION
**Pull request by premun**
From now on, we will also have a dedicated exit code (123) in Kusto so that we can analyze how often this happens

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by premun** [comment]
From now on, we will also have a dedicated exit code (123) in Kusto so that we can analyze how often this happens

**Comment by premun** [comment]
From now on, we will also have a dedicated exit code (123) in Kusto so that we can analyze how often this happens

**Comment by garath** [comment]
> From now on, we will also have a dedicated exit code (123) in Kusto so that we can analyze how often this happens

Is this exit code documented in anywher (FR wiki, feature docs)? If not, I think it really should.

**Comment by MattGal** [comment]
> > From now on, we will also have a dedicated exit code (123) in Kusto so that we can analyze how often this happens
> 
> Is this exit code documented in anywher (FR wiki, feature docs)? If not, I think it really should.

Should probably go to the readme under here: https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner

**Comment by premun** [comment]
Yup, I might but ideally this will be invisible to everyone since the retry will happen and the work item will complete on a different machine. So this is rather something for me to watch for in the stats. But I will add a note.

**Pull request merged**
