### PR TITLE
Backport #6880 to release/3.x

### PR DESCRIPTION
**Pull request by RikkiGibson**
## Description

Cherry-pick of #6880 into release/3.x branch so Roslyn can close its credscan bugs without worrying about them coming back after we update Arcade again.

cc @MattGal @riarenas @davidwengier

## Customer Impact

The process for dealing with these credscan bugs is very cumbersome. They keep coming back.

## Regression

No

## Risk

Very low. Just removing comments that are being flagged as credentials.

## Workarounds

No. The exception process for these bugs doesn't play well with files that are shared among multiple repositories

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Review by davidwengier — APPROVED** [review]
Thanks Rikki

**Comment by RikkiGibson** [comment]
Please let me know if anything else is needed before we can merge this.

**Comment by markwilkie** [comment]
Thanks @RikkiGibson.  Since this is a backport into a release branch, you'll need to fill out the tempalte.  https://github.com/dotnet/arcade/blob/ca7fab569267ed3bc73360882d652d119aae5653/Documentation/Policy/AskTellMode.md

**Comment by markwilkie** [comment]
cc/ @mmitche

**Review by riarenas — APPROVED** [review]

**Comment by riarenas** [comment]
I filled out the template. I have 40+ workitems caused by this file assigned to me right now so I understand the pain of trying to get them to stay closed.

**Review by markwilkie — APPROVED** [review]

**Comment by riarenas** [comment]
Thanks @RikkiGibson!

**Pull request merged**
