### PR TITLE
Update IbcMerge to latest version

### PR DESCRIPTION
**Pull request by davidwrighton**
- Add better error message for missing Ibc data

### CODE REVIEW

**Comment by tmat** [comment]
@davidwrighton Have you done local testing using the new IBCMerge version with dotnet/runtime or dotnet/roslyn repo?

**Comment by davidwrighton** [comment]
@tmat No. How do I do that? I'm pretty unfamiliar with how IbcMerge is actually integrated into our build environment.

**Comment by tmat** [comment]
For repos that get training data from VS IBC training infra (like Roslyn), the local testing is documented here: https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#testing-locally. 

IDK how dotnet/runtime does it, @brianrob should be able to help there.

It'd certainly take some time to do it if you're not familiar with the system. If you are making changes that are unlikely to break anything then it's probably not worth going thru the whole exercise.

**Comment by brianrob** [comment]
@jkoritzinsky who has been doing much of the IBC and PGO related work in dotnet/runtime.  He should be able to help you with the steps to update the IBC package and then restore and test locally.

**Comment by jkoritzinsky** [comment]
Here's the steps to test out a new IBCMerge in dotnet/runtime.

1. Add the line you changed to dotnet/runtime's eng/Versions.props.
2. Run `dotnet restore eng/common/internal/Tools.csproj --configFile eng/internal/NuGet.config` from the repository root.
3. Build in release. Now that IBCMerge has been restored on your machine, your build will automatically opt-in to running it on release builds (at least that's been my experience since moving to the Arcade system).

The other option is to do step one in a new branch, push it to the internal repo and queue an official build. That will for sure run it.

**Comment by davidwrighton** [comment]
I've tested on the Runtime repo and it looks good to me.

**Comment by jkoritzinsky** [comment]
Since this has been tested out, I'll merge this in.

**Pull request merged**
