### PR TITLE
[release/6.0] Generate SBOM for vs insertions

### PR DESCRIPTION
**Pull request by epananth**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

Issue -> https://github.com/dotnet/arcade/issues/9698

msbuild -> https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6321968&view=results

### CODE REVIEW

**Comment by epananth** [comment]
This is failing cos of xharness timeout. By porting these changes to release/6.0 https://github.com/dotnet/arcade/commit/8e2ccde11b70936d8254669a4a74653c580a1340 and https://github.com/dotnet/arcade/commit/18adc5b47acce8bb03948baf578fca442d1029d4
this error should go away

**Comment by epananth** [comment]
we can technically merge this changes cos my change has nothing to do with xharness test, and on the side get these other PRs ported.

**Comment by premun** [comment]
@epananth build is green after a re-run, it was just a backed up queue, no problems in the code itself

**Review by mmitche — APPROVED** [review]

**Pull request merged**
