### PR TITLE
Update to preview 4

### PR DESCRIPTION
**Pull request by mmitche**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by riarenas** [comment]
@mmitche I think we need to change the container in use for Linux from Centos 7 as .NET 8 no longer supports it: https://github.com/dotnet/sdk/issues/31893.

This might also be a noisy one because Centos 7 is still used in main in a few places https://github.com/search?q=org%3Adotnet+mcr.microsoft.com%2Fdotnet-buildtools%2Fprereqs%3Acentos-7&type=code&p=1

**Comment by mmitche** [comment]
@riarenas Moved to CBL mariner.

**Review by riarenas — DISMISSED** [review]

**Review by riarenas — DISMISSED** [review]
oh right, redhat7 is on the same boat

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
