### PR TITLE
[release/6.0][1ES Template] Migrate arcade-official-ci pipeline

### PR DESCRIPTION
**Pull request by AlitzelMendez**
validate in build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408627&view=results
issue: https://github.com/dotnet/dnceng/issues/2270

### CODE REVIEW

**Comment by AlitzelMendez** [comment]
> the validation build didn't quite work:
> 
> ```
> ##[information]Could not start execution of workflow. Logging telemetry SBOMTelemetry {Result=Failure, Errors=null, Parameters=InputConfiguration {BuildDropPath=ConfigurationSetting`1 {Value="D:\\a\\_work\\1\\a\\ReleaseConfigs.txt", Source=JsonConfig, IsDefaultSource=False}, BuildComponentPath=ConfigurationSetting`1 {Value="D:\\a\\_work\\1", Source=JsonConfig, IsDefaultSource=False}, BuildListFile=null, ManifestPath=null, ManifestDirPath=null, OutputPath=null, Parallelism=null, Verbosity=ConfigurationSetting`1 {Value=Verbose, Source=CommandLine, IsDefaultSource=False}, ConfigFilePath=ConfigurationSetting`1 {Value="D:\\a\\_work\\_temp\\SBOM-Config-b5f3359b-9616-40e0-9b06-f6d9042290f1.json", Source=CommandLine, IsDefaultSource=False}, ManifestInfo=ConfigurationSetting`1 {Value=null, Source=Default, IsDefaultSource=True}, HashAlgorithm=ConfigurationSetting`1 {Value=AlgorithmName {Name="SHA256"}, Source=Default, IsDefaultSource=True}, RootPathFilter=null, CatalogFilePath=null, ValidateSignature=null, IgnoreMissing=null, ManifestToolAction=Generate, PackageName=null, PackageVersion=null, PackageSupplier=null, FilesList=null, PackagesList=null, TelemetryFilePath=ConfigurationSetting`1 {Value="D:\\a\\_work\\_temp\\Telemetry-307f8872-9196-4b53-b266-0975ae9228bd.json", Source=JsonConfig, IsDefaultSource=False}, DockerImagesToScan=null, ExternalDocumentReferenceListFile=null, AdditionalComponentDetectorArgs=null, NamespaceUriUniquePart=null, NamespaceUriBase=null, GenerationTimestamp=null, FollowSymlinks=null, DeleteManifestDirIfPresent=null, FailIfNoPackages=null, FetchLicenseInformation=ConfigurationSetting`1 {Value=False, Source=JsonConfig, IsDefaultSource=False}, EnablePackageMetadataParsing=ConfigurationSetting`1 {Value=False, Source=JsonConfig, IsDefaultSource=False}}, SBOMFormatsUsed=null, Timings=[], Switches={}, Exceptions={["PowerArgs.ValidationArgException"]="BuildDropPath directory not found for 'D:\\a\\_work\\1\\a\\ReleaseConfigs.txt'"}, APIExceptions=null, MetadataExceptions=null, TotalLicensesDetected=0, PackageDetailsEntries=0}
> BuildDropPath directory not found for 'D:\a\_work\1\a\ReleaseConfigs.txt'
> ##[error]Manifest generation failed, please check output file for more info.
> ```
> 
> you probably need the usual file ➡️ directory change in this PR b/4 this is actually ready to go

this is a problem on arcade, it was fixed for other branches, but it was unable to get backported to 6.0: https://github.com/dotnet/arcade/pull/14582

**Review by dougbu — APPROVED** [review]
I agree there's no changes needed in this PR. unfortunately must wait for #14617 and then restart the build here to pick up that fix in the generated merge commit

**Pull request merged**
