### PR TITLE
Add missing variable group to `common-variables.yml`

### PR DESCRIPTION
**Pull request by JohnTortugo**
Closes: https://github.com/dotnet/arcade/issues/4257

@mmitche found that this variable group is missing when the internal channel stage is activated.

### CODE REVIEW

**Comment by riarenas** [comment]
I see that all the channel yamls include it here: https://github.com/dotnet/arcade/blob/5a666a2e3e7eadfd61ca34a0003630103a0486b0/eng/common/templates/post-build/channels/netcore-internal-30.yml#L53

I see no problem with adding to common-vars but:

* We should then remove it from the publish jobs in each channel yaml.
* This change should target master, and once that is merged, you should cherry-pick the change following the template for the PR found here: https://github.com/dotnet/arcade/blob/master/Documentation/Policy/AskModeTellModeTemplate.md

**Comment by mmitche** [comment]
After a second look, it does look like this should have worked.  @JohnTortugo can you make some manual changes in the dotnet-toolset branch https://dev.azure.com/dnceng/internal/_git/dotnet-toolset?version=GBinternal-test and see whether the fix above solves the issue? We are confused as to why this is failing.

You should unlink the feed pat variable group from the toolset build pipeline before you do.

**Comment by JohnTortugo** [comment]
Yeap, let me take a look.

**Comment by JohnTortugo** [comment]
> I see that all the channel yamls include it here:

@riarenas - However, the symbol publishing jobs doesn't include the group: https://github.com/dotnet/arcade/blob/3bbaf862aac175fca30fc4b82fdec83d7b132f23/eng/common/templates/post-build/channels/netcore-internal-30.yml#L47



> After a second look, it does look like this should have worked. @JohnTortugo can you make some manual changes in the dotnet-toolset branch https://dev.azure.com/dnceng/internal/_git/dotnet-toolset?version=GBinternal-test and see whether the fix above solves the issue? We are confused as to why this is failing.

@mmitche - I tested it in Toolset and also in Arcade and adding the variable group in the YAML works. See for instance these Arcade builds, which doesn't have any group linked 'manually' to the build-def:

- [Build fail because group isn't linked in the symbol publishing job.](https://dnceng.visualstudio.com/internal/_build/results?buildId=409719&view=results)
- [Build succeed because the group is linked in the `common-variables.yml` template.](https://dnceng.visualstudio.com/internal/_build/results?buildId=409766&view=results)

**Comment by riarenas** [comment]
I think we just missed the fact that the symbol publishing job is also using the task because it needs to restore. If any repo that tries to publish symbols has a private feed in their NuGet.config, then we'll see this.

Adding the variable to the common-variables seems like the safest fix. We should also consider adding the cross-org task to the other channel Yamls.

**Comment by riarenas** [comment]
My only other feedback is still the base branch situation. @mmitche do we want to merge this in 3.x first? or should this PR be targeted to master first?

**Comment by JohnTortugo** [comment]
I messed my branch up :-( . I'll create another PR

**Pull request closed without merging**
