### PR TITLE
Modify the CreateXHarnessAppleWorkItems task to accept zip files as input

### PR DESCRIPTION
**Pull request by steveisok**
In AOT configurations, the size of the test apps we generate can be quite large (100-200MB).  We can run out of disk space quickly if we have a lot of uncompressed .app folders around.  

This change adds accepting zip files as part of the AppBundles item and instead of creating the zip file, we will just make a copy instead.

### CODE REVIEW

**Comment by steveisok** [comment]
The failing device test seems to actually be running correctly as indicated in https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-7740-merge-a780d793f3de4522a3/System.Buffers.Tests/1/net.dot.System.Buffers.Tests.log?sv=2019-07-07&se=2021-08-31T15%3A49%3A19Z&sr=c&sp=rl&sig=gAm3fM7FRdmuAmhmkl%2Fu3oFMZNJ1W0yVhgv9ETxqwCQ%3D

I'm not sure if it's reporting a false failure as a result of:

```
08:50:05.5911020] 2021-08-11 08:50:05.605 System.Buffers.Tests[41272:62372894] .
[08:50:05.6591300] 2021-08-11 08:50:05.673 System.Buffers.Tests[41272:62372894] Failed to initialize TCP writer. Continuing on console.
[08:50:05.6591680] System.Net.Sockets.SocketException (48): Address already in use
[08:50:05.6591780]    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName) in System.Net.Socket
[08:50:05.6591980] 2021-08-11 08:50:05.673 System.Buffers.Tests[41272:62372894] s.dll:token 0x600025a+0x27
[08:50:05.6592050]    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) in System.Net.Sockets.dll:token 0x60001c9+0x5e
[08:50:05.6592110]    at System.Net.Sockets.Socket.Bind(EndPoint localEP) in System.Net.Sockets.dll:token 
[08:50:05.6593040] 2021-08-11 08:50:05.673 System.Buffers.Tests[41272:62372894] 0x60001c8+0x6e
[08:50:05.6593450]    at System.Net.Sockets.TcpListener.Start(Int32 backlog) in System.Net.Sockets.dll:token 0x6000380+0x34
[08:50:05.6593540]    at System.Net.Sockets.TcpListener.Start() in System.Net.Sockets.dll:token 0x600037f+0x1
[08:50:05.6593670]    at Microsoft.DotNet.XHarness.TestRunners.C
[08:50:05.6593750] 2021-08-11 08:50:05.673 System.Buffers.Tests[41272:62372894] ommon.TcpTextWriter.InitializeWithTunnelConnection(Int32 port) in Microsoft.DotNet.XHarness.TestRunners.Common.dll:token 0x6000060+0x25
[08:50:05.6593810]    at Microsoft.DotNet.XHarness.TestRunners.Xunit.iOSApplicationEntryPoint.RunAsync() in Microsoft.DotNet.XHarness.TestR
```

**Comment by akoeplinger** [comment]
I retried the tests and they passed :)

Going to merge this one so we're unblocked but @premun please let us know if you have feedback once you're back!

**Review by akoeplinger — APPROVED** [review]

**Comment by premun** [comment]
@akoeplinger LGTM! Only feedback would be that we expect the archive to not be named `.app.zip` but just `.zip` if I understand it properly?

**Comment by akoeplinger** [comment]
@premun correct, it should be .zip, not .app.zip.

**Comment by premun** [comment]
@akoeplinger I am just wondering whether we shouldn't validate it then (or maybe mention it in the `Readme.md`). I am also wondering whether we shouldn't allow the same in Android.

**Comment by akoeplinger** [comment]
@premun yeah good points I think we should validate it.

**Pull request merged**
