### PR TITLE
SignCheck fixes (#4058) for 3.x

### PR DESCRIPTION
**Pull request by joeloff**
* Add support for files that should never be signed
* nupkg repository signature checks
* Fix handling external CAB files in containers to ensure both the CAB + MSI are extracted before verifying the MSI

### CODE REVIEW

**Comment by mmitche** [comment]
@joeloff When this makes it into the .NET 3 Tools channel, only trigger it for the repo that needs it to avoid a reset of 3.0

**Comment by dougbu** [comment]
> @joeloff When this makes it into the .NET 3 Tools channel, only trigger it for the repo that needs it to avoid a reset of 3.0

I'll do this for the AspNetCore repo once we've done the 2nd phase - changing the Arcade SDK to pick up the latest signing tool package version. In particular, I will combine the dependency update into a PR that re-enables signing validation.

----
@markwilkie who are the privileged few who can merge this good work?

**Comment by markwilkie** [comment]
Pretty sure merge is open to Microsoft/dotnet devs.  Maybe @mmitche added some restrictions, I think we talked about it briefly but I don't know what came of it.

**Comment by joeloff** [comment]
Thanks @mmitche 

@markwilkie I got a big red X saying that merge permissions are restricted for 3.x

**Pull request merged**
