### PR TITLE
revert .net sdk version to 9.0.101

### PR DESCRIPTION
**Pull request by haruna99**
## Related Issue
https://github.com/dotnet/dnceng/issues/4635

### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

#### PR Summary
This pull request reverts .net sdk to version 9 to resolve build issues

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@haruna99 what is this PR about?

**Comment by ViktorHofer** [comment]
We don't want to downgrade back to a 9.0.xxx SDK. We explicitly need the .NET 10 SDK for the .NET 10 Preview 1 release. cc @mmitche

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
This is a pipeline specific issue and therefore shouldn't force Arcade to go back to a previous SDK. The `dotnet-arcade-daily` pipeline must be able to use prerelease SDKs or should manually pin back to an older SDK.

**Comment by mmitche** [comment]
@haruna99 Viktor is right here. I think the correct thing to do may just be to do a restore (`Restore.cmd`) of the arcade repo instead of the 'Install global.json SDK' step. That will also install the SDK from the global.json.

**Comment by mmitche** [comment]
@haruna99 Any success here?

**Comment by haruna99** [comment]
> @haruna99 Any success here?

**Comment by haruna99** [comment]
@mmitche I am still working on it. I attempted to restore but encountered errors during the secret-manager synchronization stage. This stage attempts to access .NET 10 online and is unable to access the version downloaded by the restore stage.

**Pull request closed without merging**
