### PR TITLE
Updating SetupNuGetSources.ps1 for SDL compliance

### PR DESCRIPTION
**Pull request by missymessa**
https://github.com/dotnet/dnceng/issues/2127

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by mmitche — APPROVED** [review]
Approved if this works. I would check this in winforms or another repo that uses SetupNugetSources.ps1

**Comment by riarenas** [comment]
Does this let the script still work? This for sure makes the sdl passes stop complaining, but I'm not sure if this keeps the scenario working just by changing everything to a secure string.

Do we know of a repo that already made this change and exercised the script? 

We could also run a test on a repo that already uses the script? Looks like maybe wpf would be a good test? https://github.com/dotnet/wpf/blob/a2c7547c602fe7dfbf8447a563b440d7449b6b6d/eng/pipeline.yml#L165

**Comment by missymessa** [comment]
@rmarinho did this change end up fixing the SDL complaints for y'all?

**Comment by missymessa** [comment]
Ahh, yes, this doesn't look like it will pass the SDL: https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingusernameandpasswordparams?view=ps-modules  

I'll edit.

**Review by dougbu — DISMISSED** [review]
Suggest checking w/ an internal build of the CI pipeline still complains. But, otherwise looks good. In particular I can't see how this would break the script.

**Comment by missymessa** [comment]
> If you edit the param name, we will have to change all of the places that use the script. It might be better to just eliminate the parameter altogether at that point.

The nice thing is that SDL is complaining about the instances of it inside the cmdlet, not the parameter name for the cmdlet :D

**Review by dougbu — APPROVED** [review]
surprised this works on its own (expected something `SecureString`y would be necessary) but wunderbar

**Pull request merged**
