### PR TITLE
Modify CheckHelixJobStatus to check work item exit codes

### PR DESCRIPTION
**Pull request by alexperovich**
This change modifies the CheckHelixJobStatus task to
check for ExitCode == 0 as well as State != 'Failed'
If kusto hasn't finished its processing then the State field
will only have 'Finished'

### CODE REVIEW

**Comment by adamsitnik** [comment]
Hello @alexperovich 

When can I expect a new Helix.Sdk with this fix to be published?

The latest microsoft.dotnet.helix.sdk, 2.0.0-beta.19116.2 does not contain it (yet)

obraz

**Comment by alexperovich** [comment]
version 2.0.0-beta.19119.2 Should have these changes.

**Comment by adamsitnik** [comment]
@alexperovich I confirm, it works now. Thank you!

**Pull request merged**
