### PR TITLE
Arcade build fix per chcosta

### PR DESCRIPTION
**Pull request by jonfortescue**

### CODE REVIEW

**Comment by chcosta** [comment]
Did you schedule an internal build of this to validate that it will fix the issue?

**Comment by jonfortescue** [comment]
about to!

**Comment by jonfortescue** [comment]
or, I mean, I'm not going to merge it until I do that.

**Comment by weshaggard** [comment]
Why isn't this also failing in CI? I'd expect the source link validation to happen there as well.

**Comment by weshaggard** [comment]
>The uri returned by Azure Pipeline appears to be dependent on which pool is running.

That seems like something we need to figure out how to generalize more then in order to allow others to use our arcade.

**Comment by chcosta** [comment]
This is only applicable to teams which are mirroring code from GitHub to Azure DevOps, and then building from Azure DevOps but providing public sources.  As far as I know, that's only dnceng.

**Comment by jonfortescue** [comment]
Build passed [here](https://dnceng.visualstudio.com/internal/_build/results?buildId=26369&view=logs), merging.

**Pull request merged**
