### PR TITLE
Add telemetry property to SymStore.targets

### PR DESCRIPTION
**Pull request by adiaaida**
Closes: https://github.com/dotnet/core-eng/issues/9138

### CODE REVIEW

**Comment by tmat** [comment]
Curious - why is it needed in SymStore.targets? These are included and executed during regular build.

**Comment by chcosta** [comment]
@adiaaida , can you provide a link to the build that failed which led to this PR? That might help understand what gap is missing and/or why this is needed here.

**Comment by adiaaida** [comment]
This is the log of the step that is failing: https://dev.azure.com/dnceng/public/_build/results?buildId=540037&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=cab6e3f0-aa10-5bbb-514b-fc6a638553f8&l=416

Failures in the target that runs Pdb2Pdb are not being categorized.

**Comment by tmat** [comment]
How does the categorization work when other tasks fail during the main build? This should be the same as the csc failing for any reason.

**Comment by chcosta** [comment]
Looking at the binlog, I'd expect this to get categorized as "Build" by default, but I don't see the categorization happening.  @adiaaida , you'll likely need to set up a repro as I wouldn't expect this PR to "fix" anything either.

**Comment by adiaaida** [comment]
I was able to create a repro and determine that, by adding the categorization property to the target in question, it would correctly add the vso decoration.

Screen Shot 2020-03-04 at 1 57 01 PM

PTAL

**Comment by tmat** [comment]
Interesting. Do we not have a general mechanism for failed Targets? It seems odd to need to add `<Telemetry>` task to every target that may fail.

**Comment by adiaaida** [comment]
Chris and I talked about this a bit, and we actually believe the issue is that the failure is in the Exec task, which isn't respecting our telemetry property group, but does respect the tag. A similar place where we've had to add the Telemetry tag is in Xunit.targets, [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L32). I'm going to investigate this and see if there's a different way to force Exec tasks to respect the tag.

**Comment by adiaaida** [comment]
@tmat, I also meant Task in my earlier comment, not Target. Words are hard.

**Comment by tmat** [comment]
Makes sense.

**Comment by adiaaida** [comment]
@chcosta As far as I can tell, what seems to be happening is that the Exec task's parent doesn't seem to have the telemetry property. When I walk up the parent tree a few times, I eventually get something that does have the property, but it doesn't seem to be flowing down properly. Additionally, and this may just be because of the way I was testing this (running Exec Command="exit /b 1"), sometimes NONE of the parents have the telemetry tag.

So, we can either just find all of the places where Exec is called and make sure those tasks have the Telemetry property set as a task property (like we've done with Xunit and like I do here), or we can change PipelineLogger.cs to do a while loop and walk up the parent ids until a telemetry property is found or we run out of ids to check. The second option doesn't seem to guarantee that we will successfully find the categorization check.

**Comment by chcosta** [comment]
what are the symptoms of the scenario where none of the parent id's have a category?

**Comment by adiaaida** [comment]
If they don't have the <Telemetry> tag as part of the task, they don't get categorized.

**Comment by chcosta** [comment]
Sorry, not sure I can get a clear understanding from that response.

when you say "tag", are you referring to the MSBuild static property or the dynamic task call (or both)? I thought the issue was that when using the Exec task, none of the parent id's had a telemetry tag.  Is that the case or not?  It sounded like sometimes a tag was found in the parent hierarchy.

**Comment by adiaaida** [comment]
When the Task has 

```
<Telemetry EventName="NETCORE_ENGINEERING_TELEMETRY" EventData="Category=Build" />
```

The category is correctly set by https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs#L89. When the task does not have the property set, we fall into the else case, where we check the categories set on the parent/projects, [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs#L95). In the else case, we fail to find the telemetry category (ie, it's blank), so we don't add that to the logging properly.

**Comment by chcosta** [comment]
Right, but that seems at odds with

> As far as I can tell, what seems to be happening is that the Exec task's parent doesn't seem to have the telemetry property. When I walk up the parent tree a few times, I eventually get something that does have the property, but it doesn't seem to be flowing down properly. 

where it sounded like you could find the property some times.

**Comment by adiaaida** [comment]
So I was testing it by changing the else clause to a while loop. Sometimes, but not always, walking up the parent ids would eventually lead to a parent with projectInfo.PropertiesCategory set. How does the map get set up?

**Comment by chcosta** [comment]
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/PipelinesLogger.cs#L237

You can attach a debugger to see how it is working, but breaking on that function will be a lot of breaks unless you have a really simple repro.

**Comment by adiaaida** [comment]
Thanks Chris.

**Comment by JohnTortugo** [comment]
Looks like this was fixed by https://github.com/dotnet/arcade/pull/5336

Ok to close @adiaaida ?

**Pull request closed without merging**
