### PR TITLE
Use the 1ES publishing tasks in some missed places in templates-official job.yml

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/dnceng/issues/2133

The `- publish:` steps that are shortcuts to the publish pipeline artifact task were not converted.

I'm working on getting a test build of these changes (I need a better process for this... at this rate maybe it makes sense to convert arcade just to speed up testing) and I will share one as soon as I have it.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by AlitzelMendez — APPROVED** [review]

**Comment by riarenas** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=2400063&view=results for a test build in symreader... I see already that the log and build retry configuration publish were successfully injected into the run, and if it succeeds I'll merge / backport this to release/8.0.

**Comment by riarenas** [comment]
My test build published the retry configuration, but not the logs through the template, since the log publishing uses `artifacts/log` instead of a complete path to publish, I don't want to risk merging without exercising that, so I think I enabled this in my newest test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2400122&view=results

**Review by chcosta — APPROVED** [review]

**Comment by riarenas** [comment]
Log artifact was uploaded just fine in new test build: 
image

I think this is good to go.

**Pull request merged**
