### PR TITLE
Increase parallelism in sourceline and symbols validation

### PR DESCRIPTION
**Pull request by adiaaida**
These two powershell scripts allowed for 6 parallel jobs. Going up to 16 significantly improves the performance of these jobs in the release pipeline (from 1.5hrs to 1 hr for symbols validation and 4.9hrs to 1.9hrs for sourcelink validation).

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by adiaaida** [comment]
I wasn't sure who all to tag as reviewers on this. @dotnet/dnceng if any of you have thoughts on upping the parallelism from 6 parallel tasks to 16, please comment/review.

**Comment by markwilkie** [comment]
Yea, based on @epananth experiments with upload, 16 seems right to me.

**Review by MattGal — APPROVED** [review]
As long as it's been tried successfully once, this sounds great.

**Comment by adiaaida** [comment]
Symbols validation run: https://dev.azure.com/dnceng/internal/_build/results?buildId=1118206&view=logs&s=2f4b62b5-8d35-5570-0513-04a0c5199809&j=b30a92fc-e51b-572d-9566-e3b9dae8a01d
Source link validation run: https://dev.azure.com/dnceng/internal/_build/results?buildId=1118206&view=logs&j=28bdc2c7-156f-51fb-6444-d4b8da3693ac&t=db80a514-da0d-59b3-7d70-a8c1f2a0491a

**Pull request merged**
