### PR TITLE
Retry NuGet signature validation

### PR DESCRIPTION
**Pull request by dougbu**
- see #13070
- more details: <https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures>

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by AlitzelMendez — APPROVED** [review]

**Comment by dougbu** [comment]
@markwilkie what are your thoughts on backporting this fix to release/6.0 and release/7.0❔ Our Helix Machines infrastructure hit the problem and uses a 6.0 SDK.

**Comment by garath** [comment]
> what are your thoughts on backporting this fix to release/6.0 and release/7.0

@dougbu I say go ahead and open the PRs. The right people will be involved in the review there.

**Pull request merged**
