### PR TITLE
Bump `$(MicrosoftDotNetSignCheckVersion)`

### PR DESCRIPTION
**Pull request by dougbu**
- use version containing @joeloff's #4083 fixes

### CODE REVIEW

**Comment by riarenas** [comment]
This change broke Arcade-Validation's official build during the signing validation step: https://dev.azure.com/dnceng/internal/_build/results?buildId=384039&view=results

```
error NU1603: SigningValidation depends on Microsoft.DotNet.SignCheck (>= 1.0.0-beta.19509.6) but Microsoft.DotNet.SignCheck 1.0.0-beta.19509.6 was not found. An approximate best match of Microsoft.DotNet.SignCheck 5.0.0-beta.19468.2 was resolved."
```
which is strange, since the version is in the dotnet-tools feed.
image

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/pull/4090/files#diff-30d0f9decb9a2745121a13c1aae8994aR19

That may need to include the dotnet-tools feed?

**Comment by riarenas** [comment]
Oh, wasn't aware of that restoresources property there. Yeah, that seems like the likely culprit for sure.

**Comment by dougbu** [comment]
- Why is anything still using `$(RestoreSources)`?
- Will that validation failure affect my attempt to use the new Arcade SDK in AspNetCore?

**Comment by riarenas** [comment]
> Why is anything still using $(RestoreSources)? 

I believe it shouldn't.

> Will that validation failure affect my attempt to use the new Arcade SDK in AspNetCore?

Yes. Until Arcade-Validation's build is unstuck, the arcade SDK with this change won't flow to anyone as it won't be available in any of the tools channels.

**Pull request merged**
