### PR TITLE
Fix the official build

### PR DESCRIPTION
**Pull request by alexperovich**
The validate-sdk stuff wasn't restoring correctly so the helix step didn't run with restored packages.

### CODE REVIEW

**Comment by markwilkie** [comment]
Thanks @alexperovich  - what changed that caused this to fail?

**Comment by alexperovich** [comment]
The helix changes I made caused it to stop Restoring the xunit projects it was sending as tests. That exposed the issue that validate-sdk wasn't restoring packages to the correct place.

**Comment by jcagme** [comment]
What's the correct place?

**Comment by alexperovich** [comment]
it was restoring to ~/.nuget/packages, it was expected to be $(RepoRoot)/.packages

**Pull request merged**
