### PR TITLE
Bump binlogtool to latest

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Fixes https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/736
Fixes: https://github.com/dotnet/dnceng/issues/1675

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
MSBuild made a fix that we need to react to.

Original PR:
https://github.com/dotnet/arcade/pull/14253

Fix in MSBuildStructuredLog repo:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/83a97d05a5e02af24ad0e418d83b27840cdd8c14

**Review by JanKrivanek — APPROVED** [review]

**Comment by JanKrivanek** [comment]
I believe `binlogtool` package is already setup to autoupdate in dnceng feed. But just for sure I run the pipeline to explixitly update it to latest (1.0.9 now) https://dev.azure.com/dnceng/internal/_build/results?buildId=2339039&view=results

**Review by ViktorHofer — APPROVED** [review]

**Comment by JanKrivanek** [comment]
> I believe [`binlogtool` package](https://www.nuget.org/packages/binlogtool) is already setup to autoupdate in dnceng feed. But just for sure I run the pipeline to explixitly update it to latest (1.0.9 now) https://dev.azure.com/dnceng/internal/_build/results?buildId=2339039&view=results

So the pipeline run succeeded giving me a false sense of everything is ok, but the update actually didn't happen:

```
Getting all versions for package 'binlogtool'
Found 2 versions in 'dotnet-public'
Skipping 'binlogtool' as owner (kirillosenkov) is unknown or not in allowed list.
```

So it lead to couple issues in promotion pipeline :-/

Reruning the feed push pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=2339968&view=results

**Comment by JanKrivanek** [comment]
Redaction is again running fine in the promotion pipeline :-)
The failed upload turned out to be a wrong parameter ('update' instead of 'new or non-microsoft')

**Pull request merged**
