### PR TITLE
Temporary work around for bad write

### PR DESCRIPTION
**Pull request by jaredpar**
Temporary work around for #2309

### CODE REVIEW

**Comment by jcagme** [comment]
LGTM but would wait for someone more related to the code to sign off. Also, since this a temp solution should we open a tracking issue for the real thing?

**Comment by jaredpar** [comment]
@jcagme issue #2309 is tracking the real fix. The real fix though is complicated enough I want to test locally before pushing it out. This is simple enough and will unblock the repositories immediately blocked here. That's why it's being sent separately.

**Comment by tmat** [comment]
This is not sufficient though. We need to add guid to the xml path as well.

**Comment by jaredpar** [comment]
> This is not sufficient though. We need to add guid to the xml path as well.

Why would we need that. Every write will be unique now. Hence it should be unblocked.

**Comment by tmat** [comment]
@jaredpar I don't think we need to rush with a fix. We have a temp workaround for Roslyn already.

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn/pull/34339

**Comment by jaredpar** [comment]
Okay. If we have a work around I can focus on the correct fix.

**Comment by tmat** [comment]
> Why would we need that. Every write will be unique now. Hence it should be unblocked.

This path needs to include guid as well:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L110

**Comment by jaredpar** [comment]
Ah I see. There are two files here we need to consider: the XML file and the NGEN.

**Pull request closed without merging**
