### PR TITLE
Updated .NET Library license

### PR DESCRIPTION
**Pull request by AbhitejJohn**
When looking for an updated license for .NET libraries shipped from the Unit Testing repo, we got an updated license from CELA. Thought I'd add it to arcade so other repos can use the updated license as well. 

**Note**: Other repos might need to update the license their repo holds given arcade performs a license validation.

### CODE REVIEW

**Comment by riarenas** [comment]
@markwilkie @mmitche What do you think is the right timing for this sort of change? I think it will end up breaking repos and require reaction to it?

**Comment by mmitche** [comment]
@richlander I think has handled license updates in the past. This looks like an update to an existing file, so not sure why it would require reaction in repos?

**Comment by riarenas** [comment]
Arcade has a license validation task that checks the content of the repo's license against arcade's https://github.com/dotnet/arcade/blob/4a43fdd015308fd283e4c380fdc201e433fd0088/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryValidation.proj

**Comment by markwilkie** [comment]
Adding @tmat who wrote the original feature to see if he has any input.  More specially, what sort of validation should be done to see that we don't break anything @tmat ?

**Comment by tmat** [comment]
Not many repos are using this license since it's a closed-source license. If a repo uses this license the PR that updates that repo to the latest Arcade will fail and they'll need to update their license file in the root of the repo to the new version of the license.

**Comment by AbhitejJohn** [comment]
@markwilkie : It sounds like this can be handled as part of the PR validation when a repo updates to the latest arcade. A broadcast announcement to everyone using arcade might be useful as well. When would be a good time to schedule this?

**Comment by mmitche** [comment]
@AbhitejJohn I am a bit confused. Are we suggesting that other repos will need to alter their license?

**Comment by AbhitejJohn** [comment]
@mmitche : If they are using a closed source license, yes.

**Comment by jonfortescue** [comment]
@AbhitejJohn @mmitche @markwilkie @tmat Looks like this stalled out in September. Is there consensus on whether this should be merged?

**Comment by richlander** [comment]
This looks nearly identical to the original license.

We only use this license on Windows. I created this file at some point: https://github.com/dotnet/core/blob/main/license-information-windows.md. It clarifies the situation.

I'm wondering if we should license the Windows version as MIT, too, and then add this other file to explain that there are other terms. The .NET Library license doesn't help clarify these other terms either, so it isn't really buying us anything. I'll ask for input.

**Comment by ChadNedzlek** [comment]
Curious what the state of this PR is. It's been sitting around for a while

**Comment by richlander** [comment]
I just sent mail asking for an opinion on this.

**Comment by missymessa** [comment]
This PR is approaching two years in age... are we planning on doing anything with it?

**Comment by richlander** [comment]
The update looks like primarily a formatting improvement. I'm happy to merge it. That said, it is failing CR.

**Comment by markwilkie** [comment]
Closing as this is too old and there's some risk because of our license automation.

**Pull request closed without merging**
