### PR TITLE
Fix official build with SwaggerGenerator reference mismatch

### PR DESCRIPTION
**Pull request by ViktorHofer**
This change broke the official build: https://github.com/dotnet/arcade/commit/b530fdaddc97f46f19eedc4071655fa086b7b72f#diff-9efa777ddcb56fd9c61fbf93b4c2f378R19

Using ProjectReference instead of PackageReference to not use `MicrosoftDotNetSwaggerGeneratorMSBuildVersion` which always points to the live built not yet published version.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@adiaaida `Microsoft.DotNet.Helix.Client` can't reference `Microsoft.DotNet.SwaggerGenerator.MSBuild` as the first one has a netstandard2.0 TFM but the latter does not. I commented out the P2P reference and the project still builds. Is the reference necessary?

**Comment by ViktorHofer** [comment]
Merging to fix official builds. cc @cchosta

**Comment by adiaaida** [comment]
Sorry about that. @alexperovich suggested that he had fixed things so that uncommenting that line could be checked in. Alex, it looks like we still have to dance around the Swagger include.

**Comment by alexperovich** [comment]
A ProjectReference for this will never work. The PackageReference is needed to support running the generator as an msbuild target. How did this break the official build?

**Comment by ViktorHofer** [comment]
I see. The build was broken becaues the `MicrosoftDotNetSwaggerGeneratorMSBuildVersion` is updated to the live built version of swagger msbuild which isn't publish at that time but the PackageReference already tried to resolve that version from the feed.

**Pull request merged**
