### PR TITLE
Streamline and simplify v3 publishing job

### PR DESCRIPTION
**Pull request by mmitche**
This change removes a bunch of cruft in the publishing job such that:
- v2 is no longer supported, even incidentally (it's not been actually supported by Eng Services for some time, but the code has stuck around)
- A single machine is used for publishing. This reduces the number of allocations, making it possible to move to 1ES pools (not in this change, yet). It also reduces general overhead associated with using multiple jobs and stages.

Implementation is as follows:
- Remove old, unused v3 publishing options and associated templates (nuget, source link and signing validation).
- Collapse all publishing down into a single job that first looks up and validates the build and channel info, setting up any necessary variables for passing to the publish task.
- Call the publish task with the associated parameters
- Also fixes an issue where we were incorrectly passing IsInternalBuild. The value of that was being evaluated in the context of the arcade publishing job, not the actual build we were trying to promote. The value of this is just used for a safety check.
- Remove publish installers and checksums options. This was hardcoded to true, and is legacy from when we were rolling this functionality out.
- Improve the tagging and title of the promotion jobs so that the channel names and BAR id are included in the title, and the BAR id is in the tags.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
First official test (efcore -> general testing): https://dev.azure.com/dnceng/internal/_build/results?buildId=1547402&view=results

Need to check a few others before I call it validated.

**Comment by mmitche** [comment]
For performance purposes, the average time for an efcore promotion appeared to be around 6:30ish. The tests show that it's about 2:30 with these changes.

**Comment by epananth** [comment]
LGTM

**Review by epananth — APPROVED** [review]
LGTM

**Review by alexperovich — APPROVED** [review]

**Comment by MattGal** [comment]
@mmitche heads up this seems to have broken publish using darc? https://dev.azure.com/dnceng/internal/_build/results?buildId=1549109&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073

**Comment by mmitche** [comment]
Yeah, some extra parameters that got removed. I'm going to revert this for now. I think it was just a testing gap, but want to make sure.

**Pull request merged**
