### PR TITLE
Bump symbol uploader version

### PR DESCRIPTION
**Pull request by JohnTortugo**
@mikem8361 created a new version of the symbol uploader and I published it to:

- dotnet-eng, dotnet-tools and dotnet/dotnet-core feed

I'm building a new SDK that uses that version and then try it in a subsequent build. I'll post here the results soon.

### CODE REVIEW

**Comment by JohnTortugo** [comment]
Building new SDK: https://dnceng.visualstudio.com/internal/_build/results?buildId=553361&view=results

**Comment by JohnTortugo** [comment]
Testing the new sdk+symbol uploader: https://dnceng.visualstudio.com/internal/_build/results?buildId=553591&view=results

**Comment by mikem8361** [comment]
The failure is during restore (I think there is a msbuild restore bug that retrying may fix) and has nothing to do with the symbol uploader.

**Comment by JohnTortugo** [comment]
New build here: https://dnceng.visualstudio.com/internal/_build/results?buildId=554385&view=results

**Comment by mikem8361** [comment]
It looks like the symbol publishing was successful. I confirmed it by downloading a package and test downloading them with dotnet-symbol from the (msdl) symbol server.

**Comment by JohnTortugo** [comment]
Thanks @mikem8361 . I'll merge this now.

**Pull request merged**
