### PR TITLE
Remove sleet and tendrils

### PR DESCRIPTION
**Pull request by mmitche**
I was looking to get arcade onboarded onto source-build PVP flow and ran into an issue where there are two different Nuget versions referenced in arcade. One of these is the latest one, and one is 4.4.0. The old one is apparently around because of sleet. We stopped using blob feeds in main long ago. In order to make progress, I took the opportuntity to remove sleet and a lot of tendrils of legacy publishing infras. I did not get it all.

Things that got removed:
- Old tasks that are no longer referenced (vestiges of v2 publishing)
- Sleet references and supporting types.
- Another vestige of the v2 publishing infra (PublishArtifactsInManifestV2), which was no longer referenced.

The primary goal was removing the sleet reference. As I threaded my way through doing that, I pulled out other things that happened to be in the vicinity and were no longer referenced in the following places:
- Arcade itself
- Searches on GitHub did not reveal usages (where applicable)
- Searches of dotnet-release, since it's publishing infra uses some special features.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
@MichaelSimons @crummel This should enable me to remove the [NuGetVersion workaround](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/repo-projects/arcade.proj#L37) for arcade when enabling PVP flow.

**Comment by mmitche** [comment]
I am not done testing and going through the changes with a fine-toothed comb quite yet. I think I got it right but want to make sure.

**Comment by mmitche** [comment]
Alright, I went through this again, found a bit more dead code, and now I think this is ready for review.

**Comment by epananth** [comment]
Can you link the test please?

**Comment by mmitche** [comment]
> Can you link the test please?

Working on that part now.

**Comment by mmitche** [comment]
Official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2095981&view=results

**Comment by mmitche** [comment]
@epananth: https://dev.azure.com/dnceng/internal/_build/results?buildId=2096152&view=results looks good.

**Pull request merged**
