### PR TITLE
Order GenerateInternalsVisibleToFile to run BeforeCompile (#5001)

### PR DESCRIPTION
**Pull request by tmat**
## Description

Port #5001 to 3.x.

## Customer Impact

Fixes embedding generated source files to PDB. Required for Source Link validation.

## Regression

No

## Risk

Some. It is possible that some custom targets depend on the previous (incorrect) ordering.

## Workarounds

None.

### CODE REVIEW

**Comment by tmat** [comment]
@markwilkie

**Comment by tmat** [comment]
@markwilkie I actually just remembered that someone run into an issue with this change. They were using some targets copied from old RepoToolset. There is a potential for break though. On the other hand we really want this change in 3.x because otherwise we can't do full Source Link & deterministic build validation.

**Comment by markwilkie** [comment]
How many more of these do you see coming @tmat?

cc/ @mmitche

**Comment by tmat** [comment]
I was diffing 3.x vs master. Once these get merged and the dust settles I'd do another diff to see if there is still anything significant to bring over. I'd expect at most one or two more changes, but maybe none.

**Comment by markwilkie** [comment]
Do you think we should send out a (possible) breaking change notice?  Not sure the likelihood...

**Comment by tmat** [comment]
This change has been in master for a while and I have heard only one team hitting the issue (their repo is not part of .NET stack).
It's unlikely that anyone depends on this and if they do they likely wouldn't know.

**Pull request merged**
