### PR TITLE
symuploader update for release/6.0

### PR DESCRIPTION
**Pull request by missymessa**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by garath** [comment]
Would arcade-validation test this change?

**Review by garath — APPROVED** [review]

**Comment by mmitche** [comment]
> Would arcade-validation test this change?

It should, it runs publishing.

**Comment by missymessa** [comment]
@epananth says this needs to be tested against Runtime.

**Comment by epananth** [comment]
> > Would arcade-validation test this change?
> 
> It should, it runs publishing.

we have retired running the tests against bell weather repos in arcade validation. I will test it against runtime before we merge this.

**Comment by epananth** [comment]
Runtime builds are red, so cannot test against them. I will test it against installer and sdk instead

**Comment by epananth** [comment]
this worked. merging this one

**Pull request merged**
