### PR TITLE
Upgrade Guardian.Cli version

### PR DESCRIPTION
**Pull request by adiaaida**
Upgrade the guardian.cli version to 0.53.3, as per the Guardian team. 

This will need to be ported to all of the arcade release branches as well.

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Review by riarenas — APPROVED** [review]
LGTM. Did you manage to get a test build using this package?

**Comment by adiaaida** [comment]
I finally got it to run locally. There is some dead code in the scripts that we need to remove per https://github.com/dotnet/arcade/issues/5238.

**Comment by MattGal** [comment]
@wtgodbe FYI. If you very much need that build you were watching to pass you could proactively get this update.

**Comment by wtgodbe** [comment]
Is there a backport of this PR to servicing branches? 3.x builds were failing because of this as well.

**Comment by adiaaida** [comment]
@wtgodbe I'm about to create the 3.x backport!

**Pull request merged**
