### PR TITLE
Remove SDK import from Tools.proj

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/arcade/issues/4102

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera @dougbu

**Comment by riarenas** [comment]
@dotnet/dnceng Could someone help us make sense of these test failures?

**Comment by tmat** [comment]
Let's also rename these tests to something more meaningful than "PizzaTests" and let's make sure they report an actionable error message when they fail.

**Comment by alexperovich** [comment]
Are you referring to these messages?
```
src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(43,5): error : TestRun 11962280: Test PizzaTests.cheese was expected to fail but did not fail.
```

The helix tests for arcade have sets of JUnit and TRX test results that are intentional failures, to validate that failing tests get reported successfully to azure devops. This message means that the test reporting from that work item didn't work.

**Comment by riarenas** [comment]
> This message means that the test reporting from that work item didn't work.

So it might just be related to the other test reporting outage? Worth a rerun in my mind now that we're seeing less issues posting the test runs.

/azp run

**Comment by alexperovich** [comment]
Yep, a quick look at the logs show this https://helix.dot.net/api/2019-06-17/jobs/99a96f9d-0a9a-4c87-a87a-d41d518617c6/workitems/JUnitTest/console

Uploading some attachments for that test run failed.

**Comment by tmat** [comment]
@alexperovich Can we add a link to that log to the output of the test when it fails (something like "See log ... for details."?

Right now all I see when I look at the test failure is this:
image

Not knowing the test I have no idea where to find out why is this failing.

**Comment by tmat** [comment]
Also please rename the test to something like "TestHelixFailureReporting_JUnit"

**Comment by alexperovich** [comment]
@tmat that test failure is 100% correct and expected. The sdk reports a failure to azdev and the MSBuild stuff validates that the failure was reported. We can certainly rename the test, but there will always be a failed test that is intentional.

**Comment by tmat** [comment]
>  will always be a failed test that is intentional

I understand that now but it's not obvious why the PR is blocked. If the failure is supposed to be displayed in the test results than the message should be more self-explanatory. Something like "This failure is expected and is not the reason why your PR failed. This test is always failing in order to test failure reporting infrastructure. If your PR is blocked there must be another test that is causing that".

**Comment by alexperovich** [comment]
That makes sense. I will update the tests.

**Pull request merged**
