### PR TITLE
Port two more fixes

### PR DESCRIPTION
**Pull request by agocke**
## Description

Two more fixes to resource generation that weren't included in https://github.com/dotnet/arcade/pull/5151

## Customer Impact

Current version of the generator creates invalid VB.

## Regression

No

## Risk

Unknown

## Workarounds

None

### CODE REVIEW

**Comment by agocke** [comment]
FYI @markwilkie looks like there were some fixes that weren't included in that PR. I've grabbed all commits that touch resource generation since then (just these two).

**Comment by agocke** [comment]
If there are some docs on how to use a locally built arcade I could test this out first

**Comment by mmitche** [comment]
> If there are some docs on how to use a locally built arcade I could test this out first

I don't know about docs, but here is what I do:
1. In your arcade repo, do .\build.cmd -pack
2. In your target repo, change the arcade references (global.json and Versions.Props) to the version of the arcade packages
3. In your target repo nuget,config, add an entry for the directory the nuget packages from step 1 were built do.
4. Build and test as you need.
5. When iterating, it's important to clean the target repo's package cache

**Comment by tmat** [comment]
I just overwrite the current version in the package cache for faster iteration. Of course, when I'm done i delete it.

**Comment by agocke** [comment]
@markwilkie @mmitche This appears to build locally now

**Pull request merged**
