### PR TITLE
Fix identifiers generated from resx resource names (#2208)

### PR DESCRIPTION
**Pull request by agocke**
* Fix identifiers generated from resx resource names

* Make AggressiveInlining NET20 conditional

(cherry picked from commit 7af51d46ccb26df45bae798c97a804b0ba7f9490)

### CODE REVIEW

**Comment by markwilkie** [comment]
This should be fine.  Before merging though, could you fill out https://github.com/dotnet/arcade/blob/master/Documentation/Policy/AskModeTellModeTemplate.md from https://github.com/dotnet/arcade/blob/master/Documentation/Policy/AskTellMode.md please?

**Comment by markwilkie** [comment]
cc/ @mmitche

**Comment by agocke** [comment]
@markwilkie I can't really speak to any of this, as I didn't author the change. Maybe @tmat knows the answer to these questions?

**Comment by markwilkie** [comment]
I presume you mean the questions in the template @agocke ?  If so, answering them with the context of why you need this backported is sufficient.

**Comment by agocke** [comment]
## Description

Description of the change here.

## Customer Impact

Roslyn will not be able to ship on a servicing-capable Arcade for the 3.X SDKs.

## Regression

No, although since we had already moved to 5.0, this is effectively a regression in our functionality.

## Risk

Unknown

## Workarounds

The code we used before 5.0 doesn't seem to work anymore. We would have to rewrite this logic into some other package and put it into Roslyn.

**Comment by agocke** [comment]
@mmitche @markwilkie One of you will have to merge this, since I don't have permissions.

**Pull request merged**
