### PR TITLE
Add location as attribute of the manifest 

### PR DESCRIPTION
**Pull request by JohnTortugo**
Add location as attribute to the manifest file so that we don't fail on the manifest validation in Tasks.Feed.

This will be reverted eventually when PublishingUsingPipelines is the default option.

### CODE REVIEW

**Comment by JohnTortugo** [comment]
The "Location" attribute isn't necessary when publishing using pipelines. I renamed that attribute to "InitialAssetsLocation". So the validation isn't really correct when publishing using pipelines; nevertheless I think it's best to keep it and add the additional attribute to the manifest for now.

**Comment by riarenas** [comment]
Please create an issue to remove it, and ideally add the issue number to the todo

**Comment by JohnTortugo** [comment]
Thanks Ricardo. Here is the issue: https://github.com/dotnet/arcade/issues/2201

**Comment by chcosta** [comment]
Is this necessary at all if you consume the change I merged yesterday? https://github.com/dotnet/arcade/pull/2151

**Comment by JohnTortugo** [comment]
Yes, actually it's necessary. The manifest for publishing using pipelines use a different set of propertygroup.

**Comment by chcosta** [comment]
I see.  The PropertyGroup isn't the problem though.  The problem is that a similar [change](https://github.com/dotnet/arcade/pull/2151/files#diff-7e5491bb4530041bebe28aadb7d5eca9R156) as was made to `PushToBlobFeed` in the change I linked, should be made to `PushToAzureDevOpsArtifacts`

**Pull request merged**
