### PR TITLE
Add -Force to Write-PipelineTelemetryError calls in sdl scripts

### PR DESCRIPTION
**Pull request by adiaaida**
Closes: https://github.com/dotnet/core-eng/issues/9017

Guardian scripts are definitely reporting errors (which is why we fail the legs). There doesn't seem to be anything wrong with Write-PipelineTelemetryError, which suggests that somewhere in the sdl scripts, we aren't forcing the calls to be written correctly. The only thing I can tell is there are a few places that are missing the -Force option, so adding those. We haven't seen these failures in a while, and they are not reproducible.

### CODE REVIEW

**Comment by adiaaida** [comment]
@chcosta I don't know if this would actually fix anything, but can you take a look at the PR, as those should have -Force anyway.

**Comment by adiaaida** [comment]
Fixes https://github.com/dotnet/core-eng/issues/9138

**Comment by chcosta** [comment]
My hunch is that the sdl scripts aren't always being called with `ci` being set even though these are running in official builds.  It seems equally reasonable either to set `ci` by default in these scripts or add `-Force`.  I guess adding `ci` means it is less likely for someone to add a `Write-PipelineTelemetryError` call in the future and repeat the same mistake.

**Comment by JohnTortugo** [comment]
@riarenas @sunandabalu - Perhaps you can help review this since @chcosta is OOF.

**Comment by sunandabalu** [comment]
The change itself LGTM, @adiaaida did you run a test run with the updated SDL scripts? 

Is there a problem in having $ci=true in each file along with -Force?

**Comment by JohnTortugo** [comment]
@chcosta - PTAL

**Pull request merged**
