### PR TITLE
Add RemoteExecutor.IsSupported property instead of SkipTestException

### PR DESCRIPTION
**Pull request by akoeplinger**
Integrating the SkipTestException added in https://github.com/dotnet/arcade/pull/5401 proved too difficult.
Instead we'll go with annotating tests with ConditionalFact/Theory and using this property to skip.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@safern you need to pass something to the constructor of ConditionalFact/Theory so I thought it's more natural to do `[ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported)]`

**Comment by safern** [comment]
Not really. You don’t need to pass anything. We follow that pattern to skip tests that we want to test on a specific input or value calculated on the test execution without been able to use it at discovery time.

So we add a ConditionalFact/Theory without a constructor.

I’m fine with either way both ways make it that the test needs to be annotated in some way.

**Comment by safern** [comment]
Actually the problem will come up when tests will have multiple conditions combined with this one, since the type of will be different for the conditions we would need to add a property for the condition.

**Comment by safern** [comment]
@stephentoub for thoughts.

**Comment by akoeplinger** [comment]
Discussed with Santi offline, notes:

> Actually the problem will come up when tests will have multiple conditions combined with this one, since the type of will be different for the conditions we would need to add a property for the condition.

I did a spot check and it doesn't seem like there are too many tests that fall into that bucket so this should be manageable.

We discussed keeping the SkipTestException in RemoteExecutor so tests already using the ConditionalFact would just work, but from what I saw the test would then report the condition from the attribute as the skip reason rather than RemoteExecutor which could be very confusing.

**Pull request merged**
