### PR TITLE
Upgrade Arcade to .NET 8 SDK and TFM

### PR DESCRIPTION
**Pull request by ViktorHofer**
Builds on-top of the work from last year: https://github.com/dotnet/arcade/pull/9127

The chosen SDK just released today and finally contains the .NET 8 targeting pack and runtime.

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by ViktorHofer** [comment]
> Unsupported log file format. Latest supported version is 14, the log file has version 15.

@alexperovich @mmitche do you remember what needs to be done to update the `BinLogToSln` tooling?

**Comment by riarenas** [comment]
@ViktorHofer I'm not really up to speed with the source indexing, but looking at https://github.com/dotnet/arcade/issues/11995, it seems like @MattGal published a version which might work with v15? 

Could try changing https://github.com/dotnet/arcade/blob/a83cd13bfe7c684d43380001c8df6da3f5e9b942/eng/common/templates/job/source-index-stage1.yml#L3  to `1.0.1-20221220.2`

**Comment by mmitche** [comment]
@ViktorHofer I think it may make sense to factor out the TFM property into a top-level property to make upgrades touch fewer files the next time around.

**Comment by ViktorHofer** [comment]
> I think it may make sense to factor out the TFM property into a top-level property to make upgrades touch fewer files the next time around.

Arcade already does that: https://github.com/dotnet/arcade/blob/88ed671f2e7e1555dc64654b71b86e4e00e2793d/eng/TargetFrameworkDefaults.props#L4

The file changes in this PR are for props and targets files inside nuget packages which hardcode the TFM. In the past we discussed if we would like to automate that, but the cost vs benefit wasn't great at that time.

**Comment by mmitche** [comment]
> > I think it may make sense to factor out the TFM property into a top-level property to make upgrades touch fewer files the next time around.
> 
> Arcade already does that (we changed that last year as part of #9127):
> 
> https://github.com/dotnet/arcade/blob/88ed671f2e7e1555dc64654b71b86e4e00e2793d/eng/TargetFrameworkDefaults.props#L4
> 
> The file changes in this PR are for props and targets files inside nuget packages which hardcode the TFM. In the past we discussed if we would like to automate that, but the cost vs benefit wasn't great at that time.

Oh. good call. Thanks.

**Review by mmitche — APPROVED** [review]

**Comment by MichaelSimons** [comment]
I'm going to defer my signoff to @lbussell since he did this for the 7.0 release.

**Review by mmitche — APPROVED** [review]

**Pull request merged**
