### PR TITLE
Bring back Apple device and simulator tests and use new queues

### PR DESCRIPTION
**Pull request by premun**
We will use the new queues which should work better

#13044

### CODE REVIEW

**Comment by riarenas** [comment]
@mmitche are you OK with this direction? Or should we instead consider changing the harness validation story as mentioned in the issue?

**Review by riarenas — APPROVED** [review]

**Comment by premun** [comment]
I was looking into this but to only trigger Apple flows for some codepaths would mean to split them into its own build.

**Comment by premun** [comment]
But I understand the flakiness that started and if we see that even with the new queue, I'm up for disabling these again

**Comment by premun** [comment]
Seems like it's still flaky, I will revisit this later

**Comment by mmitche** [comment]
I'm all for testing the simulator, but only if it adds value. If these tests are flaky, or take a lot of time/resources, and we're not finding bugs with them, then let's leave them off.

**Comment by premun** [comment]
@riarenas @mmitche I made the XHarness stage only trigger for certain paths that need to have a change

**Comment by premun** [comment]
Ah, seems it's not quite working yet

**Comment by premun** [comment]
@riarenas @mmitche I finally made the cross-stage pipeline variables work - the matrix strategy (if used) gets in the path of the variable names so I took some time to figure this out. However, it seems to be working now so we can only run XHarness jobs for XHarness-related changes.

**Pull request closed without merging**
