### PR TITLE
Add support for publishing TRX test results in job.yml

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Can we also add coverage by enabling VSTest in Arcade at least partially?

**Comment by alexperovich** [comment]
Arcade doesn't even run tests on the build agents, I didn't want to make a sweeping change like that for this.

**Comment by ViktorHofer** [comment]
Now I get it, this is for the non helix scenario only?

**Comment by alexperovich** [comment]
Yea, this is only for tests that are ran on the build agent, helix runs already support TRX

**Comment by ViktorHofer** [comment]
Makes sense, so that's why mono/linker was affected but I wasn't seeing this in dotnet/runtime in my VSTest PR. Thanks for the explanation.

**Review by ViktorHofer — APPROVED** [review]

**Review by marek-safar — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
