### PR TITLE
Remove dispatch to inner build

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by safern** [comment]
@tmat sorry to make you sad again, but the same issue is still happening. 

>  The command ""D:\a\1\s\.packages\microsoft.diasymreader.pdb2pdb\1.1.0-beta2-19521-03\tools\Pdb2Pdb.exe" "D:\a\1\s\artifacts\bin\installer.tasks\Debug\net46\installer.tasks.dll" /out "D:\a\1\s\artifacts\SymStore\Debug\installer.tasks\net46\installer.tasks.pdb" /srcsvrvar SRC_INDEX=public" exited with code 3.

**Comment by tmat** [comment]
:(

Can you share the build link?

**Comment by safern** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=435092&view=logs

Here are the binlogs: https://dev.azure.com/dnceng/_apis/resources/Containers/2878165?itemPath=Windows_NT_Build%20x64_Debug&$format=zip

**Comment by tmat** [comment]
Crossed fingers: https://github.com/dotnet/arcade/pull/4420

**Pull request merged**
