### PR TITLE
Modify SymStore.targets to Handle Runtime Identifiers

### PR DESCRIPTION
**Pull request by ocallesp**
Allows the tool pdb2pdb.exe to use a different output path depending on the runtime identifier.

This change is aimed at preventing conflicts that arise during parallelism when multiple runtimes attempt to write to the same output file. Prior to this modification, such conflicts would cause pipelines to fail with the error message "file '.pdb' cannot be accessed by the process because it's being used by another process".

By allowing pdb2pdb.exe to use a different output path for each runtime, we can avoid these conflicts and ensure smoother operation of our pipelines.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by dougbu** [comment]
@ViktorHofer, @tmat I defer to you for this review. See conversation in #13507 for my questions about whether symbol files for multiple runtime IDs is intended to be a supported scenario. (I'm also not sure whether the change here will enable that scenario end-to-end.)

**Comment by ocallesp** [comment]
@ViktorHofer, @tmat  Any comments on this change ?

**Comment by ViktorHofer** [comment]
@ocallesp @dougbu unfortunately, I can't help you with reviewing this change as I don't own or have knowledge on SymStore.targets. I made a few targeted contributions when something broke in dotnet/runtime because of it. I defer to @tmat for a technical review.

**Comment by ocallesp** [comment]
Hi @tmat, any comments on this PR ?

**Comment by ocallesp** [comment]
We had in internal discussion with @tmat, and we got to workaround to disable the tool with <UsingToolPdbConverter>false</UsingToolPdbConverter> and if the vs insertions fail the symbol check then we should add the assembly to a white list in VS.

**Comment by tmat** [comment]
To explain the reasoning: PDB conversion had only been necessary until Watson and WinDBG added support for Portable PDB. These tools have been updated so there is no need to public converted Windows PDBs.

The only remaining minor issue is that VS insertion use symchk tool that still hasn't been updated to support Portable PDBs. But that can be worked around by updating the list in VS for now until this tool is also updated. Arcade publishing itself ensures that PDBs have been published for any shipping binary, so the validation in VS is superfluous anyways.

**Comment by ViktorHofer** [comment]
> I'd recommend all Arcade-based repos to disable Windows PDB conversion and once that's done we can remove the conversion logic from Arcade SDK as well.

That sounds great. Would you mind opening an issue to track that work?

**Pull request closed without merging**
