### PR TITLE
Comment out native tools restore on Unix

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
NativeToolsRestore hangs on Unix that is a problem for CoreCLR. Is there any repo that is restoring native tools on Unix?

Adding `DisableNativeToolsetInstalls` around every single point that calls `buid.sh` is not very practical in CoreCLR.

**Comment by jkotas** [comment]
More context: https://github.com/dotnet/coreclr/pull/24333#issuecomment-495529038

**Comment by chcosta** [comment]
I think that disabling this is likely to break CoreFx.  @ViktorHofer ?

**Comment by ViktorHofer** [comment]
We don't use it yet but we planned to.

**Comment by chcosta** [comment]
@jkotas, is it not reasonable to define `DisableNativeToolsetInstalls ` in `./build.sh` itself before it calls into any scripts in `eng/common`?

**Comment by jkotas** [comment]
`eng/common/build.sh` is called from multiple places in CoreCLR repo. E.g. it is also called directly from https://github.com/dotnet/coreclr/blob/master/eng/build-job.yml

**Comment by jkotas** [comment]
cc @hoyosjs @sbomer

**Comment by chcosta** [comment]
This sounds fine, the only issue is that it's a breaking change so we need to send notification before we merge this change.  FYI @tmat

**Comment by ViktorHofer** [comment]
I believe we should disable it on both Unix and Windows to be consistent. CoreFx isn't a consumer yet, I don't know if anybody uses that feature yet besides coreclr in their CI.

**Comment by chcosta** [comment]
I think wpf has a dependency on native-toolset installation and would have to make changes to adapt to this change of default.  FYI @vatsan-madhavan 

I'm not certain who else is impacted.

**Comment by chcosta** [comment]
I want to help do the right thing here, but I'm not certain that I'm the right person to drive this.  @MattGal , is this something FR should handle?  I'm honestly not sure if this falls into FR duties or not.  Also, I'm not saying that I'm going to drop this on the floor, I really do want to make sure we get to a reasonable solution.  Answering this might help https://github.com/dotnet/arcade/issues/2673#issuecomment-497109079

**Comment by vatsan-madhavan** [comment]
Please hold this PR for a few days - I don't have time to assess this until sometime next week.

**Comment by chcosta** [comment]
@jkotas, is it reasonable to make this change in your repo and not take Maestro updates for a few days (or manually merge them since you'll potentially have file conflicts)?

**Comment by hoyosjs** [comment]
We already do this for the time being, and there's no automerge on coreclr. If it breaks wpf, it might be easier for us to do the usual work around as long as this gets fixed soon.

**Comment by vatsan-madhavan** [comment]
I just scanned the changes - looks like the change is to `.sh` files. WPF doesn't build on `*.nix` machines nor do we support it. We need full VS installation to build. Feel free to make this change. 

/cc @rladuca

**Comment by chcosta** [comment]
@hoyosjs , if native toolset bootstrapping is a problem, any reason not to just opt out of it entirely by removing any entries from your global.json?

**Comment by chcosta** [comment]
Also, can you point me to a specific build which is hitting a timeout / time increase so I can understand this better? Seems silly for cmake or python install to take 40+ minutes.

**Comment by hoyosjs** [comment]
> @hoyosjs , if native toolset bootstrapping is a problem, any reason not to just opt out of it entirely by removing any entries from your global.json?

We need it on Windows

> Also, can you point me to a specific build which is hitting a timeout / time increase so I can understand this better? Seems silly for cmake or python install to take 40+ minutes.

https://dev.azure.com/dnceng/public/_build/results?buildId=204225&view=logs&j=6f68b13e-5295-5453-81d9-93278bf6fe41

Or in general arcade updates before we comment that part out. Last time I started trying to dig into the issue we get to this https://github.com/dotnet/coreclr/blob/34805dc3852ba218fcfd695bc0b9eb996860e025/build-packages.sh#L129 and then we start seeing the hangs. I didn't have a particularly good setup so I couldn't try to take a look at what was causing the hang then.

**Comment by chcosta** [comment]
@hoyosjs , are you ok with holding off on making any changes here until the Coreclr failure has been investigated and is better understood?

**Comment by hoyosjs** [comment]
> @hoyosjs , are you ok with holding off on making any changes here until the Coreclr failure has been investigated and is better understood?

I tend to look at these PRs, I can do the fix if I see them. @jkotas also gets to these before I do more often than not, and he originally modified the files himself. This is a breaking change, so I know it is not easy to take in. I'm okay with working around it for a bit if it's being actively investigated.

**Comment by jkotas** [comment]
> This is a breaking change,

FWIW, I looks a this as *undoing* a breaking change. The original change that introduced the problematic behavior was a breaking change.

**Comment by hoyosjs** [comment]
It was enabled long ago in the repo toolset I believe, but that was before coreclr being moved even a bit, think June timeframe from the history I see. Back then almost no one used this - in fact even now it's rarely used. But now that there's more consumers, I can see why we shouldn't right before a preview snap if the workaround is so straightforward.

**Comment by chcosta** [comment]
@jkotas, completely agree that the previous change was a breaking change (for the record that was undoing a breaking change, originally this was enabled by default but that got lost in a refactor; so it was undoing a breaking change that was undoing another breaking change).  Sadly (or not), somewhere in the near past, we decided we should be more intentional and not callously make breaking changes.  Thanks for understanding!

**Comment by jkotas** [comment]
Superseded by https://github.com/dotnet/arcade/pull/2923

**Pull request closed without merging**
