### PR TITLE
Make sure private github repos don't do internal build things

### PR DESCRIPTION
**Pull request by AdamYoblick**

### CODE REVIEW

**Comment by AdamYoblick** [comment]
I changed the expressions to check for the build definition again because Build.Repository.Provider doesn't work even though it should.

**Comment by AdamYoblick** [comment]
@chcosta @mmitche FYI

**Comment by chcosta** [comment]
I don't think we want this in the common Arcade build scripts.  I'd roll this back to the version prior to the "Build.Repository.Providers" change.

If anything, maybe adding a parameter that allows a consumer to specify `IsPublic` and that would ensure no internal things would run even if the other conditions were met would allow you to opt out and do your own thing in winforms.  

@mmitche thoughts?

**Comment by mmitche** [comment]
@chcosta Yeah, that would work as an override.

**Comment by AdamYoblick** [comment]
Ok so while I wait on the right thing to do here, any chance I can suspend my darc arcade sdk subscription in the meantime (not sure how to do that)? My changes keep getting overwritten and our build keeps breaking because of it

**Comment by AdamYoblick** [comment]
I commented out the Microsoft.DotNet.Arcade.SDK dependency from my Version.Details.xml as a stopgap in the meantime so our "check for github in the build definition name" changes don't get blown away with every update, since this is breaking our builds.

I also reopened https://github.com/dotnet/arcade/issues/1150 since I closed that when I thought the problem was fixed when it wasn't.

**Comment by AdamYoblick** [comment]
@chcosta Is there any chance we can put this hacky solution in until Arcade has a better one, then replace it once we do? I only ask because we need some fixes that are coming in arcade (compiler support) and the arcade subscription keeps blowing away the yaml expressions which breaks private github CI builds

**Comment by markwilkie** [comment]
cc/ @riarenas @jcagme

**Comment by chcosta** [comment]
I'd prefer the override route than the hacky definition name route.

You could temporarily work around this by copying eng/common/templates into another folder (eng/fork?) and modifying your files to reference the base.yml file there with your changes.  you might also have to modify a few references in these files to refer to your copy, but that should be fairly straight-forward.

```
findstr /snip /C:"common" *yml
templates\phases\base.yml:54:    - template: /eng/common/templates/steps/telemetry-start.yml
templates\phases\base.yml:88:    - template: /eng/common/templates/steps/telemetry-end.yml
```

**Comment by AdamYoblick** [comment]
We resolved this via e-mail but I just wanted to record the conversation here. I ended up forking my common arcade yaml scripts until this is fixed properly in arcade. Thanks everyone. :)

**Comment by mmitche** [comment]
@AdamYoblick should I close this?

**Comment by AdamYoblick** [comment]
Yep this was fixed a while ago with the runAsPublic flag you guys added. :)

**Pull request closed without merging**
