### PR TITLE
Squash merge all auto merged PRs

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by mmitche** [comment]
@alexperovich We won't want this behavior for speculative flow builds, but this should be fine since it's configurable.

**Comment by sharwell** [comment]
❓ Does this (eventually) apply to things like branch merges we have in roslyn?

❓ How does a user opt-out of this behavior (my PRs are never to be squashed, so I would need to understand how this change would potentially affect my work if it's something that applies to repositories that *use* arcade as opposed to just something used by people working on arcade itself).

**Comment by alexperovich** [comment]
This applies to PRs that are created by Maestro++ for dependency updates. They can be auto-merged if policy allows and will be squashed if so.

**Comment by alexperovich** [comment]
And example PR is this one https://github.com/dotnet/arcade-minimalci-sample/pull/20

**Comment by sharwell** [comment]
Sorry for the red X (blocking), didn't realize I had commit access here so I was expected gray X (non-blocking).

**Pull request merged**
