### PR TITLE
Upgrade Arcade to a 5.0 SDK

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/arcade/issues/5394

To support the net5.0 TFM change we need to update the SDK for a newer NuGet.

### CODE REVIEW

**Comment by markwilkie** [comment]
This makes sense to me, but running it by @mmitche and @jaredpar as well as I might be missing something.

**Comment by riarenas** [comment]
Should we move to the latest released SDK? 
https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md#net-sdk--managed-toolset

mentions staying on the latest released preview (which we also haven't done), but also mentions moving to a non-released one should come with approval from tactics.

**Comment by ViktorHofer** [comment]
We can downgrade to a officially released P2 or P3 build. Picked the latest nightly build as it includes some VSTest features that might be useful for https://github.com/dotnet/arcade/pull/5347 (ie specifying a default filter in the .runsettings file, pointing to a custom dotnet host and not swallowing build output during VSTest).

**Comment by ViktorHofer** [comment]
@swaroop-sridhar can you please take a look at the .deps.json build failures? Looks related to https://github.com/dotnet/aspnetcore/pull/21017#issuecomment-619751460. cc @dougbu

**Comment by dougbu** [comment]
I suppressed NU5118 warnings because figuring out the root cause was going to take too much time. An actual fix would be great.

**Comment by ViktorHofer** [comment]
My lead is that https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L196 might be interfering.

**Comment by ViktorHofer** [comment]
ping @swaroop-sridhar

**Comment by mmitche** [comment]
This is sending warning bells that we may have attempted this before and decided against it.  Maybe @jaredpar remembers?

**Comment by swaroop-sridhar** [comment]
> ping @swaroop-sridhar

I posted a PR for the PublishDepsFilePath setting https://github.com/dotnet/sdk/pull/11462 
PublishDepsFilePath is also used by the packing targets, so it does seem related to the issue.

**Comment by ViktorHofer** [comment]
@swaroop-sridhar the failures are still the same with the new SDK.

**Comment by ViktorHofer** [comment]
The error goes away if I comment out all the PackageReferences used during the build.

**Comment by ViktorHofer** [comment]
Submitted a fix to the SDK: https://github.com/dotnet/sdk/pull/11522

**Comment by ViktorHofer** [comment]
@markwilkie this should be ready now. Can we clarify if we are fine upgrading to a preview5 SDK? IMO it shouldn't be an issue.

**Comment by dougbu** [comment]
See also the breaks we hit in https://github.com/dotnet/aspnetcore-tooling/pull/1692#issuecomment-622548274 and https://github.com/dotnet/aspnetcore-tooling/pull/1692#issuecomment-622548274. Discussion about the second problem continues in my dotnet/sdk#11527 PR.

**Comment by dougbu** [comment]
Oops, forgot about incorrect NU5129 warnings I commented on at https://github.com/dotnet/aspnetcore/pull/21017#issuecomment-616772747 and today at https://github.com/dotnet/aspnetcore/pull/21017#issuecomment-622458708 with responses later from @rrelyea.

**Comment by dougbu** [comment]
For the https://github.com/dotnet/aspnetcore/pull/21017#issuecomment-622491248 break, my dotnet/sdk#11527 PR is on hold for further discussion. Repos other than dotnet/aspnetcore that adjust .deps files may need to adjust as I did in https://github.com/dotnet/aspnetcore/pull/21017/commits/3ef5452bcf5b6d0ef4b116d1892f0bae5229017d i.e. run their rewrite target later or use `$(IntermediateDepsFilePath)` instead of `$(PublishDepsFilePath)`.

**Comment by ViktorHofer** [comment]
@markwilkie I downgraded to the official preview3 released version which should be less controversial. I want to get this in as it blocks the build promotion.

**Comment by markwilkie** [comment]
Makes sense @ViktorHofer.  If @mmitche, @Pilchie and @jaredpar are good with this, I am too.  An email head's up to tactics is probably in order too, especially given the noise.

Adding @missymessa as we'll hopefully be able to promote today and it sounds like you need this in soon.

**Comment by Pilchie** [comment]
Yes, I'm good with this.

**Comment by ViktorHofer** [comment]
Approved by Tactics - merging.

**Pull request merged**
