### PR TITLE
Fix image name for validate sdk

### PR DESCRIPTION
**Pull request by MattGal**
https://github.com/dotnet/arcade/issues/7873

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by MattGal** [comment]
overriding policy to unbreak build

**Comment by mmitche** [comment]
> overriding policy to unbreak build

:D 
```
Unbreak the build,
Say you'll merge me again,
...
```

**Comment by MattGal** [comment]
``` 
Undo the commit you caused
When I signed off on it before
And let it merge a long
Re-set the admin policy
I watch so many builds
Un-break my build...
My build... 
```

**Comment by ericstj** [comment]
https://www.youtube.com/watch?v=p2Rch6WvPJE

Never watched this before, but it's quite entertaining. I'm trying to imagine the two of you playing twister.

**Comment by MattGal** [comment]
oh my.  I hadn't seen the video either despite being a 90's kid, my first reaction was "there's no way that accident was fatal!"

**Comment by missymessa** [comment]
What I've learned from this thread is that breaking the build = getting into an accident with your motorcycle.

**Comment by mmitche** [comment]
> What I've learned from this thread is that breaking the build = getting into an accident with your motorcycle.

Also, it's not exactly like he actually caused intentional hurt there. He literally just got hit by a car.

**Pull request merged**
