### PR TITLE
Use containers, also use phases level variables

### PR DESCRIPTION
**Pull request by chcosta**
I'm not certain if phases level variables are supported yet in dotnet.vs.com.

### CODE REVIEW

**Comment by chcosta** [comment]
Latest update is that the "containers" feature isn't yet available for dotnet.visualstudio.com. =(

**Comment by chcosta** [comment]
official docker support does not yet appear to be available in dotnet.visualstudio.com.

**Comment by chcosta** [comment]
official docker support does not yet appear to be available in dnceng.visualstudio.com.

**Comment by jonfortescue** [comment]
@chcosta that's great news!

**Pull request merged**
