### PR TITLE
Add blurb on authorizing access to variable groups

### PR DESCRIPTION
**Pull request by garath**
In response to dotnet/core-eng#7812, add a note in Onboarding that variable groups must be authorized through a manually-queued build before they may be used in automatic builds.

### CODE REVIEW

**Comment by chcosta** [comment]
Authorization model is different between dnceng and devdiv accounts.  Initially, there was too much friction associated with authorization and thus changed how dnceng handled authorization.  We should either revisit that decision now that authorization has matured a bit, or note that this specific point is not applicable to dnceng.

**Comment by garath** [comment]
@chcosta Do you view the no-need-to-authenticate as an exception or as the norm? Also, how is that set? The variable group configuration does not have "allow access to all pipelines" ticked.

**Comment by chcosta** [comment]
doc only changes don't cause Azure DevOps builds to trigger.  You'll never get CI results for them.

**Pull request merged**
