### PR TITLE
Signtool netcoreapp21

### PR DESCRIPTION
**Pull request by chcosta**
This is fallout from https://github.com/dotnet/arcade/pull/6181

Validating with https://dnceng.visualstudio.com/internal/_build/results?buildId=818297&view=results.  I'll wait until I get this through arcade-validation testing before merging

### CODE REVIEW

**Review by riarenas — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
FYI There may be places scattered throughout the entire .NET ecosystem that have these frameworks hardcoded.

**Comment by chcosta** [comment]
FYI @ViktorHofer

**Comment by ViktorHofer** [comment]
Thanks for fixing this. I just noticed this myself and was going to submit a PR. I updated your PR, there was one more file that needed an update.

**Review by ViktorHofer — APPROVED** [review]

**Comment by chcosta** [comment]
Validated public builds - https://dev.azure.com/dnceng/public/_build/results?buildId=818452&view=results
Validated internal builds - https://dev.azure.com/dnceng/internal/_build/results?buildId=818424&view=results

will merge after ci completes

**Pull request merged**
