### PR TITLE
Updating documentation for localizing servicing branches

### PR DESCRIPTION
**Pull request by AbhitejJohn**
Updating the docs to include the steps to add a servicing branch and enable loc parsing of it.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by AbhitejJohn** [comment]
Tagging @jonfortescue  and @cristianosuzuki77 for review.

**Review by jonfortescue — APPROVED** [review]
Looks great to me. Thank you so much for writing this!

**Comment by AbhitejJohn** [comment]
@jonfortescue : I dont really have access to merge, so I'm hoping a maintainer could do that for me.

**Comment by jonfortescue** [comment]
@AbhitejJohn done!

**Pull request merged**
