### PR TITLE
Enable SxS support for preview workload manifests

### PR DESCRIPTION
**Pull request by joeloff**
Enable SxS installs of different previews for workload manifests within the same feature band. Previously, manifest installers within the same band were upgradeable.

Manifest packages can now include prerelease information in the package ID, e.g. `Microsoft.NET.Workload.Emscripten.Manifest-6.0.100-preview.1` and `Microsoft.NET.Workload.Emscripten.Manifest-6.0.100-preview.2` will generate installers that are not upgrade related.

### CODE REVIEW

**Comment by joeloff** [comment]
@mmitche This is related to 7.0 features that we want for the first preview I mentioned in tactics

@pjcollins @jonathanpeppers as an FYI

@lewing in case emsdk/mono wants to leverage this.

**Comment by joeloff** [comment]
gentle ping

**Comment by riarenas** [comment]
I don't think I have enough context on this project to be able to review this code.

**Review by dsplaisted — APPROVED** [review]
How will a repo producing workload manifests consume this?  Will it automatically start creating side-by-side manifests for different feature bands?  How will they override the prerelease version if they want to (for example if they want to remove the prerelease label from the workloads near RC)?

**Comment by joeloff** [comment]
@dsplaisted When consuming the tooling, if they drop the prerelease part of the manifest version we'll start producing stable values. There are two options. One is if the package given to the task contains the value in the package ID itself like most repos do. But alternatively, they can provide the explicit version, e.g. 7.0.100-preview.2 as a task parameter too. The tooling will give preferences to an explicit version and when absent, try to extract it from the package ID.

**Pull request merged**
