### PR TITLE
Start consuming the latest portable IBCMerge

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Comment by tmat** [comment]
Was the new implementation tested on Roslyn? Did it produce exactly the same data as the previous version?

**Comment by MichalStrehovsky** [comment]
> Was the new implementation tested on Roslyn? Did it produce exactly the same data as the previous version?

@davidwrighton is the code path that compares the outputs of old and new logic on Win32 enabled in this package? With that, it auto-validates.

**Comment by davidwrighton** [comment]
I was not tested on Roslyn. The validation code path is enabled by running IbcMerge with the -md:both command line switch

**Comment by MichalStrehovsky** [comment]
@tmat Any concerns if I add that parameter (to ensure continuous validation) and after a bit bake time, we remove it?

**Comment by davidwrighton** [comment]
One thing to be aware of the additional validation path adds a few junk files to the directory of the file being modified. This hasn't been a problem in other test environments, but we haven't used it in an official build of any sort.

**Comment by tmat** [comment]
@MichalStrehovsky Sounds good. When you do so, file an issue and include it in a comment.

**Comment by tmat** [comment]
> a few junk files to the directory of the file being modified.

Oh, we can't have that. If temp files are needed, they should be created in the TEMP dir.

**Comment by MichalStrehovsky** [comment]
> Oh, we can't have that. If temp files are needed, they should be created in the TEMP dir.

Okay, I'll re-test with Roslyn repo. I assume we don't have better way to do this kind of testing than to hack the local NuGet package cache and hope I'm running with the bits that I think I'm running.

(Cc @sergiy-k @RussKeldorph)

**Comment by MichalStrehovsky** [comment]
I can't even get a baseline for Roslyn:

```
  Downloading optimization data from service https://devdiv.artifacts.visualstudio.com, drop OptimizationData/dotnet/ro
  slyn/dev16.0-vs-deps/20190323.2/284932/1
D:\git\roslyn\.dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5):
 error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower
, or use a version of the .NET SDK that supports .NET Core 3.0. [D:\git\roslyn\src\Compilers\CSharp\Test\Symbol\Microso
ft.CodeAnalysis.CSharp.Symbol.UnitTests.csproj]
```

I tried `git clean -dfx` and wiping my nuget cache, but it didn't help. I'll try another machine, but having to retest Arcade changes in each repo that consumes Arcade is kind of a time sink. Would be nice if Arcade provided means to test with all clients in the CI. It would also prevent things like #2198 disabling IBC in CoreFX by accident (that one probably wasn't tested there for a change).

**Comment by MichalStrehovsky** [comment]
Confirmed no diffs for Roslyn with 5.0.4-beta-19179.1

**Comment by tmat** [comment]
@jaredpar

**Comment by jaredpar** [comment]
@MichalStrehovsky were you able to test Roslyn locally? The latest message on that showed an error.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky were you able to test Roslyn locally? The latest message on that showed an error.

Yes, Roslyn repo build worked on a different machine.

**Comment by jaredpar** [comment]
Curious: do we have implicit roll forward enabled for ibcmerge? Today this will only work when the repository has a 2.1 runtime installed. Not guaranteed. Need to ensure it can implicitly roll forward for this to be usable.

**Comment by tmat** [comment]
I think it would be better if we used IBCMerge as a build task instead of running an .exe

**Comment by davidwrighton** [comment]
Implicit roll forward enabled in package 5.0.5-beta.19202.1

**Comment by davidwrighton** [comment]
Actually, sorry, did it wrong, It'll be a version 5.0.6 which has it properly enabled.

**Comment by davidwrighton** [comment]
In particular, version 5.0.6-beta.19203.1

**Comment by MichalStrehovsky** [comment]
Okay, re-validated with 5.0.6-beta.19203.1 and everything still looks good. This should be good to merge once the CI is green.

Thank you David!

**Pull request merged**
