### PR TITLE
[release/7.0] Add Arcade templates compatible with the 1ES pipeline templates

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/arcade/issues/14524

Adds templates compatible with the 1ES PT schema.

This PR has two commits to hopefully help reviewers:
* https://github.com/dotnet/arcade/commit/70e78f8ff32f78ba531758d7cb245fc2313d1a49 has the changes to the templates
* https://github.com/dotnet/arcade/commit/7c7b1ae680b9519ad55742a75e578533844183de adds back the eng/common/templates so that we don't delete anything by mistake.

Testing in this build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2410177&view=results

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
not much to review but&hellip;

**Comment by dougbu** [comment]
note validation build only partially succeeded due to SBOM issues. is the "Frankenbuild" holding these files wrong❔

**Comment by riarenas** [comment]
I'm seeing the sbom issues in other places. I think it's an outage of the signing service. I'll check it in the morning.

https://github.com/dotnet/arcade/commit/70e78f8ff32f78ba531758d7cb245fc2313d1a49 might be easier to review to at least see the differences between these new ones and the existing templates.

**Comment by dougbu** [comment]
> [70e78f8](https://github.com/dotnet/arcade/commit/70e78f8ff32f78ba531758d7cb245fc2313d1a49) might be easier to review to at least see the differences between these new ones and the existing templates.

yup, the deleted files were confusing but that commit otherwise looks good. I stand by my approval 😀

**Comment by riarenas** [comment]
> note validation build only partially succeeded due to SBOM issues. is the "Frankenbuild" holding these files wrong❔

I see it happening in other places such as in https://github.com/dotnet/dnceng/issues/2324. So I'm pretty convinced this isn't an issue with these templates. I queued a new build just in case: https://dnceng.visualstudio.com/internal/_build/results?buildId=2410578&view=results

**Review by chcosta — APPROVED** [review]

**Comment by riarenas** [comment]
Will monitor this as it goes through validation and will let folks know when they are available via Maestro

**Pull request merged**
