### PR TITLE
Migrate docs from core eng

### PR DESCRIPTION
**Pull request by adiaaida**
This migrates various directories of docs from core-eng to arcade including:

* Maestro
* One-Pagers (Moved into the team process directory)
* Operations
* Policy
* Project-Docs
* Staging-Pipeline
* Validation

If you believe there are any other directories in the core-eng Documentation directory that should be migrated over, please let me know.

If you think any of these docs shouldn't be migrated, also please make a note.

This PR will preserve the doc history as part of the migration (if the majority/vocal majority believes that we don't need to preserve the history, I will squash commit).

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
Looks complete, I obviously did not  actually read everything.

I'd prefer a squash merge, there's a lot of useless history in the commits.

**Comment by adiaaida** [comment]
Directories skipped as part of this:

* Arcade-Pool-Provider
* CodeTrust
* DevGuide (already migrated, in TeamProcess/DevGuide)
* Helix-Clients
* Helix-Server-Side
* OSOB
* Orchestrated-Build
* PipeBuild
* Retrospectives (these are in one note)
* Rollout-Scorecards (@jonfortescue on if/how we want to preserve the old scorecards)
* Secret-Management
* Security
* Service-Fabric
* Tools (this was a lot of really old tools)
* images
* Anything in the main Documentation directory, not in a subdirectory.

All of these have already been migrated to the azdo wiki for dnceng. If we think they are useful as living documents (ie will be changed going forward), I can add them.

**Comment by ChadNedzlek** [comment]
The "project-docs" have a lot of crusty stuff... should we skip those too?

Also, if we are going to make this public, we might want to change the name of "Kusto" to "Azure Data Explorer", since that's the brand name of it.

**Comment by adiaaida** [comment]
@ChadNedzlek  I can make that change. I couldn't tell how much of Project-Docs was crusty and how much wasn't. It's got some stuff in it that is current and some stuff that is old. I don't mind skipping it.

**Comment by ChadNedzlek** [comment]
If there is useful stuff in there, keeping it is fine. We can always delete them later.

**Review by mmitche — APPROVED** [review]

**Comment by RussKie** [comment]
The images referenced in https://github.com/dotnet/arcade/tree/main/Documentation/Validation appears to have been lost. Looks like [this folder](https://github.com/dotnet/core-eng/tree/main/Documentation/Validation/Images) wasn't copied across.

**Comment by ChadNedzlek** [comment]
Sort of feels like that doc shouldn't be in arcade, since it's very specific to our services (a fairly large amount of what it says doesn't apply to arcade).

**Comment by missymessa** [comment]
Agreed. The validation documentation was created with the dnceng team in mind for the services we own and maintain.

**Comment by RussKie** [comment]
...then the docs (obsolete or otherwise irrelevant) should be removed?
Right now it's in a broken state.

**Comment by ChadNedzlek** [comment]
There is an entire epic around making sense of our docs that @ilyas1974 is working on. This can be handled as part of that. I can't image this is the only document that is either broken or nonsensical to the general users of arcade (or both).

**Comment by RussKie** [comment]
No worries then. 
I just had an unforgettable experience getting XUnit to produce Cobertura code coverage using the Aracde SDK, and that's how I come across this page and the missing images.

**Pull request merged**
