### PR TITLE
Exclude _.pdb files from BinSkim scan.

### PR DESCRIPTION
**Pull request by andriipatsula**
Certain PDBs causing Binskim to behave unexpectedly and crash with Out of memory exception. https://github.com/dotnet/arcade-services/issues/2744

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by andriipatsula** [comment]
Tested: https://dev.azure.com/dnceng/internal/_build/results?buildId=2225970&view=results

**Comment by MilenaHristova** [comment]
Is this excluding all pdb files?

**Comment by andriipatsula** [comment]
> Is this excluding all pdb files?

Nope, just `_.pdb` files

**Comment by andriipatsula** [comment]
> > Is this excluding all pdb files?
> 
> Nope, just `_.pdb` files

concreate example: [runtime.linux-arm.Microsoft.NETCore.ILDAsm](https://dnceng.visualstudio.com/public/_artifacts/feed/darc-pub-sym-dotnet-runtime-4bc0fe95/NuGet/runtime.linux-arm.Microsoft.NETCore.ILDAsm/overview/7.0.10-servicing.23363.10) runtime.linux-arm.Microsoft.NETCore.ILDAsm 7.0.10-servicing.23363.10 \runtimes\linux-arm\native\_.pdb

**Comment by MilenaHristova** [comment]
> > > Is this excluding all pdb files?
> > 
> > 
> > Nope, just `_.pdb` files
> 
> concreate example: [runtime.linux-arm.Microsoft.NETCore.ILDAsm](https://dnceng.visualstudio.com/public/_artifacts/feed/darc-pub-sym-dotnet-runtime-4bc0fe95/NuGet/runtime.linux-arm.Microsoft.NETCore.ILDAsm/overview/7.0.10-servicing.23363.10) runtime.linux-arm.Microsoft.NETCore.ILDAsm 7.0.10-servicing.23363.10 \runtimes\linux-arm\native_.pdb

I see, thanks

**Review by MilenaHristova — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Pull request merged**
