### PR TITLE
Update to RC2

### PR DESCRIPTION
**Pull request by ViktorHofer**
Same as https://github.com/dotnet/arcade/commit/858c0110f88f026a24be2d2c7aff08666ff9b615 for RC1

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Interesting failure. Global tool restore is failing.

**Comment by riarenas** [comment]
> Interesting failure. Global tool restore is failing.

This rings a bell, let me try and find it.

**Comment by mmitche** [comment]
I think we should skip to a newer RTM version then

**Comment by ViktorHofer** [comment]
Agreed this is a significant breaking change. Should we just skip to a recent unsigned SDK build then? Any preference?

**Comment by mmitche** [comment]
> Agreed this is a significant breaking change. Should we just skip to a recent unsigned SDK build then? Any preference on which version? The fix for that issue was merged in four days ago: [dotnet/sdk#35884](https://github.com/dotnet/sdk/pull/35884)

I would go with latest. 8.0.100-rtm.23506.1. It should be signed and will have the fix.  aspnetcore: 8.0.0-rtm.23502.22

**Review by mmitche — APPROVED** [review]

**Pull request merged**
