### PR TITLE
[release/6.0] Remove sleet and (some) tendrils

### PR DESCRIPTION
**Pull request by mmitche**
This is a slightly less expansive version of the main refactoring that removed sleet. I attempted to port that, but it's more extensive and I am more risk averse in 6.0/7.0. This basically removes the sleet reference, then NYIs the codepaths leading to it.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
Should resolve https://github.com/dotnet/arcade/issues/14105

**Comment by mmitche** [comment]
Official build is CG clean https://dev.azure.com/dnceng/internal/_build/results?buildId=2288762&view=results

**Review by riarenas — APPROVED** [review]
Where's the party parrot when you need it

**Comment by dougbu** [comment]
gotta love a widespread cleanup 😁
image
🎉

**Comment by dougbu** [comment]
this also resolved dotnet/dnceng#674. I'll close that ant link to this PR 😀

**Comment by mmitche** [comment]
If we hit these NYIs in a 6/7 branch then we have more work to do. But I don't think we will.

**Pull request merged**
