### PR TITLE
Always publish latest links

### PR DESCRIPTION
**Pull request by alexperovich**
#8312

### CODE REVIEW

**Review by riarenas — APPROVED** [review]

**Comment by mmitche** [comment]
@alexperovich Won't this end up with non-deterministic behavior for any channels that are publishing to both dotnetbuilds and dotnetcli right now?

**Comment by alexperovich** [comment]
it will be last wins, so it will be deterministic.

**Comment by alexperovich** [comment]
actually, no they are all done in parallel so it won't be the same every time. Is it worth the extra complication though? We aren't going to be dual publishing for much longer.

**Comment by mmitche** [comment]
> actually, no they are all done in parallel so it won't be the same every time. Is it worth the extra complication though? We aren't going to be dual publishing for much longer.

I'm not explicitly opposed to it, but
- How much longer?
- Are there any other issues could we see with the race condition? Any failures in publishing?

**Comment by alexperovich** [comment]
I have everything in place to swap over .net 6 to dotnetbuilds only, I just have to make that change and let it flow.

It won't cause any issues with publishing other than the aka.ms link pointing to whichever one finishes last.

**Review by mmitche — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Pull request merged**
