### PR TITLE
Improve publishing logging.

### PR DESCRIPTION
**Pull request by JohnTortugo**
Closes: #469 

Changes:

- PushToBlobFeed.cs:
  - Add log message with the name of the item being uploaded.

### CODE REVIEW

**Comment by chcosta** [comment]
Do you have a sample build you used to validate that you can link to?

**Comment by jcagme** [comment]
I think we could also change the verbosity of the logs (I don't think we are setting it so it just logs `MessageImportance.High` messages). 

For example, when we push to the blob feed there are no logs in Arcade, but in other build definitions where we verbosity is set (`Verbosity=diag`) we can see all the Sleet logging. See "Packages -> Blob feed of https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=1975978

**Comment by chcosta** [comment]
In the build def you linked to, the verbosity is set to diag for the file logger

```
/fileloggerparameters:Verbosity=diag;LogFile=publishpkg.log
```

What's being displayed there is not a diag log.  I think that dumping the diag log to the console would be too much and would cause the UI to lag substantially behind the actual build process.

I assume that what's displayed in the output of that build def is just something provided by the coreclr build in publish.proj (I haven't looked to see what's controlling the output there), and I think we should have a similar base level of verbosity here (regardless of file logging).  

Side note, they should change their diag file logging to a binlog which is faster, easier to navigate, and captures a similar level of diagnostic logging.  I assume they'll get binlogging once they move to Arcade SDK which supports binlogs.

**Comment by jcagme** [comment]
Right, found that they define the verbosity like:

https://github.com/dotnet/coreclr/blob/master/build.cmd#L488
https://github.com/dotnet/coreclr/blob/master/config.json#L73
https://github.com/dotnet/coreclr/blob/master/config.json#L776

**Comment by chcosta** [comment]
That appears to be all related to file logging as well.

**Comment by JohnTortugo** [comment]
I think that if you change the verbosity level you'll end up getting much more messages than you want.

> Do you have a sample build you used to validate that you can link to?

I'll work on that later and post here the link.

**Comment by jcagme** [comment]
> That appears to be all related to file logging as well.

Do you know what do we need to set to log to console but not to file? All the examples that I find use `/flp`

**Comment by jcagme** [comment]
> I think that if you change the verbosity level you'll end up getting much more messages than you want.

Yes but also, currently, when pushing to blob feed for example we only log:

```Performing feed push...
Creating container named 'dotnet-core' in storage account dotnetfeed.
```

Which is fine but does not provide much details about what was pushed or if something failed.

**Comment by chcosta** [comment]
Probably related to 

https://github.com/dotnet/coreclr/blob/master/config.json#L788
https://github.com/dotnet/coreclr/blob/master/config.json#L351

In general for msbuild it's `/v:` or `/verbosity:` that controls verbosity.  I believe that console is the default logger and then you can toggle different logs using things like `/flp` for file logger.  To explicitly change the console logger only you would use `/clp`

https://msdn.microsoft.com/en-us/library/ms164311.aspx

**Comment by jcagme** [comment]
Sweet! Thanks for sharing this info, super useful since I did not know about clp!

**Comment by JohnTortugo** [comment]
> Do you have a sample build you used to validate that you can link to?

What is the best way to do that? How do I test it without actually publishing the package?

**Comment by chcosta** [comment]
What's wrong with publishing the package?  If you are in sync with master in your branch, it shouldn't really matter.  you can just push to a branch in VSTS and then use the official build definition to build / publish from that branch.

**Comment by JohnTortugo** [comment]
I talked to @jcagme and he's going to include this in one of this PR's since we would likely bump into problems when updating global.json to test newest version of SDK and Feed+Sleetlib+Newtonsoft.Json issues.

**Pull request closed without merging**
