### PR TITLE
Use newer SleetLib version

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/core-eng/issues/7551

Use newer version of SleetLib. This new version compares the content of the files in cases when we are attempting to publish a package that is already on the feed. If the contents are different the operation fails.

### CODE REVIEW

**Comment by markwilkie** [comment]
Where are we still using sleet these days?

**Comment by riarenas** [comment]
We still always publish product packages to the dotnet-core feed, and it's the feed that most repos are restoring packages from. 

It's something we want to stop doing and instead rely on the dotnetx and dotnetx-transport azure feeds that the builds are also publishing to, but I don't think we can flip the switch to have everyone restore from those feeds yet without generating a lot of noise.

**Comment by rainersigwald** [comment]
Is there a chance of porting this to the .NET Tools 3 feed? MSBuild's primary target is VS, so we're not comfortable moving to Arcade 5 while we're shipping in VS 16.5/SDK 3.1.200 and friends. But for the same reason we'd really like to be able to publish our very latest bits to 3.1 _and_ 5.0.

**Comment by markwilkie** [comment]
Putting my "toolset glasses" on....grin, is it really true that msbuild should be shipping latest bits to 3.1 @rainersigwald ?  Currently our guidance is that we would only take targeting changes on a case-by-case bases.  (https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md)  

However, perhaps there are good reasons to take latest?  Basically, I'd like to understand better...

**Comment by mmitche** [comment]
> Is there a chance of porting this to the .NET Tools 3 feed? MSBuild's primary target is VS, so we're not comfortable moving to Arcade 5 while we're shipping in VS 16.5/SDK 3.1.200 and friends. But for the same reason we'd really like to be able to publish our very latest bits to 3.1 _and_ 5.0.

@rainersigwald I **think** the right thing to do here is to use the new tools channels that are getting added. The point being is that when you're doing a build for VS, it needs to go into every version of the SDK that would go into that version of VS.

**Comment by rainersigwald** [comment]
cc @livarcocc. Yes, historically we've tried to match MSBuild-via-VS (always updated) with MSBuild-via-SDK-via-VS. That minimizes surprises between VS build/`msbuild.exe` and `dotnet build`.

**Comment by markwilkie** [comment]
@livarcocc / @Pilchie  - thoughts on msbuild being latest for 3.1/16.x and our current toolset policy?  Seems there might be some additional clarification that should occur.

**Comment by Pilchie** [comment]
I think the point is that for msbuild, it's "latest" is actually latest servicing for 3.1 anyway, they don't take a dependency on .NET 5 there because they need to insert into VS which only has 3.1.  I'm not sure how to word that, but I'm in favor of @rainersigwald's point.

**Comment by markwilkie** [comment]
@rainersigwald - you cool w/ using the new tools feed https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json ?  This way sleet is entirely out of the picture which is good.

@mmitche - will this break other folks downstream or is this new feed already everywhere?

**Comment by rainersigwald** [comment]
@markwilkie I'm fine switching feeds, but it looks to me like that feed is dead; I had to switch off of it to take a recent arcade 1.0 update: https://github.com/microsoft/msbuild/pull/4920/files#diff-a7c26590e27fcbb61c69ff2564beb1faL6

**Comment by markwilkie** [comment]
I might have got the feed wrong....  @mmitche - what's the right tools feed to use?

**Comment by mmitche** [comment]
dotnet-eng is the new tools feed.  dotnet-tools is the future home of actual .net core tooling.

**Pull request merged**
