### PR TITLE
[.NET 9] Remove UsingToolMicrosoftNetILLinkTasks switch

### PR DESCRIPTION
**Pull request by ViktorHofer**
Blocked by https://github.com/dotnet/runtime/pull/91468

This shouldn't be merged into main as long as Arcade targets .NET 8.

Runtime was the only consumer of that switch and we now use the live built asset instead. Also, the linker is now in-built into the .NET SDK and doesn't need to be referenced explicitly anymore.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@mmitche when should we expect Arcade to branch-off so that we can get this change merged?

**Comment by mmitche** [comment]
> @mmitche when should we expect Arcade to branch-off so that we can get this change merged?

I may be recalling incorrectly, but I think @dkurepa was going to work on this sometime soon?

**Comment by dkurepa** [comment]
I don't think we talked about this, but I could work on this

**Comment by mmitche** [comment]
> I don't think we talked about this, but I could work on this

Maybe that was someone else. @tkapin did I talk to you about this?

**Comment by tkapin** [comment]
@mmitche - I don't this so, this doesn't ring a bell.

**Pull request merged**
