### PR TITLE
Use 1ES pools in templates that run internally

### PR DESCRIPTION
**Pull request by mmitche**
- Use the 1ES pools in our templates, jobs, etc.
- To reduce some of the cost of this, remove the "Setup Maestro Vars" job and replace with a step so that we don't end up with an additional allocation in those cases.
- Clean up some unused variables from the common variables.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
It looks like a _little_ more than just moving to 1ES but I don't see anything terrifying.

**Comment by mmitche** [comment]
@adiaaida Are any of these templates used in dotnet-release in odd ways?

**Comment by adiaaida** [comment]
Nope, I don't believe so. We're so specialized that we've basically rewritten most of the templates we could be using from arcade

**Comment by garath** [comment]
> To reduce some of the cost of this, remove the "Setup Maestro Vars" job and replace with a step so that we don't end up with an additional allocation in those cases.

So I'm clear, this is because as a job it spins up yet another instance, but as a step it just runs inline?

**Comment by mmitche** [comment]
> > To reduce some of the cost of this, remove the "Setup Maestro Vars" job and replace with a step so that we don't end up with an additional allocation in those cases.
> 
> So I'm clear, this is because as a job it spins up yet another instance, but as a step it just runs inline?

Correct. We used the job to communicate info about a build cross-stage and cross-job, because it was convenient. But a step works just as well and doesn't involve a new machine.

**Review by riarenas — APPROVED** [review]
We should have a test build that executes the publishing using these templates to make sure the set up for the maestro vars is fine. (the linked build skipped the publish job) But this LGTM

**Comment by mmitche** [comment]
> We should have a test build that executes the publishing using these templates to make sure the set up for the maestro vars is fine. (the linked build skipped the publish job) But this LGTM

There is a tweak needed to the SDL job. I also found a repo (arcade pool provider) that is calling it explicitly, and this will break it, but since we're shutting that down, that's okay.

**Comment by mmitche** [comment]
Validation builds:
- Templating (runs SDL and other validation) - https://dev.azure.com/dnceng/internal/_build/results?buildId=1561139&view=results
- Installer - https://dev.azure.com/dnceng/internal/_build/results?buildId=1561142&view=results
- Aspnet - https://dev.azure.com/dnceng/internal/_build/results?buildId=1561146&view=results
- Runtime - https://dev.azure.com/dnceng/internal/_build/results?buildId=1561157&view=results
- Arcade - https://dev.azure.com/dnceng/internal/_build/results?buildId=1560876&view=results

**Pull request merged**
