### PR TITLE
[release/7.0] Update production branch pattern for CG

### PR DESCRIPTION
**Pull request by wtgodbe**
Backport of https://github.com/dotnet/arcade/pull/13323 + https://github.com/dotnet/arcade/pull/13264

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
The test failure is because of #13337

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
@dougbu @mmitche am I good to merge this?

**Comment by dougbu** [comment]
> @dougbu @mmitche am I good to merge this?

yes 😀

**Pull request merged**
