### PR TITLE
Add tests of `PushToAzureDevOpsArtifacts`

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by mmitche** [comment]
There's actually already a set of tests for the feed task here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed.Tests

Can you add the tests there instead of a new project?

**Comment by dougbu** [comment]
@mmitche I added the new class in src/Microsoft.DotNet.Build.Tasks.Feed.Tests/ I also made a small change to the project file but didn't create a new project.

The main issue at the moment is I did my testing in VS and that doesn't match the Helix environment the tests usually executed in.

**Comment by jonfortescue** [comment]
@dougbu @mmitche Tests seem to be failing on this. Is it still something we want to be merged?

**Comment by dougbu** [comment]
@jonfortescue I'd love to merge this but have been focused on #4585 and my day job. It's also not clear to me how to get these tests running correctly; the Helix intricacies here aren't an area I've got much experience. Any help on fixing this up would be **much** appreciated❕❕

**Comment by JohnTortugo** [comment]
I'm working sporadically on this. You can close the PR if you want @dougbu - I've a copy of your branch and I'm doing the work on it.

**Comment by dougbu** [comment]
Feel free to update my branch. Or, if you prefer I close this PR, please CC me when you fix things.

Either way, thanks very much for your help. I look forward to seeing how I really should have written the tests. (They pass locally but not in Helix last I checked.)

**Comment by JohnTortugo** [comment]
I prefer to close the PR :-). I'll ping you in the new one.

**Pull request closed without merging**
