### PR TITLE
Move to using .NET Core 2.1 RTM SDK

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by eerhardt** [comment]
Any reason this wasn't `2.1.301` (the latest released version)?

**Comment by weshaggard** [comment]
@dleeapho @dseefeld I assume there isn't any reason we cannot move to the RTM SDK in source-build for 2.1.1/2.1.2 now correct?

**Comment by dseefeld** [comment]
Moving to RTM SDK should be fine.  We've moved release/2.1, but we haven't got that change into master, yet.  See https://github.com/dotnet/source-build/issues/617

**Comment by jaredpar** [comment]
@dseefeld when will the file in master be updated? We're trying to find a simple way to determine the LKG. Nice if this file represents the actual LKG we can use in our repos.

**Pull request merged**
