### PR TITLE
Remove Packaging package.

### PR DESCRIPTION
**Pull request by JohnTortugo**
Closes: #584 

To prevent confusion we are going to remove this package from Arcade for now. Depending on what is decided during work on Epic #578 we might bring it back.

### CODE REVIEW

**Comment by JohnTortugo** [comment]
I intend to close this by EOD today if no one objects.

**Comment by weshaggard** [comment]
@JohnTortugo @markwilkie why did we need to remove this from arcade? We still need it here as it is part of moving out of BuildTools?

**Comment by markwilkie** [comment]
The idea is that this work is covered by https://github.com/dotnet/arcade/issues/578

**Comment by weshaggard** [comment]
Well we already took one step in that direction which this PR undid which is why I'm surprised to see this removing that.

**Comment by markwilkie** [comment]
We do plan to use that step (which we undid) as part of #578.  We didn't want some "half finished" thing in until we were ready to properly address the work.

**Comment by weshaggard** [comment]
Ok I would have suggested we leave it as it was step in the right direction and wasn't hurting anything but we can undo this once we have someone actively working on it.

**Pull request merged**
