### PR TITLE
Updating WIX to version 3.14.0 to attempt to address Governance requirement

### PR DESCRIPTION
**Pull request by davfost**
Updating WIX to version 3.14.0 to attempt to address Governance requirement

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by dougbu** [comment]
simple change but I suggest @joeloff is the right person to review this 6.0 change. also suspect (from the build failures) that you need a different feed to find WiX 3.14.0.

/fyi there's a larger effort coming to move to WiX 4.0 but we shouldn't get ahead of ourselves because that'll require a _significant_ change in multiple repos apparently

**Review by dougbu — DISMISSED** [review]
oh, this is a good option 😀

**Comment by davfost** [comment]
The WIX package appears to be coming from 3 different feeds currently. I am attempting to consolidate on the Microsoft.Signed.Wix package as that appears to be the only one that is currently using version 3.14 or higher.

**Comment by joeloff** [comment]
It should really just be from the eng feed and a zip on blob depending what repos prefer. The version you have is the correct one. There should be version property though that you can reference in the .csproj https://github.com/dotnet/arcade/blob/c7a1a6fda527a373c6fb2a6cf8dae0982a2e7931/eng/Versions.props#L74

**Review by dougbu — APPROVED** [review]

**Review by joeloff — APPROVED** [review]
I assume this will get ported up to 7/8/main?

**Review by dougbu — APPROVED** [review]

**Comment by davfost** [comment]
> I assume this will get ported up to 7/8/main?

7/8/main are already governance compliant. In terms of the 'version' specifications there are many mis-match issues beyond the one for WIX. I will speak to my manager in my 1 on 1 to determine the priority of cleaning up all branches for all mismatches in all projects for arcade or see if we want to just clean up issues on a case by case basis, they impede governance compliance.

**Pull request merged**
