### PR TITLE
Switch "File" and "Extension" attributes in manifest to "Include"

### PR DESCRIPTION
**Pull request by jonfortescue**
Fixes #10382.

Example manifest using this build can be found [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=759426&view=artifacts&type=publishedArtifacts).

### CODE REVIEW

**Comment by missymessa** [comment]
Do we have tests to validate the output of this functionality?

**Comment by jcagme** [comment]
Also, please let's hold off merging this. I need to make a change in arcade-service's Maestro.Task since it still expects `File` and would fail when merging. Will paste the Maestro.Task version we should here when done

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade-services/pull/1333

**Comment by jcagme** [comment]
@jonfortescue could you please upgrade `Maestro.Tasks` version to `1.1.0-beta.20406.1` as part of this PR?

**Comment by jonfortescue** [comment]
@missymessa added test; @jcagme updated package version!

**Comment by jcagme** [comment]
Looks like there are conflicts, also, is there a test run I can look at?

**Comment by dougbu** [comment]
Does this and related changes mean builds using the old syntax can no longer be promoted into a channel❔

**Comment by riarenas** [comment]
It should be fine, as when promoting a build to a channel there are a couple of options:

* By default build promotion will use the version of arcade that the build that is trying to be promoted used, so old builds will use the older manifest and publishing, while new builds will use the new manifest and publishing.
* If the automatic version lookup ends up failing, it's possible to specify the branch and SHA of arcade that you want to take the publishing infra from when you promote, and that gives you a lot of flexibility.

**Pull request merged**
