### PR TITLE
Add Uri WorkItem payload.

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by markwilkie** [comment]
cc/ @jonfortescue as well.

**Comment by jonfortescue** [comment]
@jcagme @chcosta any ideas here?

**Comment by riarenas** [comment]
The Maestro and GitHub tokens are the same tokens you need to be able to use the darc tool.

Instructions at:
```
eng/common/darc-init.ps1
darc authenticate
```

Alternatively, you can push your branch to the internal dnceng arcade mirror, and run the arcade official build definition: https://dnceng.visualstudio.com/internal/_build?definitionId=6 which will do all the steps for you.

**Comment by garath** [comment]
Perhaps better instructions on darc are working [through PR](https://github.com/dotnet/arcade/pull/1951) right now. See the [darc authenticate](https://github.com/dotnet/arcade/blob/2b969ec2170d955bfa506ab6758c5dd61bad5b3f/Documentation/Darc.md#authenticate) section.

**Pull request merged**
