### PR TITLE
Avoid generating dummy fields for structs that already contain appropriate public fields

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/dotnet/arcade/issues/2031

### CODE REVIEW

**Comment by markwilkie** [comment]
@jaredpar - who do you think the right person to review this is?  (not sure @weshaggard cares anymore...grin)

**Comment by jaredpar** [comment]
Unfortunately everyone who understood this has left the various teams. At least that I'm aware of. @weshaggard may know someone who is still here that can review. 

My 2 cents though: the current state isn't broken, it's just verbose. There are no tests for this code and it's going to take effort to find a reviewer. I'd leave as is for now.

**Comment by pakrym** [comment]
It can't be left as is because of https://github.com/dotnet/arcade/issues/2030 that blocks ASP.NET Core adoption of GenAPI

**Comment by jaredpar** [comment]
How does it block ASP.NET adoption? That's not specified anywhere. 

Als

**Comment by pakrym** [comment]
We have a type that has `LayoutKind.Explicit` and adding a dummy field without `FieldOffsetAttribute` produces code that doesn't compile. This type fortunately already has public value and reference type fields so adding dummy field is not required and avoids us hitting #2030.

**Comment by jaredpar** [comment]
Then this doesn't seem like the right fix. It will still leave the dummy field for other cases which need a dummy field and they'll hit the same error. Shouldn't we be fixing that?

**Comment by pakrym** [comment]
> Shouldn't we be fixing that?

We should definitely fix that too.

But my goal here is to unblock ASP.NET Core 3.0 targeting pack work. This PR is enough to accomplish that.

**Comment by pakrym** [comment]
Can we get some traction here, please? This is the last thing that's blocking targeting pack work on our side.

cc @muratg

**Comment by jaredpar** [comment]
my 2 cents: 

1. This is the wrong fix. As we identified you're fixing a symptom, not the problem. Should focus on the problem. Otherwise we'll jsut be back here again later on with another PR. 
1. I don't know who is qualified to review this code anymore. Possibly @ericstj will know.

**Comment by weshaggard** [comment]
The changes look reasonable to me but I shouldn't be the one signing off on the changes given that I won't be the one fixing issues if they occur. I'd suggest one of @ahsonkhan @terrajobst @ericstj @karelz as potential reviewers.

@jaredpar from a quick look it appears this is a valid fix and if we don't need to include a dummy field we shouldn't, so while #2031 might not be 100% necessary it is also not bad to take a fix for it. I also agree that #2030 should be fixed as well, however even if that was fixed I'm not sure how we would get a struct layout that matches what the implementation contains while we add a new dummy field. 

@pakrym you can also unblock yourself by excluding this type from genapi and providing it manually until the tooling can be fixed.

**Comment by markwilkie** [comment]
It's been almost a month.  Do you think this is still needed @pakrym ?

**Comment by pakrym** [comment]
We unblocked ourselves by manually editing the generated files. It would be nice to get this in any way to avoid future problems and additional work to maintain manually edited refs.

**Comment by terrajobst** [comment]
@stephentoub @jkotas  @ericstj

I think the correct fix is to omit dummy fix is to omit dummy fields if the type has an explicit layout and expose all fields from the implementation as-is.

**Comment by ericstj** [comment]
> I think the correct fix is to entirely omit dummy fields if the type has an explicit layout and instead expose all fields from the implementation as-is (preserving modifiers obviously).

Sounds about right.  I'd feel much more comfortable about selectively exposing things already defined in impl rather a field called *dummy*.  What does csc /refout do?

**Comment by terrajobst** [comment]
> What does `csc /refout` do?

@jaredpar ?

**Comment by stephentoub** [comment]
> The reason being that explicit layout basically means there isn't much room for implementation details anyways -- they are part of your API contract.

@terrajobst, can you help me to understand that better?  This may be academic, because at least for coreclr/corefx, looking through all of our LayoutKind.Explicit structs, they fall into one of two categories:
1. Internal, and thus wouldn't be in ref assemblies anyway.
2. Public, but with all of their fields public as well (mostly COM interop related)

That said, for a decent number of the internal structs that are Explicit, the layout actually is just an implementation detail.  For example:
https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueueSegment.cs,332
uses explicit to ensure that the fields are a certain distance apart in order to minimize false sharing.

**Comment by jkotas** [comment]
> @pakrym you can also unblock yourself by excluding this type from genapi and providing it manually until the tooling can be fixed.

I would recommend doing this.

The proposed fix fixes some cases, but breaks other cases: If you have a struct with both private and public fields, the fix may make the C# compiler to think that that the struct is fully initialized when it actually is not.

I am not sure whether it is worth inventing the correct fix for this corner case. It should be only ever a problem for APIs that are violating API design guidelines.

**Comment by markwilkie** [comment]
@pakrym - does it make sense to close this PR?

**Comment by terrajobst** [comment]
> > The reason being that explicit layout basically means there isn't much room for implementation details anyways -- they are part of your API contract.
> 
> @terrajobst, can you help me to understand that better? This may be academic, because at least for coreclr/corefx, looking through all of our LayoutKind.Explicit structs, they fall into one of two categories:
> 
> 1. Internal, and thus wouldn't be in ref assemblies anyway.
> 2. Public, but with all of their fields public as well (mostly COM interop related)

The only relevant case is (2) here (because we're talking about GenAPI). My statement was meant to mean "if you expose a struct with explicit layout in your API, you'e surrendering your right to change the layout of private fields, thus GenAPI should encode the type as is from the implementation".

> That said, for a decent number of the internal structs that are Explicit, the layout actually is just an implementation detail. For example:
> https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueueSegment.cs,332
> uses explicit to ensure that the fields are a certain distance apart in order to minimize false sharing.

That's fair, but I'm not sure it's worth optimizing for this case. My proposal isn't mean to make GenAPI for arbitrary design goals; but I think the heuristic is good enough.

**Comment by pakrym** [comment]
I'll leave the decision here to @anurse

**Comment by anurse** [comment]
Since we've worked around this using manual generation, I'm ok to close this.

**Pull request closed without merging**
