### PR TITLE
Update the SDK to 6.0 Preview 1

### PR DESCRIPTION
**Pull request by ViktorHofer**
As agreed in Tactics, we want to dogfood our officially released SDK builds on a monthly cadence. Also sent out a mail to tactics for approval.

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@mmitche any idea what's causing the failure?

**Comment by ViktorHofer** [comment]
Had to update the NuGet package dependencies because of a breaking change in their API: https://github.com/NuGet/NuGet.Client/pull/3215#discussion_r579635554.

**Comment by Lodewijk1** [comment]
Master Joda hier

**Comment by Lodewijk1** [comment]
Leunin proces. Syst.m 32 windows advanced instller

**Comment by Lodewijk1** [comment]
Be happy het antwoorx op metox das metox!

Op za 20 feb. 2021 13:17 schreef azure-pipelines[bot] <
notifications@github.com>:

**Comment by ViktorHofer** [comment]
@dotnet/dnceng can someone help me figuring out why the `FindDotNetCliPackage` task is failing on the xHarness legs?

**Comment by premun** [comment]
@ViktorHofer let me see

**Comment by mmitche** [comment]
@premun That's not the version of aspnetcore in preview 1 (is actually 6.0.0-preview.1.21103.6)

**Comment by premun** [comment]
So the problem is that XHarness is a .NET Core 3.1 tool and the version was hardcoded to 3.1.5. But then it was changed here:
https://github.com/dotnet/arcade/commit/38a3674288eb2559aa64245adcf4035c34c61749

@steveisok I have only seen the other change where you require the aspnetcore-sdk instead of runtime if it's desired. Why did we need to also change the version? This SDK should be only used to run XHarness or there are other things like the web server in the WASM flows?

**Comment by mmitche** [comment]
That change may be getting rolled out to arcade here: https://github.com/dotnet/arcade/pull/7005

**Comment by premun** [comment]
The value gets set here:
https://github.com/dotnet/arcade/blob/f388f258444f63a9754ad202f2f0d099c4a67fc6/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props#L5-L6

If we have incoherent preview versions between ASP.NET Core version, we might need to have two variables then but I am not sure about the impact of a change like that.

**Comment by mmitche** [comment]
> The value gets set here:
> https://github.com/dotnet/arcade/blob/f388f258444f63a9754ad202f2f0d099c4a67fc6/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props#L5-L6
> 
> If we have incoherent preview versions between the SDK and the ASP.NET Core version, we might need to have two variables then but I am not sure about the impact of a change like that.

It's safe to assume that we will have incoherent versions for every preview, and coherent for any RTM/servicing version.

**Comment by premun** [comment]
@ViktorHofer how urgent is this update? I am a bit burried this week but I could look into it next week

**Comment by ViktorHofer** [comment]
It would be really great to get this in before Monday 3/1 which is the date where we update the SDK in dotnet/runtime as part of our batched rollout.

**Comment by premun** [comment]
I will have a look on Friday then. I need to make sure a change here won't cause problems down the line first so I don't want to rush it much.

Also please be aware that this probably only changes which .NET we use to build Arcade but the projects themselves have only recently been updated to .NET Core 3.1 (https://github.com/dotnet/arcade/pull/6891). So the produces of Arcade are behind quite a lot.

**Comment by ViktorHofer** [comment]
> But please be aware that this probably only changes which .NET we use to build Arcade. The projects themselves have only recently been updated to .NET Core 3.1 (#6891). So the produces of Arcade are behind quite a lot.

That is understood and expected. Even though I think we should always build against latest, the reason why this PR is opened is to flow the SDK update to 6.0 P1 into all "arcadified" repositories. Arcade handles that well as its part of the Maestro dependency flow.

**Review by mmitche — APPROVED** [review]

**Comment by premun** [comment]
So I actually found that the real problem is different..
The green version is in global.json and the yellow version it's trying to install but cannot find:

image

/__w/1/s/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets(5,5): Unable to find dotnet cli aspnetcore-runtime version 6.0.0-preview.1.21102.12, tried https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.0-preview.1.21102.12/aspnetcore-runtime-6.0.0-preview.1.21102.12-osx-x64.tar.gz [/__w/1/s/tests/UnitTests.XHarness.iOS.proj]

**Comment by mmitche** [comment]
@rbhanda @leecow See above, the included runtimes have the same version, but they're different for previews.

**Comment by rbhanda** [comment]
Adding @mairaw for dot.net. 

As per the [release.json](https://github.com/dotnet/core/blob/main/release-notes/6.0/releases.json), the ASP.NET Runtime version is 6.0.0-preview.1.21103.6 while runtime version is 6.0.0-preview.1.21102.12.

Also releases.json has the correct URL for [aspnetcore-runtime-osx-x64](https://download.visualstudio.microsoft.com/download/pr/9c1c4e05-2adb-4ea0-9d9a-f0c7406de9c0/af48195a4e770620a0721dd27fdcb4c9/aspnetcore-runtime-6.0.0-preview.1.21103.6-osx-x64.tar.gz)

**Comment by premun** [comment]
Thanks!

So I guess the way we get the URL is wonky in our case: https://github.com/dotnet/arcade/blob/15246f4af00a1cb2e580783d32ec2937b1878a64/src/Microsoft.DotNet.Helix/Sdk/FindDotNetCliPackage.cs#L89

I guess we should be parsing the `release.json` and getting it from there?

**Comment by premun** [comment]
@ViktorHofer the build is green now but it forces the specific preview version in a sort-of hacky way. Nonetheless, it should work since it's tied to SDK version set in `global.json`. If we want this in for Monday, I'd say we can do it and prepare a proper way to handle this.

@mmitche thoughts?

**Comment by mmitche** [comment]
> @ViktorHofer the build is green now but it forces the specific preview version in a sort-of hacky way. Nonetheless, it should work since it's tied to SDK version set in `global.json`. If we want this in for Monday, I'd say we can do it and prepare a proper way to handle this.
> 
> @mmitche thoughts?

Yep fine by me. Parsing the releases.json seems questionable. There are times when we don't use officially released versions here.

**Comment by ViktorHofer** [comment]
Yes works for me too. Let's just make sure that the proper fix gets the right attention after this is in. Thanks to all that helped getting this in.

**Comment by mairaw** [comment]
Thanks for the ping @rbhanda. I've fixed the download page info:
image

**Pull request merged**
