### PR TITLE
Force import of the "right" version of X509Certificates

### PR DESCRIPTION
**Pull request by MattGal**
(we were restoring multiple before and this is undesirable for static analysis)

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation (verified locally)

### CODE REVIEW

**Review by ulisesh — APPROVED** [review]
LGTM

**Comment by premun** [comment]
@MattGal just to double-check - should this change be specific to arcade?

I am asking because when onboarding Arcade, we ask people to copy this file over so it might not be desirable to have arcade specific things there.

**Comment by MattGal** [comment]
> @MattGal just to double-check - should this change be specific to arcade?
> 
> I am asking because when onboarding Arcade, we ask people to copy this file over so it might not be desirable to have arcade specific things there.

We need to be CG clean.  If people copy and paste things outside the eng/common folder in Arcade, there are numerous examples of things that don't necessarily apply to other repos.  If you have an approach that gets a green scan though that you feel is better for that "blind copy/paste" user group, I'm happy to approve that PR.

**Comment by premun** [comment]
> If people copy and paste things outside the eng/common folder in Arcade, there are numerous examples of things that don't necessarily apply to other repos

I understand that they just shouldn't copy any files and expect to adopt them, but we literally tell them to copy this one when starting a fresh repo:

image

What if people don't have the `SystemSecurityCryptographyX509CertificatesVersion` property available?

I think we could resolve this by putting another `Directory.Build.props` lower in Arcade's tree (in `src/` or `test/` or wherever we need it) and include the root `DB.props` from there.

**Pull request merged**
