### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by garath**
This begins an updated entry point to user documentation, links some existing resources and adds a "documentation principles" guide.

### CODE REVIEW

**Comment by markwilkie** [comment]
I wonder if it might be better to have a simple (modern kinda) landing page seperate from getting started w/ basically the block you already inserted into getting started.  That way it's not "lost" in a very busy page...

Also, if you are looking to mimic 1ES, you could potentially also use tables.  https://help.github.com/articles/organizing-information-with-tables/

Thoughts?

**Comment by garath** [comment]
I agree. GitHub pages has opinions about where the entry page can be, which is a bigger change than I was anticipating. I think this is the next step.

**Comment by garath** [comment]
I've enabled Pages on my fork. See [here](https://garath.github.io/arcade/) for the preview.

**Comment by markwilkie** [comment]
I like this - it seem that the direction should work.  What do you think about trying out the documentation yourself to onboard some random repo in your own fork?  It might have the effect of rounding things out.  For example, the new packages guidance is general, but which packages to use for what was harder to find...

Thoughts?  It would be great to get something checked in a iterate from there, but the initial check it should also be somewhat representative.  Thoughts?

**Comment by garath** [comment]
Discussed in-person with Mark. Merging.

**Pull request merged**
