### PR TITLE
Prevent double-import warning for Microsoft.Common.props

### PR DESCRIPTION
**Pull request by MattGal**
Noted from the conversation [here](https://github.com/dotnet/aspnetcore/pull/23585#discussion_r450353191)

### CODE REVIEW

**Comment by alexperovich** [comment]
This.... should really be needed at all. A helix sdk project doesn't use the 'Microsoft.NET.Sdk' and projects made with the helix sdk shouldn't ever import it.

**Comment by dougbu** [comment]
@alexperovich without this conditionality, features such as automated .NET SDK installation on Helix agents are pretty much useless. We need to know `$(NETCoreSdkVersion)` when setting `$(DotNetCliVersion)` and using `$(IncludeDotNetCli)`. That means we need to import all of the .NET SDK's SDK.props, not the small part of it the Helix SDK imports.

**Comment by MattGal** [comment]
> @alexperovich without this conditionality, features such as automated .NET SDK installation on Helix agents are pretty much useless. We need to know `$(NETCoreSdkVersion)` when setting `$(DotNetCliVersion)` and using `$(IncludeDotNetCli)`. That means we need to import all of the .NET SDK's SDK.props, not the small part of it the Helix SDK imports.

I think @alexperovich is suggesting full deletion of the line.  I prefer to not find out that we did actually need it later on, but I'll chat w/ Alex offline and get this done one way or the other.

**Comment by alexperovich** [comment]
I am not suggesting full deletion of the line. The helix sdk requires microsoft.common.props and targets to work. It is not designed to work alongside another SDK that also imports them. We can add this condition, but there are no guarantees that anything will work in that scenario.

**Comment by dougbu** [comment]
What alternative do you suggest @alexperovich to make `$(IncludeDotNetCli)` useful (without ugly hacks and manual changes to multiple files when the SDK version changes)❔

**Comment by MattGal** [comment]
After discussion with @alexperovich it seems that it's preferable for teams needing to do this to suppress the warning, abandoning.

**Comment by dougbu** [comment]
Why is it preferable to suppress the warning❔ I thought @alexperovich was saying what we need to do won't work and we might as well give up on `$(IncludeDotNetCli)` until something else changes.

**Comment by alexperovich** [comment]
It looks like we can grab that version without importing the entire sdk. I will look into it.

**Comment by dougbu** [comment]
> I will look into it.

Much appreciated❕

**Comment by alexperovich** [comment]
https://github.com/dotnet/arcade/pull/5748

**Pull request closed without merging**
