### PR TITLE
Update default version of signtool in SDK

### PR DESCRIPTION
**Pull request by JohnTortugo**

### CODE REVIEW

**Comment by jcagme** [comment]
Should we make this upgradable by Maestro?

**Comment by jcagme** [comment]
Actually it is part of the dependencies that are updated on each PR. If this was not auto upgraded then we need to figure out why. I checked today’s PR and the version was updated

**Comment by nguerrera** [comment]
It looks like dependency update just updates the versions used for the build off arcade itself:

https://github.com/dotnet/arcade/blob/afdfa8bf7011553e3a8acf4c66b74d8ea7cba865/eng/Version.Details.xml#L12-L16

But does not update these default versions passed on to repos that do not list it as an explicit dependency.

What is the guidance here? Are these default versions meant to be kept up to date, or should arcade repos be specifying everything explicitly with their own dependency uptake?

**Comment by tmat** [comment]
> What is the guidance here? Are these default versions meant to be kept up to date, or should arcade repos be specifying everything explicitly with their own dependency uptake?

I don't think they should. Repos can definitely override the versions if there is a reason for it, but I wouldn't do that unless working around some issue.

The tools listed in DefaultVersions are integrated to Arcade SDK targets. That means a change in the targets might be necessary when the tool changes. For example, let's say we added a new parameter to the sign tool task. Then the targets in Arcade SDK need to pass that parameter. So we can't just automatically consume the new version as soon as it's available.

Also not that not all repositories that use Arcade SDK have dependency uptake.

**Pull request merged**
