### PR TITLE
Added extra attribute to manifest to arcade 3.x 

### PR DESCRIPTION
**Pull request by epananth**
## Description

Same change as https://github.com/dotnet/arcade/pull/6319, but the target branch is arcade 3.x

## Customer Impact

Customer impact if this change is **not** made.

## Regression

Testing here ->https://dnceng.visualstudio.com/internal/_build/results?buildId=843160&view=results ( cos of the outage this might not run)

## Risk

How risky is this change? Not risky, just adding another attribute to the manifest

## Workarounds

Are there available workarounds for the bug? No, have to make this change so that arcade-services get the attribute.

### CODE REVIEW

**Comment by MattGal** [comment]
Everything's on the floor from the outages, but wasn't there also a test change needed with this?

**Comment by epananth** [comment]
with the outage, my test is not going to pass :(  So I created a PR anyway. I will run a build and whenever it passes, I will merge this..

**Comment by MattGal** [comment]
For release/3.x, I think the PR text should fill out https://github.com/dotnet/arcade/blob/master/Documentation/Policy/AskModeTellModeTemplate.md too.

**Review by MattGal — APPROVED** [review]
LGTM

**Pull request merged**
