### PR TITLE
Bump the version of Drop.App

### PR DESCRIPTION
**Pull request by andriipatsula**
### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

Fixes: https://github.com/dotnet/arcade/issues/14866

[discussion in Teams](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1718808066604?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1718808066604&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1718808066604)

### CODE REVIEW

**Review by premun — APPROVED** [review]
I have never heard of this `Drop.App` so no idea

**Comment by andriipatsula** [comment]
> I have never heard of this Drop.App so no idea

Started a discussion in [FR Internal](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1718808066604?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1718808066604&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1718808066604)

**Review by mmitche — APPROVED** [review]

**Comment by riarenas** [comment]
Where do we get the drop app from? If it's from https://devdiv.visualstudio.com/DevDiv/_artifacts/feed/dotnet-core-internal-tooling/NuGet/Drop.App, the new version is not available in the feed.

**Comment by premun** [comment]
Can you put a comment above the line with a link to the feed so that people can verify this next time?

**Comment by riarenas** [comment]
Maybe we can add the mseng feed as an upstream to the internal-tooling feed? Since it's in a different org from devdiv I'm not entirely sure it will "just work". 

We currently get the drop app from upstreaming the VS feed, and it seems the VS feed only has up to `18.165.29912-buildid11693003`. The VS feed has no upstreams.

**Comment by andriipatsula** [comment]
> Maybe we can add the mseng feed as an upstream to the internal-tooling feed? Since it's in a different org from devdiv I'm not entirely sure it will "just work".
> 
> The dotnet-core-internal-tooling feed gets the drop app from upstreaming the VS feed, and it seems the VS feed only has up to `18.165.29912-buildid11693003`. The VS feed has no upstreams.

I added an upstream feed `azure-feed://mseng/VSOnline-Internal@Shared` to `dotnet-core-internal-tooling`. So we have a new version available in our feed
[Package Details - Azure Artifacts (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_artifacts/feed/dotnet-core-internal-tooling/NuGet/Drop.App/overview/19.239.34923-buildid28260713)

**Pull request merged**
