### PR TITLE
Add dependsOn and condition parameters to source-index job

### PR DESCRIPTION
**Pull request by alexperovich**
### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by jonfortescue** [comment]
@alexperovich do we still want to merge this?

**Comment by alexperovich** [comment]
Yes, I need this for change for runtime. I haven't poked any to get this reviewed though.

**Comment by alexperovich** [comment]
@ChadNedzlek can I get a sanity check here?

**Review by ChadNedzlek — APPROVED** [review]

**Pull request merged**
