### PR TITLE
Bump xcopy MSBuild from `17.6.0-2` to `17.7.2`

### PR DESCRIPTION
**Pull request by premun**
Hopefully this solves https://github.com/dotnet/dnceng/issues/904

https://dev.azure.com/dnceng/internal/_build/results?buildId=2271252&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=fb192a8b-e433-5fc8-e2b0-276ab015e7d5&l=34

### CODE REVIEW

**Comment by dkurepa** [comment]
If the build requires a higher version of msbuild than we have bundled with VS, we are going to use the Msbuild from this script

**Review by dkurepa — APPROVED** [review]

**Comment by riarenas** [comment]
Did we fix the problems with the 17.7.2 package? https://github.com/dotnet/arcade/issues/14055

**Comment by riarenas** [comment]
This still needs to happen, it's just that it seems 17.7.2 is not a good xcopy msbuild.

**Comment by riarenas** [comment]
Basically, it seems the package that we generated brings in new of out of date dependencies with it that will create CG alerts in repos. We probably need a second attempt at generating the package (it's not rare we get this wrong, the process is very manual and icky)

**Comment by riarenas** [comment]
This indeed brings in new CG alerts. It's probably best if we revert

**Pull request merged**
