### PR TITLE
Remove symbol validation from channel implementations.

### PR DESCRIPTION
**Pull request by JohnTortugo**
Closes: https://github.com/dotnet/arcade/issues/3872

Remove symbol validation references from channel implementations.

I'm going to keep the symbol-validation.ps1 file because I think we'll need it in the future when we do the validation during the release.

/cc @vatsan-madhavan

### CODE REVIEW

**Comment by riarenas** [comment]
Could you also remove the parameter from the doc?

**Comment by JohnTortugo** [comment]
Yeah. I'm going to update the documentation. I'm also going to keep the parameter in the post-build.yml file otherwise builds will start to fail because they reference the parameter.

I'm looking for a way to warn (during the build) that the parameter shouldn't be used anymore.

**Comment by markwilkie** [comment]
Can you add an issue Cesar to come up w/ a way to deprecate properties please?  (this is to your point above)

**Comment by JohnTortugo** [comment]
@markwilkie - issue is here https://github.com/dotnet/arcade/issues/3884

**Pull request merged**
