### PR TITLE
Update default msbuild for sdk tasks

### PR DESCRIPTION
**Pull request by mmitche**
rc2 requires 17.3.0+. Should fix sign-check error in arcade-validation

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by riarenas** [comment]
I think there's a process to generate these packages, I still see 17.2.1 as the latest version in the feed: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/RoslynTools.MSBuild/versions

**Comment by riarenas** [comment]
We should also update here: https://github.com/dotnet/arcade/blob/afc901d73d7d3bd363547ddf8769efe14052bfa7/eng/common/tools.ps1#L369

**Comment by riarenas** [comment]
I'm failing to find the docs on how to generate a new xcopy msbuild. I think @MattGal dealt with this last. Do you happen to remember where the docs for this are?

**Comment by mmitche** [comment]
https://teams.microsoft.com/l/message/19:05c952128d754b8eb8fbe3a14141c6e3@thread.skype/1623351242618?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1623350658056&teamName=.NET%20Eng%20Services&channelName=Arcade%20Guardians&createdTime=1623351242618&allowXTenantAccess=false

**Comment by MattGal** [comment]
> I'm failing to find the docs on how to generate a new xcopy msbuild. I think @MattGal dealt with this last. Do you happen to remember where the docs for this are?

It's in the readme in https://github.com/jaredpar/xcopy-msbuild

**Review by riarenas — APPROVED** [review]

**Comment by akoeplinger** [comment]
Should we port this to main?

**Pull request merged**
