### PR TITLE
Fixes for SetupNuGetSources scripts

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/arcade/issues/4469

* Add 3.1 internal feeds as well as 3.0
* Fix some errors in the bash script
* Fixed the usage blurb

Not 100% certain of how the yaml needs to look for the bash script to get all the values, so queued https://dev.azure.com/dnceng/internal/_build/results?buildId=445116 to make sure.

### CODE REVIEW

**Comment by riarenas** [comment]
I guess we now fail PRs if a script doesn't capture telemetry. Adding some calls following the guidance...

**Comment by mmitche** [comment]
@riarenas I'd port to 3.x first, as it doesn't have the same telemetry requirements. Also, getting this done asap is critical

**Comment by riarenas** [comment]
@mmitche I still had to make sure the linux calls were working and adding the telemetry wasn't much additional work. Everything looks good now: https://dev.azure.com/dnceng/internal/_build/results?buildId=445154 modified the nuget.config and added it to the build artifacts.

**Comment by mmitche** [comment]
> Not 100% certain of how the yaml needs to look for the bash script to get all the values, so queued https://dev.azure.com/dnceng/internal/_build/results?buildId=445116 to make sure.

That looks like it only ran windows.

**Comment by riarenas** [comment]
Yeah I messed that one up. the linux one is here:  https://dev.azure.com/dnceng/internal/_build/results?buildId=445154

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/4481 for 3.x PR

**Pull request merged**
