### PR TITLE
[release/6.0] Add 1espt compatible official templates

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/arcade/issues/14524 for release/6.0

Trying something different with this one to see if that helps take look at things. 

* [9da548e0c0cee38d5320c5ee1927a73f1371b63a](https://github.com/dotnet/arcade/commit/9da548e0c0cee38d5320c5ee1927a73f1371b63a) has the diff between the old and new templates
* [3936ac0c4626048aa84d3818cc63fff75ecd951d](https://github.com/dotnet/arcade/commit/3936ac0c4626048aa84d3818cc63fff75ecd951d) adds the old templates back so I don't end up deleting anything.

The validation is pretty suspect on this change.
 https://dev.azure.com/dnceng/internal/_build/results?buildId=2401312&view=results is a build of symreader's main branch but with the 6.0 templates which is not ideal. 

Any other ideas on better tests that don't involve converting a more complex pipeline are welcome.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by riarenas** [comment]
Oh, I think I want to add the fixed setupnugetsources.ps1 to this PR as well. https://github.com/dotnet/arcade/pull/14553 didn't backport cleanly to 6.0

**Comment by riarenas** [comment]
Fixed the script and ran this new test: https://dev.azure.com/dnceng/internal/_build/results?buildId=2401507&view=results

**Review by mmitche — APPROVED** [review]
Seems reasonable.

**Comment by riarenas** [comment]
> Seems reasonable.

Terrifying

**Comment by mmitche** [comment]
I looked at the diff. It looked pretty non-invasive, so nothing jumped out. We'll work through issues if we find them.

**Comment by riarenas** [comment]
> I looked at the diff. It looked pretty non-invasive, so nothing jumped out. We'll work through issues if we find them.

Yep, it was in jest. Servicing branches tend to be scarier than main.

**Pull request merged**
