### PR TITLE
Excluding symbols in SymbolsPublishingExclusion.txt to publish to symbol server

### PR DESCRIPTION
**Pull request by epananth**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

Ran a runtime publishing build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1284774&view=results

Also this is the runtime build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1284469&view=results

Here is the place where the symbolsExclusion file is uploaded

image

This was missing the previous build, so publishing failed -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1281458&view=artifacts&pathAsName=false&type=publishedArtifacts

### CODE REVIEW

**Comment by epananth** [comment]
Arcade will need an arcade update immediately after this change is merged to main

**Comment by epananth** [comment]
I ran another test with sdk -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1284280&view=results that worked too

**Comment by riarenas** [comment]
I see that runtime's publishing still seems to be failing: https://dev.azure.com/dnceng/internal/_build/results?buildId=1285349&view=results

Does that mean this change wasn't responsible for it? Or that a YAML change needs to propagate to runtime? Should we still be tracking that somewhere else?

Is there a way to split this change so that there aren't any side effects between when this gets merged and when Arcade gets updated? There will always be a gap while the official build succeeds. I would think the task change can go first, and the yaml changes should go with the version bump?

**Comment by epananth** [comment]
Sure I can split this PR into 2 parts, so that the promotion does not break

**Comment by epananth** [comment]
I did some digging on runtime publishing, looks like its not that change that broke runtime. Its something else may be related to the symUploader API

**Comment by markwilkie** [comment]
What do we need to do to unblock?

**Review by hoyosjs — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Pull request merged**
