### PR TITLE
Do case-insensitive comparison for ArchiveTests

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @safern @ViktorHofer

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Just curious, was there an issue with the case sensitive comparison?

**Comment by wtgodbe** [comment]
@ViktorHofer yes, me and @carlossanlop were trying to get a build with archived tests locally, and were confused when `/p:ArchiveTests=tests` didn't work

**Comment by ViktorHofer** [comment]
I see. What was the reason that you needed the archived tests locally? Just asking as that property will probably change (= simplified) in the future and I didn't expect that anybody uses it besides me and @safern as it's an implementation detail.

**Comment by wtgodbe** [comment]
We were trying to get a private test run going in Helix (something that @wfurt sent email to the team about a few weeks ago). Useful if you want to add some debug `printf`s to your code, then run the tests on a set of Helix queues (Or add some new tests & get CI validation before going to PR).

**Comment by ViktorHofer** [comment]
Thanks!

**Pull request merged**
