### PR TITLE
Add Channel option to call to dotnet-install

### PR DESCRIPTION
**Pull request by adiaaida**
For the dotnet/performance repo, we would like to be able to pull in dotnet from various channels. This change adds the ability to specify the channel that we want to pull dotnet from. Default behavior is to do what we currently do and pull from LTS. To specify a channel, one would change their global.json to include a "dotnetChannel": "<channel name>" line.

### CODE REVIEW

**Comment by adiaaida** [comment]
@chcosta @jcagme @tmat PTAL

**Comment by markwilkie** [comment]
What's the latest with this @adiaaida ?

I'm kinda uncomfortable having "LTS" be hard-coded.  Outside of that, I would have thought that we could already choose a channel.  @mmitche ?

**Comment by adiaaida** [comment]
I ultimately decided I didn't really need it and forgot about this PR.

**Comment by jcagme** [comment]
> I ultimately decided I didn't really need it and forgot about this PR.

Should this PR be closed?

**Pull request closed without merging**
