### PR TITLE
Update Microsoft.DotNet.Maestro.Tasks

### PR DESCRIPTION
**Pull request by MilenaHristova**
Updates arcade version to get https://github.com/dotnet/arcade/pull/14702
Updates Microsoft.DotNet.Maestro.Tasks to get https://github.com/dotnet/arcade-services/pull/3311

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Interestingly, most of the projects in release/6.0 are set up to target netcoreapp3.1 :/

**Comment by mmitche** [comment]
I poked around this a bit, it's kind of messy:
- The issue is that this branch of the repo wants to target netcoreapp3.1. It's pervasive enough that it kind of scares me to change. Not sure what the implications would be.
- That means in order for Build.Tasks.Feed to target netcoreapp3.1, we either need the Maestro Client to target net3.1 or at least additionally target netstandard. It would look something like https://github.com/dotnet/arcade-services/pull/3485
- Alternatively, we could also eliminate the Maestro client ref from Build.tasks.Feed. It's only used in the publishing code, which is not active in this branch.

**Comment by MilenaHristova** [comment]
> I poked around this a bit, it's kind of messy:
> 
> * The issue is that this branch of the repo wants to target netcoreapp3.1. It's pervasive enough that it kind of scares me to change. Not sure what the implications would be.
> * That means in order for Build.Tasks.Feed to target netcoreapp3.1, we either need the Maestro Client to target net3.1 or at least additionally target netstandard. It would look something like [Allow the Maestro client to target netstandard arcade-services#3485](https://github.com/dotnet/arcade-services/pull/3485)
> * Alternatively, we could also eliminate the Maestro client ref from Build.tasks.Feed. It's only used in the publishing code, which is not active in this branch. That would look something like [Remove Maestro Client dependencies in release/6.0 #14711](https://github.com/dotnet/arcade/pull/14711)
> * Lastly, we may just be able to simply split the Maestro.Client and Maestro.Tasks references. Leave Maestro.Client on the old version. **I would try this first**.

Thanks for investigating. I tried updating only Maestro.Tasks and it's building at least. I'm not sure what would happen if we have different versions since Maestro.Tasks calls Maestro.Client. @premun do you know if Maestro.Tasks and Maestro.Client versions should be synced?

**Comment by premun** [comment]
@MilenaHristova why didn't it get bumped together to the same version? How did we update the dependencies here?

**Comment by premun** [comment]
There was a build today where we target netstandard - https://dev.azure.com/dnceng/internal/_build/results?buildId=2428221&view=results - probably we want those versions here?

**Comment by MilenaHristova** [comment]
> I think you should :)

It didn't work because `System.Text.Encodings.Web`, `System.Collections.Immutable`, and probably others don't target netcoreapp3.1. 
Maybe we can try leaving Maestro.Client on the old version and see how it works in arcade-validation? Or if they must be in sync then https://github.com/dotnet/arcade/pull/14711 should work?

**Comment by mmitche** [comment]
Yeah, updating to the newer client is going to start pulling everything forward onto net6 or higher. That's also an option, I just wish I knew why we kept this on netcoreapp3.1.

I would go with the low risk change and split the versions for now.

**Comment by tkapin** [comment]
@mmitche - wouldn't it be a low risk change just to delete it if the code is not used anymore? If that's done in one commit, it should be easy to restore if needed.

**Comment by mmitche** [comment]
> @mmitche - wouldn't it be a low risk change just to delete it if the code is not used anymore? If that's done in one commit, it should be easy to restore if needed.

Yep, I have the removal in PR.

**Pull request merged**
