### PR TITLE
Add DoNotAbortNativeToolsInstallationOnFailure/DoNotDisplayNativeToolsInstallationWarnings equivalent on Unix

### PR DESCRIPTION
**Pull request by hughbe**
Cref #3496 

/cc @vatsan-madhavan

### CODE REVIEW

**Comment by hughbe** [comment]
> It would be great if the init-tools-native.* scripts imported the pipeline-logging-functions.* scripts so that meaningful errors were surfaced in Azure DevOps if there was a failure.

Could you clarify what you mean? Just invoke it at the top of the file?

E.g. `$_script_dir/pipeline-logging-functions.sh`

**Comment by hughbe** [comment]
@chcosta how does this look :)

**Comment by chcosta** [comment]
Sorry for the delayed response.  The "pipeline-logging-function" scripts add in functions that allow you to emit messages which are actionable by Azure DevOps.  ie, rather than the pattern...

```
echo "Error: foo happened"
exit 1
```

you would do something like https://github.com/dotnet/arcade/blob/master/eng/common/tools.sh#L145

```
Write-PipelineTelemetryError -category 'native-tools-bootstrapping` "Foo happened"
exit 1
```

It's not really strictly necessary for your change.

**Comment by hughbe** [comment]
@chcosta I've done this :) let me know if this is good to merge!

**Comment by chcosta** [comment]
> I've done this

Which thing did you do?  I don't see this iteration as any different than your previous iteration.

Either, this change should use the pipeline logging functions and emit meaningful errors instead of using "echo", or this change should not include the pipeline logging functions at all.

Sorry this is taking so long.

**Comment by JohnTortugo** [comment]
/azp run

Is this still necessary / good to merge?

**Comment by jonfortescue** [comment]
@hughbe @chcosta Would we like to merge this still? Checks are all passing and it has approval.

**Comment by chcosta** [comment]
The changes look reasonable.  I don't remember seeing any functional validation for this though.

**Comment by jonfortescue** [comment]
@chcosta @hughbe Tests are passing now and changes are approved, I'm going to merge this.

**Pull request merged**
