### PR TITLE
Replace MicrosoftSHA2 with Microsoft400

### PR DESCRIPTION
**Pull request by natemcmaster**
MicrosoftSHA2 should not be used. Microsoft400 is the more appropriate default.

### CODE REVIEW

**Comment by weshaggard** [comment]
@natemcmaster why do you think Microsoft400 is more appropriate? I would expect "Microsoft" to be the most appropriate based on the MicroBuild guidance https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?pagePath=%2FEngineering%20System%20%26%20Tools%2FMicroBuild%2FEnabling%20Signing%20in%20Your%20Projects%2FSigning%20Cert%20Guidance&wikiVersion=GBwikiMaster.

**Comment by joeloff** [comment]
Microsoft corresponds to 401 which is a dual authenticode cert. The current guidance from PRSS per the SHA1 deprecation plan it to move away from dual certs if possible. If the file doesn't need to be verified on older OS versions (Vista/XP/2K3), then use the SHA2 cert (old COPS 400)

**Comment by weshaggard** [comment]
@joeloff thanks so does that map to using "Microsoft400" then?

**Comment by joeloff** [comment]
yes, based on the link @natemcmaster shared, Microsoft400 should be the SHA2 authenticode cert.

**Comment by natemcmaster** [comment]
What @joeloff said. See https://aka.ms/sha1 and https://microsoft.sharepoint.com/teams/codesigninfo/Wiki/SHA1%20Deprecation%20Plan.aspx for details on SHA1 deprecation.

**Pull request merged**
