### PR TITLE
Enable using BinSkim and CredScan2 in SDL verification

### PR DESCRIPTION
**Pull request by hoyosjs**
First try at enabling binskim and credscan2 (credscan is on its way out). The only remaining concerns I'd have is BinSkim has no exclusion mechanism. To create exclusions for CreadScan2 a json file needs to be checked in according to https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-faq#to-suppress-all-occurrences-of-a-given-secret-within-the-specified-path

Cant add reviewers for some reason. @sunandabalu @jcagme

### CODE REVIEW

**Comment by hoyosjs** [comment]
Sorry. It's this: https://dev.azure.com/dnceng/internal/_build/results?buildId=596003&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=f511b583-5060-5810-7549-865816347c8e

**Comment by sunandabalu** [comment]
> Sorry. It's this: https://dev.azure.com/dnceng/internal/_build/results?buildId=596003&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=f511b583-5060-5810-7549-865816347c8e

BinSkim runs seems to be failing and not producing any results, maybe the target value needs some alterations?

```
Error running tool 1 of 1: BinSkim
    Error running BinSkim job: 1 of 122
    binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir\*.dll, or dir\*
    
```

**Comment by sunandabalu** [comment]
\cc @jonfortescue who has a little more context on BinSkim. Jon, is there something that needs to be done to get BinSkim to successfully scan here? I remember you had to do flattening of directories before running BinSkim before.

**Comment by jonfortescue** [comment]
@hoyosjs sorry for not responding to this, I was having lunch.

The trick to getting BinSkim to succeed is to trawl through your artifacts for dlls/exes and copy them into a single flat folder (naming them by {Name}-{Version} or {Name}-{Path} to avoid duplication). Then you point BinSkim at that directory and scan. It's a massive pain, but it's what I did last time I set up BinSkim.

**Pull request closed without merging**
