### PR TITLE
Fix Azure Devops Reporter : new change assumes Python 3.6+

### PR DESCRIPTION
**Pull request by MattGal**
It seems we don't test this codepath in default test runs, and the mentioned changes introduce a python 3.6-ism.  The fix is simply to access the RegEx's groups via the older method in all cases.

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

I'm validating this fix via both testing on python 3.5 in a Debian docker container (already done) and via applying my change on top of the commit that is the source of the failure via draft PR: https://github.com/dotnet/arcade/pull/7437

### CODE REVIEW

**Comment by MattGal** [comment]
[Verified fixed](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-7437-merge-5d42e50097d042ebac/Microsoft.DotNet.RemoteExecutor.Tests.dll/console.fd75e967.log?sv=2019-07-07&se=2021-06-13T17%3A13%3A36Z&sr=c&sp=rl&sig=3%2FwQRHbdaDXqz5HrIpzMKSA%2BKBDyrGOUjaP29ygn7iU%3D)

**Review by garath — COMMENTED** [review]
👍

**Review by garath — APPROVED** [review]

**Comment by ChadNedzlek** [comment]
Hrm... Perhaps we should include a testing queue that has a minimum version of python in the matrix so that people stop making this mistake? :-)

**Comment by MattGal** [comment]
> Hrm... Perhaps we should include a testing queue that has a minimum version of python in the matrix so that people stop making this mistake? :-)

We already do, it's Debian 9.  This code path wasn't hit by non-remote-executor test paths.

**Comment by ChadNedzlek** [comment]
It has uploaders for all the various formats.  Isn't the path just... "I ran XUnit"? Or am I misunderstanding the issue?

**Comment by MattGal** [comment]
> It has uploaders for all the various formats. Isn't the path just... "I ran XUnit"? Or am I misunderstanding the issue?

by code path, I mean it has to not return on https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/formats/xunit.py#L26 and hit https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/formats/xunit.py#L27 to reproduce the bug.

**Comment by ChadNedzlek** [comment]
Oohhhh!. It's "fake" XUnit stuff isn't fake enough.  It doesn't have the bad escaping in it.  Could we add one?

**Comment by ChadNedzlek** [comment]
Wait, it doesn't have a fake XUnit file... Now I'm extra confused.  It has JUnit and TRX.

Maybe one of the "real" tests needs to include a newline?

**Comment by MattGal** [comment]
@ChadNedzlek took some wrangling but I think I got it.  I had to make a testResults.xml and include it like the JUnit/ TRX parts since a real failing xunit test in Arcade  (as I opine it should) fails the work item and thus the job.

https://dev.azure.com/dnceng/public/_build/results?buildId=1154197&view=logs&j=50e98f4f-3b28-577a-6481-eda1b1f9a1d6 is the run

**Comment by MattGal** [comment]
Now successfully prints unicode and the other special characters covered in the reporter: 
image

**Pull request merged**
