### PR TITLE
Race condition fix for PublishArtifactsInManifest

### PR DESCRIPTION
**Pull request by lukas-lansky**
@mmitche suggested that some issues with missing assets we observe during Preview 5 package publishing (see [example](https://dev.azure.com/dnceng/internal/_build/results?buildId=654287&view=logs&j=4df4a6f9-28ef-5f93-fb89-c6fa9e3765d8&t=65db9769-0d0e-5ac4-c809-2b34859967fa&l=364) of such asset) can be connected to PR https://github.com/dotnet/arcade/pull/5414 and parallel usage of `HashSet` class that is not thread safe. So in this change, I'm replacing `HashSet<T>` by `ConcurrentDictionary<T, ()>`.

Any idea on how to test this properly is greatly welcomed.

Not sure whether this is connected to https://github.com/dotnet/installer/issues/7529.

### CODE REVIEW

**Comment by mmitche** [comment]
It's not connected to https://github.com/dotnet/installer/issues/7529.

Testing this may be tougher...you could build an official version of arcade that uses this fix, publish it to the General Testing channel, then update a repo (e.g. installer) to use the new build and run an official build with it.

I'm 99.9% sure that this is the actual bug though and that this fix will work :)

**Comment by mmitche** [comment]
@JohnTortugo Can you help @lukas-lansky fix up the current preivew5 build to have all the correct location information? All assets got correctly published but some did not get correct locations.

I'm thinking this could be done with some clever use of the API:
1. Get the builds from the manifest file.
2. Use the rest API to get all assets
3. Foreach asset:
4. If the current locations are empty or the build artifacts url:
  1. If ends in "symbols.nupkg", add https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json (Container)
  2, If ends in .sha512, add https://dotnetclichecksums.blob.core.windows.net/dotnet/index.json (Container)
  3. If ends in non .nupkg, add https://dotnetcli.blob.core.windows.net/dotnet/index.json (Container)
  4. Otherwise, fail and decide what to do about the specific asset.

**Comment by JohnTortugo** [comment]
@mmitche - Yeah, I'll talk with @lukas-lansky and get this sorted.

@lukas-lansky thanks for fixing this.

**Comment by JohnTortugo** [comment]
@mmitche - Judging by the mapping of file extension to target feed ([and the publishing logs here](https://dev.azure.com/dnceng/internal/_build/results?buildId=654287&view=logs&j=4df4a6f9-28ef-5f93-fb89-c6fa9e3765d8&t=65db9769-0d0e-5ac4-c809-2b34859967fa&l=54); and the type of assets) I think all other extensions should go to `https://dotnetcli.blob.core.windows.net/dotnet/index.json`. What do you think?

**Pull request merged**
