### PR TITLE
Add missed changes from initial duplication of arcade templates

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/arcade/issues/14556

I missed a few places with the template duplication we did. 

These were missed as I made the mistake of starting from the templates in the symreader repo (the test repo we were testing things on), which is behind in arcade updates since January.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Is https://github.com/dotnet/arcade/commit/e9a8e07465adf515a595e2afde2ffe893e973838 also missing? What's the strategy to keep templates-official in sync with templates? Or is the recommendation to touch both directories at the same time when making changes in Arcade?

**Review by ViktorHofer — APPROVED** [review]
Thanks for the quick fix!

**Comment by riarenas** [comment]
> Is [e9a8e07](https://github.com/dotnet/arcade/commit/e9a8e07465adf515a595e2afde2ffe893e973838) also missing? 

That one is a little trickier. the publishing pool hasn't been updated to allow usage of 1ES pipeline templates, so we probably don't want to bring that in. We'd need to wait for https://github.com/dotnet/dnceng/issues/2080 to roll out (we're aiming next week) 

It was on my radar but I didn't open an issue so thanks for the reminder: https://github.com/dotnet/dnceng/issues/2146

> What's the strategy to keep templates-official in sync with templates? Or is the recommendation to touch both directories at the same time when making changes in Arcade?

This is still TBD as we haven't really had time to do anything other than the minimum unblocking we could. Once we have had the chance to clean up the templates, I'm hoping either most of the duplication will go away, and keeping things in sync will be easier, or we will have tooling to help with the sync and prevent scenarios such as this one.

For now, as unsatisfying as it is, we'll have to do it manually, which will be error prone.

**Comment by akoeplinger** [comment]
@riarenas would you mind backporting this?

**Comment by akoeplinger** [comment]
@riarenas ah no sorry I got confused with another issue, nevermind.

**Pull request merged**
