### PR TITLE
Update .gitignore to remove launchSettings.json

### PR DESCRIPTION
**Pull request by eerhardt**
launchSettings.json files are intended to be committed to source control.

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]

**Comment by ViktorHofer** [comment]
We initially added them to gitignore as they were automatically created by tooling and then accidentally committed. How do we guard against that when removing the entry from .gitignore?

**Comment by DamianEdwards** [comment]
@ViktorHofer they're intended to be committed though, even if created by tooling.

**Comment by ViktorHofer** [comment]
IIRC we excluded them from this repository because they didn't add any value and just created more LOC. I.e. when someone uses VS to debug code locally, which results in the launchsettings file being generated. I agree on that there might be cases to check a launchsettings.json file in, but we didn't had any of these for this repository.

Why do you want to change this setting in arcade? Is there a specific project that would benefit from them being checked in?

**Comment by eerhardt** [comment]
> Why do you want to change this setting in arcade? Is there a specific project that would benefit from them being checked in?

I believe that when new repos are created that use arcade, they copy dotnet/arcade's .gitignore file. This was the case on a recent new repo, and the launchSettings.json entry in the .gitignore caused a bug (because the launchSettings.json file needed to be checked in).

**Comment by ViktorHofer** [comment]
I would prefer if we note that in the [Arcade Onboarding document] instead of removing the entry from arcade's gitignore file. Arcade doesn't benefit from checked-in launchsettings files today.

**Comment by eerhardt** [comment]
The PR that added this entry doesn't mention anything about launchSettings.json and why it would cause a problem: https://github.com/dotnet/arcade/pull/1100. It also happened long enough ago, that it might have been normal at the time to exclude them. However now they are meant to be checked into the repo. For example, if there's an ASP.NET API or Web app in the repo, you want your launchSettings checked in.

Regardless, I just made a PR here in order to help the next team that onboards from dotnet/arcade. I don't care if arcade has this change or not.

cc @mmitche

**Pull request closed without merging**
