### PR TITLE
Disable RemoteExecutor for single-file

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Helps with https://github.com/dotnet/runtime/issues/43079. It would be nice to make RemoteExecutor compatible with single file publishing eventually, but that would require more fundamental changes.

**Comment by jkotas** [comment]
cc @ViktorHofer Remote executor compatibility with single file publishing is something to consider in the test infra plans you are thinking about.

**Review by agocke — APPROVED** [review]
LGTM, thanks

**Comment by MichalStrehovsky** [comment]
> It would be nice to make RemoteExecutor compatible with single file publishing eventually, but that would require more fundamental changes.

FWIW, there is a path to make RemoteExecutor compatible with single file - it was nuked in #4142. It includes RemoteExecutor support.

**Pull request merged**
