### PR TITLE
Update feed url

### PR DESCRIPTION
**Pull request by garath**

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Can the dotnet-core feed be removed here too?

**Comment by garath** [comment]
> Can the dotnet-core feed be removed here too?

To be clear, are you saying you know that no packages from there are used, or are you asking me to check and remove if possible?

**Comment by mmitche** [comment]
Check and remove if possible.

**Review by riarenas — APPROVED** [review]

**Comment by garath** [comment]
Looking closer, it only needs one package, and it's actually resolving it from the dotnet-eng feed. So none of these are needed.

**Review by riarenas — APPROVED** [review]

**Comment by luchitor** [comment]
jkl

**Pull request merged**
