### PR TITLE
Add tizen arm rootfs build and cross build support

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
What is the plan for this? Is it going to replace Tizen armel, or is it going to be in addition to Tizen arm.

I do not think we need PR CI validation in dotnet/runtime for Tizen arm given that we have Tizen armel, Tizen x86 and Linux arm. Chances that all Tizen armel, Tizen x86 and Linux arm succeed and Tizen arm breaks are very low.

**Comment by gbalykov** [comment]
Both Tizen arm (hard-float ABI) and tizen armel (soft-float ABI) will be used in future, so we need to be able to perform cross build of dotnet/runtime for tizen arm too. I agree that CI specifically for Tizen arm is not needed.

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by gbalykov** [comment]
Thanks!

**Pull request merged**
