### PR TITLE
Add additional null checking in TargetFeedConfig.Equals

### PR DESCRIPTION
**Pull request by adiaaida**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

This change does the following:
* Add a distinct to the target channel ids so that we are not attempting to publish to the same channel multiple times (corresponding change to https://github.com/dotnet/arcade-services/pull/1922).
* Add additional null checking to string member variables in TargetFeedConfigs Equals method (for strings, either both should be null, or the strings should be equal to one another, but you can't do .Equals if the first string is null)

Addresses https://github.com/dotnet/arcade/issues/9508.

### CODE REVIEW

**Comment by adiaaida** [comment]
It's honestly pretty unclear what the source of the null ref is

**Comment by adiaaida** [comment]
The example where this failed was one where there were duplicates of channels to publish to (hence all the distinct-ing in various parts of this process). When one was removed (in this case, the regex one), the publish passed. It's possible that the regex default channel is to blame, but looking at the calls being made, that looks unlikely. We pass into the publishing code the right channel ids (but the same one, twice), and yet we still hit this failure.

**Comment by riarenas** [comment]
Here is an instance for "publishing does not exist for that channel"


```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error : Value cannot be null. (Parameter 'first')
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 85
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 107
##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22313.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error : Value cannot be null. (Parameter 'first')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 85
   at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 107
```

**Comment by riarenas** [comment]
Oh nevermind, that one is in the `TargetChannelConfig`, not in the `TargetFeedConfig`

**Comment by adiaaida** [comment]
Right, but that would also be that one of the list of things is null. The problem is, honestly, the line number that we're getting. It's [here](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetFeedConfig.cs#L94) on the if. Not on any particular line. It's more of a guess than anything else that it's one of the strings. But I also don't believe that the list of target feed configs that we are iterating over could have a feed that is null. I guess it's possible, but then I'd expect a null ref somewhere else as well. It is likely that the token is the thing that is null, IMO, given the code flow: [this](https://github.com/dotnet/arcade/blob/4156bc9b370b3c88557fd719456906790fa41c5b/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs#L53) passes a bunch of null tokens to the base class, which in turn sets that to be null in the target feed config.

**Review by riarenas — APPROVED** [review]

**Comment by adiaaida** [comment]
Ricardo and I talked offline. Sounds like the issue @mmitche is bringing up is a different null ref that we see when people try to publish to channels that aren't in PublishingConstants yet. This will not fix that, and is a different... unrelated issue.

**Pull request merged**
