### PR TITLE
Find dotnet cli package the same way that dotnet-install does

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by alexperovich** [comment]
@jonfortescue @AdamYoblick  this will fix using 3.0 preview stuff in helix.

**Comment by AdamYoblick** [comment]
Thanks!

**Comment by jonfortescue** [comment]
@alexperovich -- if you get a chance sometime this week or next, can you update the documentation to reflect these changes? https://github.com/dotnet/arcade/blob/master/Documentation/AzureDevOps/SendingJobsToHelix.md#the-simple-case

**Comment by AdamYoblick** [comment]
Thanks Alex, I will merge in the latest darc PR from arcade and try again

**Pull request merged**
