### PR TITLE
Move runtime runs to use LKG dotnet

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Comment by DrewScoggins** [comment]
@billwert @ooooolivia @adiaaida PTAL

**Comment by ooooolivia** [comment]
I suppose getting the exact dotnet version is to avoid further break of dotnet install scripts? Wondering if we could move this to ```ci_setup.py``` so it can apply to other runs as well.

**Comment by DrewScoggins** [comment]
> Would this line in [ci_setup.py](https://github.com/dotnet/performance/blob/afdf541e36060c0e38af3bd7737a9c977be09b71/scripts/ci_setup.py#L240)
> `dotnet_version = dotnet.get_dotnet_version(target_framework_moniker, args.cli)`
> override the version ?

Uhh, I don't think so. When I run this it uses the version that I pass it.

**Comment by billwert** [comment]
That line just parses out info from the installed framework. The passed in version is used here:

https://github.com/dotnet/performance/blob/afdf541e36060c0e38af3bd7737a9c977be09b71/scripts/ci_setup.py#L198

**Comment by DrewScoggins** [comment]
> I suppose getting the exact dotnet version is to avoid further break of dotnet install scripts? Wondering if we could move this to `ci_setup.py` so it can apply to other runs as well.

As it stands we only do runs in runtime and in the performance repo on core-sdk. In the performance repo we need to always be downloading the latest version and can't use this method. So we could move this into ci_setup.py and then do checks to see which repo we are in and act accordingly, but I think it is better to leave ci_setup.py as generic as possible and leave the repo specific stuff here.

**Comment by DrewScoggins** [comment]
@adiaaida could you merge this when the checks pass?

**Pull request merged**
