### PR TITLE
Update MSBuild task version

### PR DESCRIPTION
**Pull request by epananth**
### To double check:

Failing Build ->https://dev.azure.com/dnceng/internal/_build/results?buildId=2275564&view=results
test build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=2276170&view=logs&s=3df7d716-4c9c-5c26-9f45-11f62216640d
 

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by riarenas — CHANGES_REQUESTED** [review]
As far as I'm aware, our 17.7.2 package should not be used as it will bring in many CG alerts to all product repos. https://github.com/dotnet/arcade/issues/14055

**Comment by epananth** [comment]
So arcade-validation is going to be in a broken state until this is fixed? Or should I look for an alternative fix?

**Comment by riarenas** [comment]
Yes. That needs to be fixed.

**Comment by epananth** [comment]
arcade validation test https://dev.azure.com/dnceng/internal/_build/results?buildId=2282848&view=results

**Comment by riarenas** [comment]
The test build of arcade looks about how I expected it to and I don't see it generating any new alerts. Ill let this go through to Arcade-validation where I will make a final test to make sure, but this one might do the trick?

**Review by riarenas — APPROVED** [review]

**Comment by riarenas** [comment]
Oh, @epananth. Heads up that if this makes it through, since we already branched for release/8.0 this will need to be added to that branch as well

**Comment by riarenas** [comment]
oh. The test build doesn't exercise the signing validation step. I'm running this build of arcade-validation to get some validation and save some time. 

https://dnceng.visualstudio.com/internal/_build/results?buildId=2283391&view=results

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-validation?_a=history&typeId=17349662&alerts-view-option=active shows that there are no new alerts brought in by this branch and the new xcopy msbuild. I think this one is good.

**Pull request merged**
