### PR TITLE
Implement SigningValidation workaround

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/5328

Implement SigningValidation workaround due to the hosted agent having a certificate revoked.

Tested here: https://dnceng.visualstudio.com/internal/_build/results?buildId=614082&view=results

### CODE REVIEW

**Comment by joeloff** [comment]
So the work-around is to patch the certificate inside the local store?

**Comment by JohnTortugo** [comment]
Yeah, that's what they provided. There is another option, we can just patch the build definition job to execute in our build pools instead of the hosted agents. I didn't go for that option because I think the work around is simple enough to implement and has the benefit of not bringing additional load to our build pool.

**Comment by riarenas** [comment]
I am not a fan of this solution

Is Azure DevOps working on fixing the image at all?

**Comment by JohnTortugo** [comment]
@riarenas - Yeah, Azure DevOps said they are going to deploy the fix this week. 

I'll close the PR since you opted to disable signing validation and so we shouldn't hit the problem.

**Pull request closed without merging**
