### PR TITLE
Call publishing under AzureCLI and publish without SAS tokens.

### PR DESCRIPTION
**Pull request by mmitche**
### To double check:

* [ ] The right tests are in and the right validation has happened.  Guidance: https://github.com/dotnet/arcade/blob/main/Documentation/Validation.md

### CODE REVIEW

**Comment by premun** [comment]
@mmitche I am planning almost the same change but for all darc usage in Arcade. I want to send out an email first to partners as this will start triggering service connection approvals.

Is this meant for nuget feed publishing?

**Comment by premun** [comment]
@mmitche we will need to then obtain the BAR entra token in a step before yours if we need 2:

https://github.com/dotnet/arcade/pull/14843

**Comment by premun** [comment]
I think altogether it will look something like this:
https://dev.azure.com/dnceng/internal/_git/dotnet-arcade/commit/8babee88dc9d6cac6e800dfeb14338cdfa2cf2ac/

I am testing it https://dev.azure.com/dnceng/internal/_build/results?buildId=2472857&view=results

**Comment by mmitche** [comment]
We don't need this for nuget push actually. NuGet authenticate + nuget push works fine. We do pass a PAT right now, but it's only for purposes of downloading and comparing existing packages.

**Review by epananth — APPROVED** [review]

**Pull request merged**
