### PR TITLE
Update dependency SymUploader 

### PR DESCRIPTION
**Pull request by epananth**
Arcade test -> https://dnceng.visualstudio.com/internal/_build/results?buildId=949559&view=results
Maestro promotion pipeline -> https://dnceng.visualstudio.com/internal/_build/results?buildId=949589&view=results
Issue : https://github.com/dotnet/arcade/issues/6786

Had to change the following versions 

1) System.Buffers - 4.5.0 -> 4.5.1
2) System.Memory - 4.5.3 -> 4.5.4
3) System.Collections.Immutable - 1.5.0 -> 1.7.1

### CODE REVIEW

**Comment by riarenas** [comment]
Will this work in arcade-validation?

**Comment by epananth** [comment]
Yeah trying to get a successful arcade validation build, before I merge this changes..

**Comment by epananth** [comment]
arcade-validation -> https://dnceng.visualstudio.com/internal/_build/results?buildId=951199&view=logs&s=0d7db6e4-c533-50c8-77c7-b1b9fc049ed6&j=6b44ce6e-5697-5874-5d96-c5c395e52546

**Comment by epananth** [comment]
I think this fix broke a bunch of tests, figuring that out.. :/

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
