### PR TITLE
Fixes for SetupNugetSources scripts

### PR DESCRIPTION
**Pull request by riarenas**
## Description

Fixes for the scripts that set up the authenticated nuget sources in NuGet.config
* Add 3.1 feeds
* Various fixes in linux script which wasn't finding the right feeds and skipping some.
* Fixed usage comment for both scripts.

## Customer Impact

Can't get a servicing build of the product reliably without the workarounds from these scripts in place

## Regression

No

## Risk

Low

## Workarounds

No

### CODE REVIEW

**Comment by riarenas** [comment]
Test build that runs both windows and linux version of the script and uploads the modified nuget.config to build artifacts:: https://dev.azure.com/dnceng/internal/_build/results?buildId=445261&view=results

**Comment by riarenas** [comment]
The test failures are strange, these scripts do not run as part of the PR, so this PR changes nothing that should affect the outcome of the tests.

**Comment by mmitche** [comment]
> The test failures are strange, these scripts do not run as part of the PR, so this PR changes nothing that should affect the outcome of the tests.

Looks like a Helix issue a bit.

**Comment by riarenas** [comment]
Yeah, there's something weird. Just ran the top of the branch and got the same failures:  https://dev.azure.com/dnceng/public/_build/results?buildId=445313&view=results 

Filed https://github.com/dotnet/arcade/issues/4484 to investigate.

**Comment by mmitche** [comment]
Good to merge then?

**Comment by riarenas** [comment]
Yeah I believe so. Can you approve explicitly as merging is blocked without one?

**Pull request merged**
