### PR TITLE
Add NuGet.config for eng/common/internal/tools.csproj

### PR DESCRIPTION
**Pull request by riarenas**
https://github.com/dotnet/arcade/issues/8144

I tested an arcade official build with these changes here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1535352&view=results

I'll send communication to partners before merging this to let them know that these feeds will need to be added to nuget.configs if they use either of these two tools so that we stop having nuget feed dependencies hiding in csprojs.

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Comment by mmitche** [comment]
@riarenas Do you happen to know what teams this might be? Will we get into a situation where these feeds end up in the global nuget.config and will need infra to enable them (for OSS purposes).

**Comment by riarenas** [comment]
>Do you happen to know what teams this might be? Will we get into a situation where these feeds end up in the global nuget.config and will need infra to enable them (for OSS purposes).

I know runtime uses some of them, but I can whip up a search. I don't think we'd need to enable anything new even if the repo has to add it to the global nuget.config, as they are being currently restored from the same feeds? Unless you're thinking of something else that I'm not thinking of?

**Comment by riarenas** [comment]
for `https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json`, using a github search for `UsingToolIbcOptimization`: https://cs.github.com/?q=org%3Adotnet+UsingToolIbcOptimization# 

dotnet/msbuild‎
‎dotnet/roslyn‎
‎dotnet/wcf‎
‎dotnet/runtime‎
‎dotnet/project-system‎
‎dotnet/roslyn-tools‎
‎dotnet/deployment-tools‎

for `https://devdiv.pkgs.visualstudio.com/_packaging/VS/nuget/v3/index.json` `UsingToolVisualStudioIbcTraining`, https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Adotnet%20UsingToolVisualStudioIbcTraining%20NOT%20path%3Aeng%2Fcommon%2Finternal%2FTools.csproj

dotnet/msbuild
dotnet/roslyn

**Comment by mmitche** [comment]
> > Do you happen to know what teams this might be? Will we get into a situation where these feeds end up in the global nuget.config and will need infra to enable them (for OSS purposes).
> 
> I know runtime uses some of them, but I can whip up a search. I don't think we'd need to enable anything new even if the repo has to add it to the global nuget.config, as they are being currently restored from the same feeds? Unless you're thinking of something else that I'm not thinking of?

I'm mainly thinking of the behavior of OSS non-authenticated scenarios. They won't be using IBC in public builds, but will the builds pass if the feeds are added to the config? I'm not positive on the behavior of nuget around this at the moment.

**Comment by riarenas** [comment]
Ooh I see what you mean now. I'll run some experiments with the above repos to make sure.

**Comment by riarenas** [comment]
Yep, @mmitche as you suspected as soon as we add one of these feeds to the global nuget.config we'll fail public builds. I wonder if keeping these restoreSources here is just a necessary evil while there's a better alternative in NuGet to specify which packages should come from which feed?

**Comment by mmitche** [comment]
> Yep, @mmitche as you suspected as soon as we add one of these feeds to the global nuget.config we'll fail public builds. I wonder if keeping these restoreSources here is just a necessary evil while there's a better alternative in NuGet to specify which packages should come from which feed?

There may be 2 or 3 other options:
- Separate nuget config used when restoring the IBC data? (Not sure whether this would work or not)
- Have the internal feeds off by default, but have SetupNuGetSources.ps1 enable them on internal
- Add RestoreIgnoreFailedSources by default: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties

I kind of like the third option, actually...

**Comment by riarenas** [comment]
Ooh I like that third option too. In that case we'd only fail if there end up being missing packages after everything is said and done. I'll play around with that setting in this PR.

**Comment by riarenas** [comment]
Still trying to work out the best place to stick this in. Mostly making sure this doesn't impact local dev builds.

**Comment by riarenas** [comment]
Looks like this approach won't quite work:
* The switch seems to work in that all sources will be checked for packages even after seeing the 401s from the private feeds, causing nuget to not fail fast. However, there is still an error reported, and that ends up causing the build steps to fail in the end. I think we can probably make this work by hiding these errors somehow. But...
* As soon as we add these non-public feeds to the nuget.config, official builds will fail in the auto injected nuget.config security analysis: https://dev.azure.com/dnceng/internal/_build/results?buildId=1545629&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=4c89b337-069e-51f7-2aaa-f871608d682e due to not being able to check the private feeds for upstreams. 

I'll see if I can get the first approach working tomorrow morning, but I'm not all that optimistic as even if we use a separate nuget.config for these tools, it'll probably still get flagged by the scan.

I think our most feasible option is to do something like option 2 and only enable this sources via a script during internal builds.

**Comment by mmitche** [comment]
> Looks like this approach won't quite work:
> 
> * The switch seems to work in that all sources will be checked for packages even after seeing the 401s from the private feeds, causing nuget to not fail fast. However, there is still an error reported, and that ends up causing the build steps to fail in the end. I think we can probably make this work by hiding these errors somehow. But...
> * As soon as we add these non-public feeds to the nuget.config, official builds will fail in the auto injected nuget.config security analysis: https://dev.azure.com/dnceng/internal/_build/results?buildId=1545629&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=4c89b337-069e-51f7-2aaa-f871608d682e due to not being able to check the private feeds for upstreams.
> 
> I'll see if I can get the first approach working tomorrow morning, but I'm not all that optimistic as even if we use a separate nuget.config for these tools, it'll probably still get flagged by the scan.
> 
> I think our most feasible option is to do something like option 2 and only enable this sources via a script during internal builds.

@riarenas Is it a warning-as-error that we could suppress?

**Comment by riarenas** [comment]
@mmitche I think it's either warnings as error or something else we can end up suppressing. I'm less optimistic about the problem with the nuget.config feed scan. I was wondering if removing the auto injected step and running the analysis explicitly after we had already installed the credential provider might work? Might be more burden on the arcade templates to ensure we do all the right things but as long as the scan runs it might still be OK?

**Comment by mmitche** [comment]
@riarenas You can try, but I think the injected step will fail no matter what. The credentials it uses can't access the AzDO REST API cross-org,

A separate nuget.config will work, though it needs to contain only a single feed (and a clear), otherwise it will have the same issue. This should be fine for just restoring the IBC data?

**Comment by riarenas** [comment]
These two: 

* https://pkgs.dev.azure.com/devdiv/_packaging/VS/nuget/v3/index.json
* dotnet-core-internal" value="https://pkgs.dev.azure.com/devdiv/_packaging/dotnet-core-internal/nuget/v3/index.json

**Comment by mmitche** [comment]
> These two:
> 
> * https://pkgs.dev.azure.com/devdiv/_packaging/VS/nuget/v3/index.json
> * dotnet-core-internal" value="https://pkgs.dev.azure.com/devdiv/_packaging/dotnet-core-internal/nuget/v3/index.json

I suggest adding the VS feed as an upstream to dotnet-core-internal.

**Comment by riarenas** [comment]
I'll give that a shot!

**Comment by riarenas** [comment]
I think the upstream source approach works. The only issue I see now is that repos call this project in different ways. MSBuild and Roslyn have a separate yaml step where they nuget restore the project while [specifying the global nuget.config](https://github.com/dotnet/msbuild/blob/66f6305da5924287e8d45e50f89fd8232725e5b5/.vsts-dotnet.yml#L79-L86) So this change as is would break them. Runtime restores using arcade scripts, so they wouldn't be broken. 

In order to avoid surprise official build breaks, I think the best way to approach this is to do it in two steps:

1. Add the local nuget.config with the dotnet-core-internal-tooling feed. 
2. As the eng/common changes flow to repos, provide guidance / modify the YAML ourselves of the few repos that use this project so that their build pulls from the new nuget.config instead of using the one at the repo root. 
3. Once the repos are using the new config, delete the restoreSources from the csproj.

**Pull request merged**
