### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by ellahathaway**
Closes https://github.com/dotnet/arcade/issues/14273

Creates a codeowners file with source-build-internal as the owner of files `/eng/SourceBuild*`

### CODE REVIEW

**Review by garath — APPROVED** [review]

**Comment by lbussell** [comment]
There's an error in the CodeOwners file - "Unknown owner on line 4: make sure the team dotnet/source-build-internal exists, is publicly visible, and has write access to the repository"

**Comment by garath** [comment]
> There's an error in the CodeOwners file - "Unknown owner on line 4: make sure the team dotnet/source-build-internal exists, is publicly visible, and has write access to the repository"

This is perhaps because the team itself is not explicitly listed as having write access? It seems to meet the other requirements.

**Comment by ViktorHofer** [comment]
FWIW after this PR is merged I intend to add entries for the various libraries that the runtime team owns.

**Comment by ellahathaway** [comment]
> This is perhaps because the team itself is not explicitly listed as having write access?

This would be my guess. Is there a way to give dotnet/source-build-internal write access?

**Comment by garath** [comment]
> This would be my guess. Is there a way to give dotnet/source-build-internal write access?

Yes, but let's not do that. I don't think there's a real need to muck with ownership. Most or all of the members of that group have write access, so the right things can happen. 

I suggest just ignoring this linter warning.

**Pull request merged**
