### PR TITLE
Support DLLs in FilesToPublishToSymbolServer

### PR DESCRIPTION
**Pull request by MattGal**

### CODE REVIEW

**Comment by riarenas** [comment]
This will make it so DLLs that are published to the pdbartifacts azdo container also get published to the symbol servers to be indexed.

**Review by riarenas — APPROVED** [review]

**Comment by dougbu** [comment]
@MattGal and @riarenas will this cause problems in the dotnet/aspnetcore repo❔ We put Microsoft.Web.Xdt.Extensions.pdb and a few other PDBs into the PdbArtifacts container but no assemblies. The assemblies ship separately e.g. in Microsoft.AspNetCore.AzureAppServices.SiteExtension.nupkg.

**Comment by MattGal** [comment]
> @MattGal and @riarenas will this cause problems in the dotnet/aspnetcore repo❔ We put Microsoft.Web.Xdt.Extensions.pdb and a few other PDBs into the PdbArtifacts container but no assemblies. The assemblies ship separately e.g. in Microsoft.AspNetCore.AzureAppServices.SiteExtension.nupkg.

Not by default, if you want it to I can probably help you rig up a way to do so.  All this is saying is that if DLLs are included in specific, known-name artifact, to also submit them to the symbol service for indexing.  If your stuff is in a nupkg, everything not in the /ref/... path is already being submitted, so double-submission (again, only true if you submitted your DLLs as artifacts using a custom eng\Publishing.props)  is not ideal but also harmless.

**Comment by dougbu** [comment]
Sounds good. We'll leave well-enough alone then 😃

**Pull request merged**
