### PR TITLE
Port retry logic in tools.ps1 to release/3.x

### PR DESCRIPTION
**Pull request by adiaaida**
## Description

This change ports the retry logic that we added to tools.ps1 in master to release/3.x. Addresses https://github.com/dotnet/core-eng/issues/11899.

## Customer Impact

Without retry, we have intermittent errors due to IOExceptions when downloading various tools. This change mitigates those errors. See: https://github.com/dotnet/core-eng/issues/11897

## Regression

No

## Risk

Minimal. It simply wraps the original logic in a retry.

## Workarounds

No

### CODE REVIEW

**Comment by riarenas** [comment]
The change looks reasonable to me. Can you use this template for your pr description? https://github.com/dotnet/arcade/blob/master/Documentation/Policy/AskModeTellModeTemplate.md

Also adding @mmitche and @markwilkie to the PR, as approval from one of them is required for changes to the 3.x branch

**Review by MattGal — APPROVED** [review]
LGTM

**Comment by adiaaida** [comment]
@riarenas Done to the best of my ability. Thanks for the link.

**Review by markwilkie — APPROVED** [review]
Presuming this is indeed a straight port, I'm cool with this.

**Pull request merged**
