### PR TITLE
Split DotNetBackgroundPngFile into WixInstallerBackgroundFile msbuild property.

### PR DESCRIPTION
**Pull request by AraHaan**
Fixes https://github.com/dotnet/arcade/issues/8352.

### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by AraHaan** [comment]
I have verified that this change works for my bundle exe installers.

**Comment by AraHaan** [comment]
@NikolaMilosavljevic I have verified that this works with dotnet/runtime.

**Review by NikolaMilosavljevic — APPROVED** [review]
Looks good.

**Comment by AraHaan** [comment]
Ready to merge?

**Comment by AraHaan** [comment]
@NikolaMilosavljevic is this ready to merge?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic is this ready to merge?

Yeah, this can be merged now - thanks again!

**Pull request merged**
