### PR TITLE
Change format for production branches for CG

### PR DESCRIPTION
**Pull request by wtgodbe**
Based on some feedback from partner teams, I'm putting this PR to change the default format for branches that are opted in to CG (production branches). The changes are:

- `internal/release/*` becomes `release/*`. There are more repos using Arcade than I'd thought, and many don't have the concept of `internal/release/*` branches - that concept is pretty isolated to the mainline dotnet repos.
- Add `microsoft/*` and `dotnet/*` - there are ~8 arcade repos using this format for their release branches, and it's unlikely a dev would use this prefix for a dev branch.

CC @akoeplinger

### CODE REVIEW

**Comment by mmitche** [comment]
What about vs* branches (msbuild). /cc @rainersigwald

**Comment by wtgodbe** [comment]
> What about vs* branches (msbuild). /cc @rainersigwald

I think msbuild already built in their own custom logic for that, but I'm happy to include it here so they can remove that if they want (CC @JanKrivanek)

**Comment by wtgodbe** [comment]
Although now that I think about it, `vs` is not unlikely to be the prefix of a dev branch (e.g. every one of vseanreesermsft's PRs)

**Comment by JanKrivanek** [comment]
MSBuild branching nomenclature is currently planned to be held internal to MSBuild repo (captured here: https://github.com/dotnet/msbuild/pull/8695)

Btw. - do we actually want to keep the `refs/heads/internal/release/` as well (as addition to `refs/heads/release/`)? E.g. for cases where security fixes are developed on the internal branch first? Otherwise those would currently get scanned only after merging to public

**Comment by wtgodbe** [comment]
> Btw. - do we actually want to keep the refs/heads/internal/release/ as well (as addition to refs/heads/release/)? E.g. for cases where security fixes are developed on the internal branch first? Otherwise those would currently get scanned only after merging to public

We only want one or the other, since otherwise we get a lot of duplicate work. I think introducing a CG issue in a security fix is unlikely enough/not high enough impact to justify the 1-month gap.

**Comment by JanKrivanek** [comment]
Hmm, hmmm... I'm thinking if it would be possible to introduce 'releaseBranchPrefix' parameter, with default value of 'refs/heads/release/', while individual repos would have easy way to overwrite that. This way we can have single clean logic, while repos with internal branches can easily flip to scanning those; plus we can apply the logic to repos like MSBuild (where we would overwrite that parameter to 'refs/heads/vs')

**Comment by wtgodbe** [comment]
> Hmm, hmmm... I'm thinking if it would be possible to introduce 'releaseBranchPrefix' parameter, with default value of 'refs/heads/release/', while individual repos would have easy way to overwrite that. This way we can have single clean logic, while repos with internal branches can easily flip to scanning those; plus we can apply the logic to repos like MSBuild (where we would overwrite that parameter to 'refs/heads/vs')

I was thinking about something like this as well, but there are so many repos that use arcade, some of which don't get touched very often, that I figured it was unlikely we'd be able to get owners for all of them to update that param, and therefore we'd lose coverage for repos like that which don't use `release/*`. As far as I'm aware, dotnet/msbuild is the only repo using arcade that isn't covered by the pattern in this PR (I scanned through all darc subscriptions ingesting arcade to confirm this), so I think this approach leads to the least manual work

**Comment by JanKrivanek** [comment]
Sounds fair
Glad to hear this was considered and that you made decision based on collected evidence

**Review by JanKrivanek — APPROVED** [review]

**Comment by wtgodbe** [comment]
@mmitche @dougbu any concerns here?

**Review by mmitche — APPROVED** [review]

**Pull request merged**
