### PR TITLE
Add a non-shipping bit in the BAR

### PR DESCRIPTION
**Pull request by mmitche**
This maps onto the manifest produced as part of publishing

### CODE REVIEW

**Comment by alexperovich** [comment]
@ChadNedzlek fyi

**Comment by mmitche** [comment]
Oh crap...@ChadNed is arcade-services good to go yet?

**Comment by ChadNedzlek** [comment]
Not yet, I can't get signing/publishing to work, and @chcosta is working on some other stuff.

**Comment by ChadNedzlek** [comment]
What is "non-shipping" is that different than "toolset" (which I need to add later so our dependency graph isn't "every build that ever happened ever in the history of the universe"

**Comment by chcosta** [comment]
My stuff is implemented, but I won't have any documentation guidance for it until Tuesday.  I'm happy to take a look at it with you though.

**Comment by chcosta** [comment]
Shipping vs nonshipping - https://github.com/dotnet/arcade/blob/fa19e5a7dd74bca0dbea83b8a306457483534eec/Documentation/RepoToolset/MigrationToArcade.md#shipping-vs-nonshipping-packages

**Comment by mmitche** [comment]
@ChadNedzlek Shipping basically means "needs to go to customers", vs. "Needs to go somewhere accessible".  So for instance, coreclr produces no shipping packages, but it does produce shipping symbols and packages that are required to build corefx.

**Comment by ChadNedzlek** [comment]
@chcosta It... is Tuesday. Or do you mean a different Tuesday? :-)

**Comment by chcosta** [comment]
next tuesday, after vacation

**Pull request merged**
