### PR TITLE
Update version of Maestro.Tasks to latest in Arcade SDK

### PR DESCRIPTION
**Pull request by JohnTortugo**
Need to make Arcade SDK use the latest version of Maestro.Tasks so that PublishToBar can recognize some new properties in the BuildAssetManifest.

### CODE REVIEW

**Comment by alexperovich** [comment]
If you got this Maestro.Tasks version from the arcade-services master build then we will need to wait for a maestro production deployment to merge this. There are some changes in the task assembly that will fail if we don't deploy maestro.

**Comment by JohnTortugo** [comment]
This version is from this Build: https://dnceng.visualstudio.com/internal/_build/results?buildId=118457 does that include the change that you mentioned?

**Comment by alexperovich** [comment]
Yes, that build includes my changes.

**Comment by JohnTortugo** [comment]
@alexperovich are we OK to update this now?

**Comment by alexperovich** [comment]
once the release https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=3591 finishes.

**Pull request merged**
