### PR TITLE
Fix default TRX Test Results files extension

### PR DESCRIPTION
**Pull request by marek-safar**
Follow up fix for #6325

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@marek-safar isn't the default extension .trx?

**Review by alexperovich — CHANGES_REQUESTED** [review]
This is incorrect, "*.xml" test files are xunit results. "*.trx" files are VSTest files. This should not change.

**Comment by marek-safar** [comment]
The default can be .trx but Arcade overwrites it at https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/VSTest.targets#L23

**Comment by alexperovich** [comment]
We should change that then, this change as is will cause breaks because if the test results are VSTest the xunit thing will explode on them and if they are xunit the VSTest thing will explode on them.

**Comment by marek-safar** [comment]
Things don't explode it only fail with `No Result Found to Publish` error message as you can see for example here https://dev.azure.com/dnceng/public/_build/results?buildId=850899&view=logs&jobId=22fea640-1099-5f32-ec5d-316ad83f359a&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=bed643d2-0cc9-554b-140a-aac0a8564348

I'm fine with anything what makes TRX results processing work

**Comment by ViktorHofer** [comment]
I agree with Alex. Let's fix this in the VSTest target itself. Renaming trx to xml is weird as people would expect the xunit XML format.

**Comment by safern** [comment]
I didn't see this, but I just opened an issue for this: https://github.com/dotnet/arcade/issues/6419 and submitted a fix to change the file extension: https://github.com/dotnet/arcade/pull/6420

**Pull request closed without merging**
