### PR TITLE
Use "-verbose" reporter if no other is selected

### PR DESCRIPTION
**Pull request by ChadNedzlek**
Fixes: https://github.com/dotnet/arcade/issues/5146

### CODE REVIEW

**Comment by davidfowl** [comment]
@ChadNedzlek can we merge this?

**Comment by davidfowl** [comment]
Wait, does this only affect helix runs?

**Comment by ChadNedzlek** [comment]
Yes, because this is the built in Helix executor.  Since ASP.NET executes test inside Helix itself, I don't think it's going to apply to ASP.NET.

But I can definitely merge.

**Comment by davidfowl** [comment]
@ChadNedzlek what about non helix runs.

**Comment by ChadNedzlek** [comment]
This code is, as far as I'm aware, only used during Helix runs. I'm not sure where the code for local dev scenarios is located.  It's... possible the code is somehow shared, but I don't think so.  @alexperovich would know more.

**Comment by alexperovich** [comment]
The code for running tests locally on the build machine is not shared with this code. That is done in Arcade.Sdk somewhere. I don't have much experience with that mode.

**Comment by davidfowl** [comment]
Ok who has experience with it? It would also be  helpful to do that. It can be another PR though

**Comment by ChadNedzlek** [comment]
If the people wanting this feature won't actually be affected by itand it's going to significantly increase the size of the logs (Linq.Parallel.Tests has 186,409 tests, which are all going to show up in the console spew now), then I think I actually don't want to check this in.

**Pull request closed without merging**
