### PR TITLE
[release/6.0] Move to latest SDK

### PR DESCRIPTION
**Pull request by dougbu**
### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by dougbu** [comment]
Won't pass 'til release but ready

**Comment by mmitche** [comment]
@MattGal I'm not seeing actual failures in the Trx test log (no failures in the tests), but Helix is reporting exit code 1 for the run...any ideas?

**Comment by MattGal** [comment]
> @MattGal I'm not seeing actual failures in the Trx test log (no failures in the tests), but Helix is reporting exit code 1 for the run...any ideas?

Yes there was an outage @adiaaida was commenting about in the AzDO API; if the work item finishes happily but the helix client fails to write test results to AzDO this happens.  I think you can merge on red relatively safely here, or just re-run.

**Comment by dougbu** [comment]
Looks like something real is really wrong. Last run failed about the same way as the first.

**Comment by adiaaida** [comment]
We have opened an IcM with AzDO about this. Arcade issue is here: https://github.com/dotnet/arcade/issues/10358

**Comment by MattGal** [comment]
> We have opened an IcM with AzDO about this. Arcade issue is here: #10358

I think something's genuinely broken about run 1933413, so I kicked off a new pipeline run to see what happens.   We can escalate the IcM if needed but it's not broken universally (yet)

**Comment by dougbu** [comment]
It's almost nice that the problem reproduces so reliably 😦

We updated the SDK in 

- dotnet/aspnetcore#43168
- dotnet/efcore#28635

and didn't hit similar problems there.

**Comment by MattGal** [comment]
> It's almost nice that the problem reproduces so reliably 😦
> 
> We updated the SDK in
> 
> * [Merging internal commits for release/6.0 aspnetcore#43168](https://github.com/dotnet/aspnetcore/pull/43168)
> * [Merging internal commits for release/6.0 efcore#28635](https://github.com/dotnet/efcore/pull/28635)
> 
> and didn't hit similar problems there.

Arcade specifically does a bunch of custom types of test reporting, though the fact this isn't showing up in main-branch Arcade runs is very confusing (they use identical fake test results and the clients are versioned external-to-arcade).  The Test API team work on IDC time so I'll start a thread to try to bump up priority of the IcM I opened.

**Comment by dougbu** [comment]
@MattGal did you backport your #10358 workaround (#10380) to release/6.0❔ Pretty please if not done yet&hellip;

**Comment by dougbu** [comment]
Just in case
/azp run

**Review by MattGal — APPROVED** [review]

**Comment by MattGal** [comment]
> @MattGal did you backport your #10358 workaround (#10380) to release/6.0❔ Pretty please if not done yet…

@joeloff added it to another PR to 6.0, but effectively yes.  _Supposedly_ this is fixed now,  I'll get that verified today.

**Comment by dougbu** [comment]
We're all set but have two `Build Analysis` checks, one that's failing, and I don't have rights to merge into release/6.0. Help plz

**Comment by adiaaida** [comment]
@AlitzelMendez will the .Net Helix Build Analysis go away? I'm fine checking this in.

**Comment by riarenas** [comment]
Build analysis changed the app they use. However, since this PR was opened before the swap, it left a dangling failed check using the old app.

That dangling check didn't realize there were new runs. I clicked the rerun button which made the check update with the fact that the app was moved.

**Comment by dougbu** [comment]
> I clicked the rerun button

Excellent e2e testing @riarenas 😁

**Comment by riarenas** [comment]
The fact that older checks posted by the old app won't be updated is something we might want to make more widely known though @AlitzelMendez  @missymessa

**Comment by riarenas** [comment]
> Excellent e2e testing @riarenas 😁

That only worked because of the work that was deployed this week to make the re-run buttons do something for those checks, so it was a happy coincidence.

**Pull request merged**
