### PR TITLE
fix for "The specified solution configuration "Debug|MCD" is invalid" when running build.cmd

### PR DESCRIPTION
**Pull request by andresff**
### Description
This is a change because I was trying to build the EFCore solution and found an issue. I opened an issue at https://github.com/aspnet/EntityFrameworkCore/issues/18305 but @dougbu suggested to do the change in this repo

### Error
Restore completed in 5,81 sec for C:\Users\andres\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19510.4\tools\Tools.proj.
C:\Andres\Development\OSS\arcade\Arcade.sln.metaproj : error MSB4126: The specified solution configuration "Debug|MCD" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Andres\Development\OSS\arcade\Arcade.sln]. 

### Solution
Unset the env variable Platform before building.

### CODE REVIEW

**Comment by tmat** [comment]
I wonder if we could unset all environment variables, except for some well-defined subset. Ideally, the build wouldn't depend on any environment variables.

**Comment by andresff** [comment]
I see your point. In this case, this was causing the colllision. As I wrote in the code, the problem was at InstallDotNetCore.targets file
image

**Comment by dougbu** [comment]
@markwilkie I can merge but prefer someone on your team makes the final call.

**Comment by tmat** [comment]
@dougbu Sure, to fix this particular issue this is sufficient. But I think it would be valuable to explicitly pass any environment variables that the build depends on, so that we ensure our builds are deterministic.

**Comment by markwilkie** [comment]
approved

Also, @andresff could you file a new bug in arcade to explore what it would take to start w/ a known state (one of which are env variables) please?

**Comment by andresff** [comment]
@markwilkie I submitted this issue https://github.com/dotnet/arcade/issues/4167 but I don't know if that what you refer.

**Comment by markwilkie** [comment]
Perfect @andresff - thanks.

**Comment by jonfortescue** [comment]
@andresff This has approval and checks were passing last time, but there's some merge conflicts now. If you resolve those, I'll merge this.

**Comment by andresff** [comment]
I'll check this weekend

**Comment by andresff** [comment]
Done @jonfortescue

**Pull request merged**
