### PR TITLE
Reporting changes

### PR DESCRIPTION
**Pull request by ChadNedzlek**
Reintroduce #7383

This switches arcade from using a custom reporter, to using a reporter more tightly integrated with helix.  That reporter has the capacity to handle local test retrying and reporting to Azure DevOps for "flaky" tests.

To enable the retry, a file "eng/test-configuration.json" must be created following the documented schema.

### CODE REVIEW

**Review by AlitzelMendez — APPROVED** [review]

**Review by missymessa — APPROVED** [review]
LGTM shipit

I think this is good :)

**Comment by markwilkie** [comment]
This PR should not go in, it was based on a misunderstanding.  Closing.

**Comment by missymessa** [comment]
@markwilkie did you mean to close it? We can revert the iOS queue changes, but the rest of the changes are necessary for the test retries, I believe.

**Comment by markwilkie** [comment]
I don't think any reverts should happen, and we should not turn off the ios queues.

**Comment by markwilkie** [comment]
I see....this PR is MORE than just ios queues being turned off.  (duh)  Yea, let's be sure to NOT turn off the IOS queues but get the PR working.  (reopening)

**Comment by ChadNedzlek** [comment]
I reverted the removal of that queue. :-)

**Pull request merged**
