### PR TITLE
Add internal runtime args to source build template

### PR DESCRIPTION
**Pull request by mmitche**
These need to be passed through to correct restore an internal runtime

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
@MichaelSimons @dseefeld Prep for internal .NET 6 builds. This gets past a couple issues in aspnetcore, but it also looks like that repo will need additional work as it calls its own `.\build.sh` in its SourceBuild.props and doesn't include these parameters.

**Review by monstro805 — APPROVED** [review]

**Comment by MichaelSimons** [comment]
@JunTaoLuo, See https://github.com/dotnet/arcade/pull/7587#issuecomment-873191543

**Review by MichaelSimons — APPROVED** [review]

**Review by dseefeld — APPROVED** [review]

**Comment by missymessa** [comment]
Reverting this change, as it's causing Arcade's official build to fail: https://dnceng.visualstudio.com/internal/_build/results?buildId=1221868&view=results

**Comment by missymessa** [comment]
https://github.com/dotnet/arcade/pull/7598

**Pull request merged**
