### PR TITLE
Drop support for EOL alpine 3.9

### PR DESCRIPTION
**Pull request by am11**
* Remove 3.9.
* Set 3.13 as default.
* Add 3.14.

### CODE REVIEW

**Comment by am11** [comment]
cc @ViktorHofer, @janvorli based on https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux, we are currently only supporting Alpine 3.13 onwards. This PR sets default version to 3.13. I will send a subsequent PR to `dotnet-buildtools-prereqs-docker` so we get updated tags for both crossbuild arm (which is currently using 3.13) and crossbuild arm64 (which is currently using 3.9). We have already updated WithNode and helix to 3.13 and added 3.14 in docker matrix.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
@ViktorHofer, this and https://github.com/dotnet/runtime/pull/57324 are related (but not dependent) and ready for review/merge. :)

https://github.com/dotnet/runtime/pull/57324 is:
* WithNode: used for building x64 binaries.
* helix: used for testing x64, arm64, arm.

This PR + the future dotnet-prereq PRs with this change and runtime PRs with consuming the centos updated image:
* crossbuild: used for cross-building arm64 and arm binaries.

so it turned out, that "alpine update" story has a long tail than I imagined. 😅

**Comment by ViktorHofer** [comment]
Thanks for the great work again @am11 👍

**Pull request merged**
