### PR TITLE
Revert to previous arcade to unblock official builds

### PR DESCRIPTION
**Pull request by mmitche**
The previous bad arcade build (my fault) passed through validation and got checked into arcade. This then blocks the fix from flowing because we can't currently create an official build. Roll arcade back to the previous version to unblock.

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Comment by mmitche** [comment]
Interestingly, there is SB validation in arcade-validation that I think should have caught this, but didn't. Need to investigate why.

**Review by MichaelSimons — APPROVED** [review]

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/issues/14695

**Comment by mmitche** [comment]
quick official test in parallel to verify: https://dev.azure.com/dnceng/internal/_build/results?buildId=2423380&view=results

**Comment by mmitche** [comment]
Looks good in official.

**Pull request merged**
