### PR TITLE
Reverting back to using AzureCosmosDb

### PR DESCRIPTION
**Pull request by Anipik**
using this ```WindowsAzure.Storage``` was missing commits.
And sometimes was throwing ```WebRequestsException``` due to too many requests.
The error was not getting repro with my git credentials and local machine.

These failures are not encountered while using AzureCosmosDbTable package probably because the back end database is azure cosmos db rather than windows storage.

this line is added because the default package that gets installed lead to runtime failure
```
<MicrosoftAzureDocumentDBVersion>1.22.0</MicrosoftAzureDocumentDBVersion>
```

### CODE REVIEW

**Comment by eerhardt** [comment]
> And sometimes was throwing WebRequestsException due to too many requests.

I find this hard to believe.  According to:

https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets

> Maximum request rate per storage account | 20,000 requests per second

Are we using our own storage account or is it shared with some other tool?  There's no way this service should be exceeding 20k requests a second.

**Comment by Anipik** [comment]
@eerhardt I also think that it cant make that many requests.
something is wrong here but the exception thrown was 
```
2018-07-08 21:02:46,184 [27] INFO  Microsoft.DotNet.GitSync.Program Running sanity check for corefx/master
fatal: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (429) Too Many Requests
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, O
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, O
   at Microsoft.WindowsAzure.Storage.Table.TableQuery.ExecuteQuerySegmented(TableContinuationToken token, CloudTable
   at Microsoft.WindowsAzure.Storage.Table.TableQuery.<>c__DisplayClass2.<Execute>b__1(IContinuationToken continuati
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.GitSync.Program.RetrieveOrInsert(String SourceRepo, String branch, String sha, String TargetR
   at Microsoft.DotNet.GitSync.Program.SanityCheck(RepositoryInfo repository, String branch)
   at Microsoft.DotNet.GitSync.Program.<ProcessAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.DotNet.GitSync.Program.Step(CancellationToken token)
   at Microsoft.DotNet.GitSync.Program.Run()
Request Information
RequestID:ff3e81b8-5936-4d63-bfdf-93b92a8d9ed7
RequestDate:Sun, 08 Jul 2018 21:02:47 GMT
StatusMessage:Too Many Requests
ErrorCode:429
ErrorMessage:Message: {"Errors":["Request rate is large"]}
ActivityId: 4aa0c52d-f0e7-4366-a265-f1217ccd1278, Request URI: /apps/e0714b10-8947-43e3-afce-75b9afad7ec7/services/9
ResponseTime: 2018-07-08T21:02:48.1604594Z, StoreReadResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus2-fd6.d
88a32/replicas/131727111058803794s/, LSN: 204, GlobalCommittedLsn: 203, PartitionKeyRangeId: , IsValid: True, Status
```

I tried to repro the bug . but was not able to. It occurred only on the machine where it is deployed.

**Comment by Anipik** [comment]
> Are we using our own storage account or is it shared with some other tool? There's no way this service should be exceeding 20k requests a second.

We are using a our own storage account. I can give you the access if you wanna take a look at the back end ?

**Comment by Anipik** [comment]
@eerhardt i will try to repro the bug again with windowsAzure verison (as discussed offline).
I have improved the sanity check for this PR (calling api just once per commit)

**Pull request merged**
