### PR TITLE
Exclude properties when set to 'none'

### PR DESCRIPTION
**Pull request by chcosta**
Exclude properties when they are set to 'none'.

Fixes https://github.com/dotnet/core-eng/issues/3804

### CODE REVIEW

**Comment by chcosta** [comment]
This doesn't actually work.  It doesn't appear that I can access the matrix values ('_PublishType' and '_SignType') during the template evaluation context.  =(

**Comment by chcosta** [comment]
It's possible this works but a recent variable name change (`PB_ -> DotNet`) is causing the issues I'm seeing.  I'll wait for that work to settle down and then try to revalidate

**Comment by mmitche** [comment]
@chcosta Those are parameters, not variables, so they'll have to be on step conditionals instead.

**Comment by jcagme** [comment]
Yeah, I tried `${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), notin (and alos ne)(variables['_PublishType'], 'none')) }}:` yesterday and it did not had any effect. 

I found that `<_PublishToBlobStorage Condition="$(PB_PublishType.Contains('blob'))">true</_PublishToBlobStorage>` was removed from `Publish.proj` with https://github.com/dotnet/arcade/commit/09d6fc41d31eacbaa1ff2903da62beec5c0166fe so I plan to add it back while we agree on the new variable and to unblock myself on completing the push to BAR work.

**Comment by mmitche** [comment]
@chcosta Those don't appear to be variables in the .vsts-ci.yml, as far as I can tlel.

**Comment by chcosta** [comment]
Closing in favor of @jcagme 's changes which are forthcoming

**Pull request closed without merging**
