### PR TITLE
Add Mono to GitSync mirrored repos

### PR DESCRIPTION
**Pull request by akoeplinger**
We'll need to sync System.Private.CoreLib source code into the mono github repository.

@Anipik is there anything else to do other than adding mono to https://github.com/dotnet/versions/blob/8dad694f389747c6c6e8dfba205fffd4e6a45baa/Maestro/subscriptions.json#L2079 to set up the mirror?

### CODE REVIEW

**Comment by Anipik** [comment]
Currently the mirrors are bi-directional for each pair, which means if a commit enters in one repo it gets mirrored to other one. Do we need a bi-Directional here or a uni-directional will suffice ? if we need a bidirectional, then we will need to setup a webhook

 who is going to maintain this mirror because sometimes it ends up in merge conflicts and or exceed api limitation.

we will have to do some setups like a bot account with priviledges to open PR in bot account and also setup the machine with mono repo.


i think it would be nice if we could remove the names the repo entirely from the tool and specify them in a settings file. then anybody can use it for any set of repos.

**Comment by Anipik** [comment]
I opened the pr to make repo pairs dynamic https://github.com/dotnet/arcade/pull/1635 
after the pr is merged, I can help you with setting up everything else

**Comment by akoeplinger** [comment]
> Do we need a bi-Directional here or a uni-directional will suffice ? if we need a bidirectional, then we will need to setup a webhook

I think uni-directional would be fine at least for now, but I can add the webhook to the mono repo too.

>  who is going to maintain this mirror because sometimes it ends up in merge conflicts and or exceed api limitation.

Are you talking about the mirror service itself or the PRs it creates? We'll take care of resolving merge conflicts on the PR.

> we will have to do some setups like a bot account with priviledges to open PR in bot account and also setup the machine with mono repo.

This sounds like you want us to setup the mirror service ourselves, can't we just use your existing one?

The #1635 PR looks great :)

**Comment by akoeplinger** [comment]
We don't plan on editing the sources in Mono right now and as I said adding the webhook is fine so we can make it bidirectional if that's easier :)

**Comment by akoeplinger** [comment]
Actually, another question while I remember it: does the mirror work with an empty destination folder or should we pre-seed the folder with a snapshot of e.g. the corefx System.Private.CoreLib folder?

**Comment by Anipik** [comment]
> We don't plan on editing the sources in Mono right now and as I said adding the webhook is fine so we can make it bidirectional if that's easier :)

i think unidirectional should be good, if we are not editing any sources.

> Actually, another question while I remember it: does the mirror work with an empty destination folder or should we pre-seed the folder with a snapshot of e.g. the corefx System.Private.CoreLib folder?

no it wont work on an empty folder. we will require some consistent state. When we will start the mirror for mono, the folders should be synced or the commits need to be in our database.

i talked with dan offline and i can maintain the mirror for you. can you provide me with the link to mono repo ?

**Comment by Anipik** [comment]
Thanks, i will let you know if anything else needs to be done on your side

**Comment by Anipik** [comment]
@akoeplinger I have deployed the mirror for mono repo as well. currently the mirror is hooked up with corefx repo which I think is sufficient. Let me know if you see any commit has not been mirrored

**Comment by akoeplinger** [comment]
@Anipik since most CoreLib changes land in the CoreCLR repo first I think it'd make more sense to watch that one. Otherwise I think we'd need to wait for two cycles (coreclr -> corefx -> mono) for new changes to propagate right?

Thanks for setting up the mirror!

**Comment by Anipik** [comment]
Yeah you are right, most of the changes to SPC are made in coreclr. I will add mono to corefx, coreclr and corert, after its working perfectly with one repo.
The mirror runs every 10 minutes.

**Pull request closed without merging**
