### PR TITLE
Remove -x for XHarness iOS payload script

### PR DESCRIPTION
**Pull request by premun**

### CODE REVIEW

**Comment by premun** [comment]
@akoeplinger I have removed `set -x` to reduce the noise in XHarness logs. Most of it was just parsing the arguments and in future, unlocking the keychain (which we might want to not log at all).

Example new logs:
- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-6815-merge-7d47ed4b9db74ac8a8/System.Numerics.Vectors.Tests/console.a5ee380e.log?sv=2019-07-07&se=2021-02-07T14%3A29%3A27Z&sr=c&sp=rl&sig=r%2BA3XPPfARMKgq%2BAo6dyVmKDNSk5vDnAROYiBMTN4Lc%3D
- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-6815-merge-7d47ed4b9db74ac8a8/HelloiOS/console.fb9d695c.log?sv=2019-07-07&se=2021-02-07T14%3A29%3A27Z&sr=c&sp=rl&sig=r%2BA3XPPfARMKgq%2BAo6dyVmKDNSk5vDnAROYiBMTN4Lc%3D

Would you like this change or do you find value in the more verbose one?

**Review by akoeplinger — APPROVED** [review]
This is fine I think, we don't need the log of commands normally.

You don't need to restore `set -x` in the exit points, it won't propagate to outside scripts.

Also it looks like we use `set +e` on line 100 which covers the majority of the script so I wonder whether the `set -e` on line 9 even makes sense.

**Comment by premun** [comment]
@akoeplinger I added set `-x` so that we know what the script ends with - it's nice for full text search too.

You are right about the `-e`, I will remove it

**Comment by premun** [comment]
On a second thought - I will just output exit code in the parent script and remove `-x`

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
