### PR TITLE
Revert "Work around implicit usings breaking change"

### PR DESCRIPTION
**Pull request by markwilkie**
Reverts dotnet/arcade#7745

### CODE REVIEW

**Comment by mmitche** [comment]
This has no diffs...is this right @markwilkie ?

**Comment by markwilkie** [comment]
Well fooy....the 'revert' button didn't work.  Nevermind, I'll do this the right way.

**Comment by riarenas** [comment]
@markwilkie I'm pretty sure this was reverted a whole ago and that would explain the lack of diff

**Comment by markwilkie** [comment]
Thanks @riarenas

**Comment by riarenas** [comment]
Found it: https://github.com/dotnet/arcade/commit/3dd12f0a1d25fa29b84e38b7d2345a693f4ae45e

**Pull request closed without merging**
