### PR TITLE
Add build task to generate a rsp file from the CoreFX test exclusion list.

### PR DESCRIPTION
**Pull request by davmason**
I didn't see a good place to stash this so I created a new assembly. There currently is the known limitation that whole test assemblies can't be excluded, to work around we will have to exclude every namespace/class from the assembly we don't want to run.

CC @mikem8361 @hoyosjs

### CODE REVIEW

**Comment by davmason** [comment]
@tmat @ViktorHofer can one of you take a look? This is for the corefx testing in coreclr.

**Comment by ViktorHofer** [comment]
@davmason can't coreclr use the rsp format that is supported by xunit instead of the json one? That would remove the necessity of this code.

**Comment by davmason** [comment]
@ViktorHofer this code is to parse the json file and generate the rsp, so coreclr will be using the rsp file.

Unless you mean check in the rsp file instead of the json and skip this step?

**Comment by ViktorHofer** [comment]
> Unless you mean check in the rsp file instead of the json and skip this step?

Exactly.

**Comment by hoyosjs** [comment]
@ViktorHofer Don't have any strong objections, I'd considered something like this. The only advantage the JSON file had was the ability to add a reason per disabled test. As long as these are tracked by issues, no worries. However, I expect that to bloat issue count on CoreCLR.

**Comment by ViktorHofer** [comment]
You can add comments with `#` which should be sufficient for reason texts I guess?

**Comment by davmason** [comment]
Sorry to go dark here. I have been trying to validate that it works end to end with checking in the file directly and running in to lots of unrelated issues. It looks like it is working at this point though.

**Pull request closed without merging**
