### PR TITLE
Eliminate unnecessary legs

### PR DESCRIPTION
**Pull request by mmitche**
I took a look at the Kusto data for arcade, to try and see how correlated failures in some configurations are. It turns out the failure rates for our Debug/Release pairs for Linux and Windows fail at the same rate. That basically just means that we should be able to eliminate one without affecting quality. This should improve reliability and reduce VM/helix usage.

I left Windows_Release and Linux_Debug to cover the official build as well as Debug build configurations.

Raw data on main from last year (PR or otherwise)

```
Windows_NT Build_Debug	    succeeded	        1713
Windows_NT Build_Debug	    failed	            69
Windows_NT Build_Debug	    succeededWithIssues	8
Windows_NT Build_Debug	    canceled	        3
Windows_NT Build_Release	succeeded	        1706
Windows_NT Build_Release	succeededWithIssues	12
Windows_NT Build_Release	failed	            71
Windows_NT Build_Release	canceled	        4

Linux Build_Debug	        succeeded	        1678
Linux Build_Debug	        succeededWithIssues	26
Linux Build_Debug	        failed	            88
Linux Build_Debug	        canceled	        1
Linux Build_Release	        succeeded	        1691
Linux Build_Release	        succeededWithIssues	18
Linux Build_Release	        failed	            83
Linux Build_Release	        canceled	        1
```

### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Comment by MattGal** [comment]
Looks like you need to go here https://github.com/dotnet/arcade/blob/main/azure-pipelines.yml#L189 and make adjustments to match your cuts.

Apple_Devices Build_Release & Android_Simulators Build_Release need linux artifacts, so make both debug
Android_Devices Build_Debug needs Windows artifacts so make it release

**Review by missymessa — APPROVED** [review]
LGTM shipit

**Review by MattGal — CHANGES_REQUESTED** [review]
(left comment; can't pass til the test legs use the pipeline artifacts produced in the build legs correctlY)

**Comment by mmitche** [comment]
> Looks like you need to go here https://github.com/dotnet/arcade/blob/main/azure-pipelines.yml#L189 and make adjustments to match your cuts.
> 
> **Apple_Devices Build_Release & Android_Simulators Build_Release** need linux artifacts, so make both debug **Android_Devices Build_Debug** needs Windows artifacts so make it release

Yep, I'll poke at it tomorrow morning.

**Comment by MattGal** [comment]
I think you still need to change this one to a release since it uses windows artifacts : https://github.com/dotnet/arcade/blob/a95f2cc3bd233767f07fd5d0ca315728a3c857bf/azure-pipelines.yml#L290

**Comment by mmitche** [comment]
@MattGal Looking good now.

**Review by MattGal — APPROVED** [review]

**Pull request merged**
