### PR TITLE
Update SDK to preview 3

### PR DESCRIPTION
**Pull request by mmitche**
### To double check:

* [ ] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/core-eng/tree/master/Documentation/Validation

### CODE REVIEW

**Review by riarenas — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by mmitche** [comment]
@alexperovich It looks like whatever is processing the binlog needs to support a newer version. Can you take a look?

**Comment by ViktorHofer** [comment]
@MattGal that should be the corresponding issue: https://github.com/dotnet/arcade/issues/7024.

**Comment by alexperovich** [comment]
I think this was hit by runtime a while ago, https://github.com/dotnet/arcade/pull/7274 should fix this.

**Comment by ViktorHofer** [comment]
@alexperovich did you see https://github.com/dotnet/arcade/issues/7024 which I filed some months ago?

**Comment by alexperovich** [comment]
I did, and it needs to be done, but it would involve adding arcade publishing to a repo that doesn't even know about arcade.

**Comment by ViktorHofer** [comment]
I don't see the SDK change flowing into the repositories, i.e.: https://github.com/dotnet/runtime/commit/9c39208d845f4cf36d071635702f3e2a8b362e43. Is that intentional?

**Comment by mmitche** [comment]
Blocked up here: https://github.com/dotnet/arcade-validation/pull/2268/checks?check_run_id=2449219260

**Comment by ViktorHofer** [comment]
Did you know about the pipeline being blocked? If not, would it make sense to monitor that repo via automation to notify in case something is blocked?

**Comment by mmitche** [comment]
I think it is monitored, just no one has gotten around to investigating the issue.

**Pull request merged**
