### PR TITLE
Adding hook for custom repo testing logic

### PR DESCRIPTION
**Pull request by sfoslund**
See https://github.com/dotnet/sdk/pull/14493 for the SDK side of this change

### CODE REVIEW

**Comment by sfoslund** [comment]
Not sure why linux tests are timing out now but when I originally opened this PR all legs were passing.

**Review by wtgodbe — APPROVED** [review]
Cool!

**Comment by sfoslund** [comment]
Is this a known CI failure or is it something with the PR?

**Comment by riarenas** [comment]
@dotnet/dnceng it looks like the xharness helix leg is timing out. Can someone take a look?

@sfoslund this doesn't look related to your PR.

**Comment by premun** [comment]
@riarenas yeah, yesterday and today we got 2 spikes of long taking work items in the queue. It's an OnPrem queue, so we cannot scale it. Unfortunately, there's not much I can do now, but we will investigate.

The spike should be over in 30 minutes:
image

**Pull request merged**
